### ISSUE TITLE
TeachOSM for High School

### ISSUE THREAD

**Issue by shawnmgoulet** [mozilla/global-sprint#10]
**[ Project Contact ]** @shawnmgoulet
**[ GitHub Repo ]** https://github.com/shawnmgoulet/teachosm-for-high-school
**[ Track ]** Web Literacy
**[ Community ]** 
**[ Location ]** Online/Barnstable, MA, USA / EDT
### Description
This project provides educators with scale-able OpenStreetMap (OSM) geography-based educational modules developed to integrate with the United States AP Human Geography curriculum, exposing students to 21st century mapping technology.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @shawnmgoulet! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by chadsansing** [comment]
@zee-moz, @auremoser - are there mapping communities that come to mind that might help with this project?

**Comment by shawnmgoulet** [comment]
@chadsansing @zee-moz @auremoser - Related, I'm constantly sharing progress/ideas on the osmus.slack.com #teachosm channel.  I also sent an initial email to the TeachOSM listserv sharing that the project was accepted as a Moz OLT project and asking for assistance creating module-based curriculum.  Thus far, the response RE assistance has not been strong.

**Comment by chadsansing** [comment]
@shawnmgoulet - I will ask around some educator circles within the week, as well.

**Comment by shawnmgoulet** [comment]
@chadsansing - that's great, I appreciate your help.

**Comment by shawnmgoulet** [comment]
@zee-moz : Image for Moz Pulse:

![image](https://cloud.githubusercontent.com/assets/3179974/25207162/b76ae1fe-253a-11e7-8222-1ff01d8324ba.png)

**Comment by shawnmgoulet** [comment]
@chadsansing : For a template for curriculum development, you suggested the possibility of using the Thimble template:

- Thimble: https://thimbleprojects.org/chadsansing/107281/#overview
- GitHub: https://github.com/mozilla/curriculum-final/tree/gh-pages/blank-template

Do you know if it integrates with a site constructed with Markdown-Jekyll-GitHub pages?
This curriculum will end up on [TeachOSM](http://teachosm.org/) which uses that architecture, so integration matters there.  Thanks a bunch!

**Comment by chadsansing** [comment]
@shawnmgoulet, that's a question beyond my knowledge; both templates are pretty much straight HTML with CSS and a little JS, for whatever that's worth :)

**Comment by shawnmgoulet** [comment]
@chadsansing all good, figured I'd see if you knew off-hand, I'll figure it out.

**Comment by abbycabs** [comment]
@shawnmgoulet if you want to write in markdown directly, I would start by just committing markdown files directly in your GitHub repository. GitHub does a good job rendering them in the browser. That way it'll be easier to move to jekyll when you're ready!

**Comment by chadsansing** [comment]
Thanks, @acabunoc!

**Comment by zee-moz** [comment]
@shawnmgoulet we have some friendly curriculum templates that we've used for a few different projects, like our [Working Open Workshops](http://mozillascience.github.io/working-open-workshop/writing_readme/) and some of our [Open Data curriculum  projects](https://cbahlai.github.io/rqm-template/). You're welcome to reuse them! @auremoser help design and wrangle them, so she can able to answer any questions you have 😸

**Comment by zee-moz** [comment]
@shawnmgoulet sorry, in previous comment I said these were markdown, and they are not! we'd planned for them to be, but they never got there. but they might be handy anyway, and @auremoser has lots of experience with Jekyll

**Comment by shawnmgoulet** [comment]
thanks for all of this @chadsansing @acabunoc @zee-moz.  Come to find out that the format for the TeachOSM site re-build (they're hoping for June/July) might not be in Jekyll.  Because of that, I'm thinking we'll just go with @acabunoc's suggestion initially and then we can branch in the direction of the site re-build once it is ironed out.  Hopefully that makes sense...

Also, [this](https://flyingzumwalt.github.io/jekyll-curriculum-template/) looks like a clean jekyll curriculum template if the site stays GH-pages.

**Comment by shawnmgoulet** [comment]
`This is ready for Mozilla Pulse` :balloon:

**Comment by jalbertbowden** [comment]
commenting because i'm interested in hacking during the sprint

**Comment by geomantic** [comment]
Just signaling my interest in hacking as well. 

Also, I expect [TeachOSM](http://teachosm.org) to remain in gh-pages/jekyll for the foreseeable future. So even if we move to Gitbook for publishing, we'll likely be generating content in markdown.

**Comment by abbycabs** [comment]
Pulsed https://www.mozillapulse.org/entry/376

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
