### ISSUE TITLE
Comparing Changes on Government Web Pages

### ISSUE THREAD

**Issue by dcwalk** [mozilla/global-sprint#102]
**[ Project Contact ]** @dcwalk, @patcon, or @titaniumbones
**[ GitHub Repo ]** https://github.com/edgi-govdata-archiving/web-monitoring and https://github.com/edgi-govdata-archiving/web-monitoring-processing/
**[ Track ]** Web Literacy
**[ Community ]** 
**[ Location ]** Toronto, ON  ET (UTC/GMT -4) _We'll be at the Toronto Mozilla Office!_
### Description
The Environmental Data & Governance Initiative (EDGI) has been monitoring changes to the content on tens of thousands of US government web pages. A team of analysts manually inspecting most changes has already identified significant changes to the government’s web presence, however, our work process is extremely labour-intensive. As a result we are building an open-source platform with an easy to use interface compare millions of federal web pages and review ‘diffed’ web page snapshots.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @dcwalk! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @acabunoc. We're here to help you through this process.

**Comment by patcon** [comment]
cc: @linamnt :)

**Comment by dcwalk** [comment]
![mozsprint-monitoring](https://cloud.githubusercontent.com/assets/4692834/26495137/3f7e70fc-41f0-11e7-83ac-06ca56371ba6.png)

**Comment by dcwalk** [comment]
`This is ready for Mozilla Pulse`! 🎈

**Comment by abbycabs** [comment]
This is great @dcwalk! I'll take a look and pulse this soon :)

**Comment by dcwalk** [comment]
Hey! @acabunoc just wondering if this has been added to pulse! We want to link to that view and I'm having trouble ~seeing~ finding it.

**Comment by abbycabs** [comment]
Thanks for the nudge @dcwalk!

Can you add a license file to this repo:
https://github.com/edgi-govdata-archiving/web-monitoring
Even if it's your documentation repo, you can add a CC license to the content

Once that's done, I think you're good to go 💯 🎉

**Comment by dcwalk** [comment]
Added!

**Comment by abbycabs** [comment]
pulsed 🎈 https://www.mozillapulse.org/entry/326

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
