### ISSUE TITLE
Green-Analytics

### ISSUE THREAD

**Issue by konark-cliqz** [mozilla/global-sprint#108]
**[ Project Contact ]** Konark Modi
**[ GitHub Repo ]** https://github.com/cliqz-oss/green-analytics
**[ Track ]** Privacy + Security
**[ Community ]** 
**[ Location ]** Munich, UTC+01:00
### Description
Green-Analytics

As per the study Tracking the Trackers[1], ~78% of the page loads in Germany have at least one third-party tracker, almost ~42% of Page loads of Google analytics and ~22% have a Facebook tracker.

Green analytics is meant to provide solutions :

	A. Privacy first analytics.
	B. Privacy first social sharing features.

A. Privacy first analytics :
The aim is to build an analytics service, which the users can use on their websites, blogs etc. The existing solutions like Google Analytics, Piwik etc all rely on server-side aggregation which means they cookies, IP or other parameters to link the message on the backend.

Privacy preserving analytics service is meant to cover a wide range of use-cases:

Unique visits and page loads.
Returning customers.
Goal conversion to track campaigns.
Cross site correlations.
In-site click-throughs.
Visits and time in page per user (without beacons).

Without having to rely on the cookies or any such thing. This approach unlike the industry de-facto standard, relies on client-side aggregation. Which means the user is the owner of the data, any only emits an aggregated event, without any
identifier.

Based on the implementation of Green-tracker by Josep from Cliqz[2] , Demo[3], objective at the Mozilla global sprint is to :
	1. Make people aware of doing analytics in a privacy preserving manner.
	2. Provide a generic script, which should be ready-to use for people who want to do analytics on their projects.

Apart from just providing an analytics scripts, the task would be to provide :
	1. Green analytics for websites & open-source market leading CMS like Wordpress / Drupal
	2. Basic backend which collects data and generates analytics report and dashboards.

If the time permits, we would also like to build a small SDK for Mobile app analytics based on the same approach.

B. Privacy first social sharing features : The other very common way of tracking users across websites is adding social sharing buttons, another component of Green analytics project will be identify plugins which still allow the users to share over social media but needs explicit consent.

There are already open-source solutions available for static websites / CMSes , we should not try and re-invent the wheel, instead we should create a comprehensive list of the available solutions and create a in-depth how-to guide.

Footnotes:

1  Tracking the Trackers: http://www2016.net/proceedings/proceedings/p121.pdf
2. Data Collection without Privacy Side-Effects : http://josepmpujol.net/public/papers/big_green_tracker.pdf
3. Demo Green-tracker : http://site1.test.cliqz.com/

***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, Konark Modi! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @acabunoc. We're here to help you through this process.

**Comment by konark-cliqz** [comment]
![greenanalytics](https://cloud.githubusercontent.com/assets/10497229/26562007/0df278f0-44c3-11e7-8a18-134d0982ebfe.jpg)

**Comment by konark-cliqz** [comment]
This is ready for Mozilla Pulse

**Comment by abbycabs** [comment]
Hey @konark-cliqz!

I'd love to see you [create a few issues](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) containing chunks of work people can do during the sprint.
https://github.com/cliqz-oss/green-analytics/issues

Once that's done, this should be ready for pulse 🎉

**Comment by konark-cliqz** [comment]
Hey @acabunoc :) . Can you check again, I have chalked out rough ideas to implement during the sprint. Will add more details / issues. Thank you

**Comment by abbycabs** [comment]
Perfect! Can you add a label called `mozsprint` to the ones you want worked on during the sprint? That way they'll show up here:
https://github.com/search?q=label%3Amozsprint&type=Issues&utf8=%E2%9C%93

**Comment by konark-cliqz** [comment]
@acabunoc : Done !

**Comment by abbycabs** [comment]
Thanks @konark-cliqz! Pulsed: https://www.mozillapulse.org/entry/343 🎉

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
