### ISSUE TITLE
Web Ninja

### ISSUE THREAD

**Issue by michel-cliqz** [mozilla/global-sprint#109]
**[ Project Contact ]** Michel Tucker
**[ GitHub Repo ]** https://github.com/cliqz-oss/web-ninja
**[ Track ]** Web Literacy, Privacy + Security
**[ Community ]** 
**[ Location ]** Munich, UTC+01:00
### Description
An educational game to illustrate issues of tracking and centralisation on the web.

You are tasked with finding information on the web, but you are being tracked - if your adversaries find what you are doing, you lose. Based on the requests going out of your browser the game will show what information is being leaked, and to whom. Different trackers can be included to ramp up difficultly.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, Michel Tucker! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by chadsansing** [comment]
Awesome, @michel-cliqz - let me know how to help and when the project is ready Pulse.

**Comment by michel-cliqz** [comment]
![web ninja](https://cloud.githubusercontent.com/assets/6093812/26587399/92e182ec-4552-11e7-9dc4-54e74d0dc6fb.png)

**Comment by michel-cliqz** [comment]
This is ready for Mozilla Pulse

**Comment by chadsansing** [comment]
Pulsed! Image is on the way.

https://www.mozillapulse.org/entry/321

**Comment by michel-cliqz** [comment]
Due to lack to resources, we're shelving this project to focus on our other proposed projects #108 and #111

**Comment by chadsansing** [comment]
@michel-cliqz - maybe turn it into a game idea/issue here?

https://github.com/MozillaFoundation/mpa-game-jam-challenge/

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
