### ISSUE TITLE
Liberate Science

### ISSUE THREAD

**Issue by chartgerink** [mozilla/global-sprint#11]
**[ Project Contact ]** @chartgerink
**[ GitHub Repo ]** https://github.com/libscie/liberator
**[ Track ]** Digital Inclusion
**[ Community ]** Mozilla Science - wrangler @stephwright
**[ Location ]** Tilburg, NLD, CET
### Description
Public access to the public domain is not a given --- in order to ensure this, this project aims to identify and liberate scholarly works that have expired copyright and are in fact public domain. The current aim is to develop an easy-to-use website that allows users to contribute to freeing these works.This helps empower people to share their access where it is possible. Liberate once, free forever.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @chartgerink! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @chadsansing. We're here to help you through this process.

**Comment by chadsansing** [comment]
Calling @stephwright - should this be a Science community project?

**Comment by stephwright** [comment]
Sorry... yes :)

**Comment by stephwright** [comment]
Hi @chartgerink ... I'm checking in to see how prep is going for this Global Sprint project.  I'd love to see it succeed.  Just a few steps to get through and I can make this a Featured Project.  You would definitely want to make sure it's got a README and CONTRIBUTING though so folks know how to help you out during the sprint!  It's only 3 weeks away! 🎆

**Comment by chartgerink** [comment]
Hey @stephwright; it's on my to-do for tomorrow! Thanks for pinging me though, I've been tardy on this. I had some of this stuff in a meta-repo and just have to transfer and add :-)

:steam_locomotive:

**Comment by chartgerink** [comment]
Just updating: have everything ready to push to github, just waiting for a response from one person and then I will be ready, also for Mozilla Pulse :smile:

**Comment by stephwright** [comment]
Hi @chartgerink ... did you have an image you wanted me to post with this?

**Comment by chartgerink** [comment]
Yes, I was just awaiting the response to push everything. Here is the image.

![sg2bhu2q](https://cloud.githubusercontent.com/assets/2946344/26056931/a177c0b4-3977-11e7-9029-81022254bc5e.jpg)

So now truly: `This is ready for Mozilla Pulse`

**Comment by stephwright** [comment]
You've been Pulsed!  https://www.mozillapulse.org/entry/283
