### ISSUE TITLE
Women Techmakers Tucson Hackathon 2017

### ISSUE THREAD

**Issue by maggiemelo** [mozilla/global-sprint#110]
**[ Project Contact ]** Maggie Melo
**[ GitHub Repo ]** https://github.com/maggiemelo/womentechmakers-tucson-hackathon-2017
**[ Track ]** Web Literacy, Digital Inclusion
**[ Community ]** Women in Technology - wrangler: @amirad
**[ Location ]** Tucson, Arizona; Mountain time
### Description
This free hackathon provides an opportunity for persons of all levels of technical expertise to collaboratively develop tech-driven projects over the course of two days.  All are encouraged to attend — no computer programming experience required.  
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, Maggie Melo! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [ ] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @amirad. We're here to help you through this process.

**Comment by Its-me-judy** [comment]
This is awesome! I would love to join.

**Comment by amirad** [comment]
Hey @maggiemelo can you share your repo so I can add it to Mozilla Pulse. I'm excited to contribute over the next couple days so please let me know how best to jump into your project with you :)

**Comment by abbycabs** [comment]
Hey @maggiemelo! We need you to complete the first 5 items to participate in the sprint.

I'd love to see this project in the sprint! Can you complete those steps before tomorrow?

**Comment by maggiemelo** [comment]
@amirad and @acabunoc, hi there! Done and done. 👍 Looking forward to it!

**Comment by abbycabs** [comment]
Great, thanks @maggiemelo! Can you add a link to the repo you made here so people can contribute?

**Comment by amirad** [comment]
@acabunoc link to repo is up top! https://github.com/maggiemelo/womentechmakers-tucson-hackathon-2017

@maggiemelo I'm ready to jump in! Where is the link to the wiki mentioned on the repo? I have some resource to contribute and can help build other ones you want for the event. Want to collaborate on skype? you can add amiradhalla (here, gitter or anything else works too)

**Comment by maggiemelo** [comment]
We're helping other folks set up in Tucson! Sorry for the delay. Just be 5 minutes. 😄

**Comment by maggiemelo** [comment]
We're up! @amirad Skype works. Just sent you an invite via Skype. Also, here's the link to the Wiki: https://github.com/maggiemelo/womentechmakers-tucson-hackathon-2017/wiki

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
