### ISSUE TITLE
Privacy bot

### ISSUE THREAD

**Issue by remusao** [mozilla/global-sprint#111]
**[ Project Contact ]** @remusao
**[ GitHub Repo ]** https://github.com/cliqz-oss/privacy-bot
**[ Track ]** Privacy + Security
**[ Community ]** 
**[ Location ]** Munich, UTC+01:00

### Description

Privacy policies are a legal requirement for websites handling users' data. So anyone should be able to access them, read them and understand what it takes (in terms of privacy) to be using a given service. Except no one reads them. User's fault? Probably not. We can list several reasons:

1. A lot of people don't even know what they are.
2. They are "legal documents", and it takes a specific set of skills to comprehend them.
3. They are long and reading them would be time consuming (the median length is ~2500 words).

In short, they don't seem to be designed for people to read and understand. But still, the content of these policies is very important to anyone's privacy, for this is where you should learn what private data you agree to give away.

*Privacy Bot* is a project which aims at addressing the aforementioned issues. If policies are not meant for humans, then maybe we can design a bot to automatically do the heavy lifting for us. The high level goals of the project are to:

1. Discover the privacy policy of any domain.
2. Automatically fetch and store them in a central place (eg: in a github repository, which will give us `diffs` on updates for free).
3. Analyze them to extract a summary of what private data is shared, and with whom.
4. Stay up-to-date by monitoring updates.
5. Make all the policies available in a central repository, in a usable data format that people can build upon (eg: building a browser extension to show the summary on any visited website, creating a twitter bot to communicate facts and updates about policies, etc.).

***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @remusao! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by remusao** [comment]
We would like to use this image for our project (png and svg). I have different sizes, are these ones Ok?
![image](https://cloud.githubusercontent.com/assets/1299873/26555972/121cb2ea-4498-11e7-88ef-d6d0b157124f.png)

![](https://framapic.org/PzYfwR8xPFs0/zv5evK1h9l0K)

**Comment by remusao** [comment]
This is ready for Mozilla Pulse

**Comment by abbycabs** [comment]
Pulsed! https://www.mozillapulse.org/entry/334 🎉

**Comment by omushpapa** [comment]
@remusao loving the image there

**Comment by remusao** [comment]
@acabunoc Thanks a lot for the Pulse!
@giantas Happy you like it! We enjoyed creating it :)

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
