### ISSUE TITLE
Colper Science: A podcast promoting Open Science and its methods

### ISSUE THREAD

**Issue by ilyasst** [mozilla/global-sprint#126]
**[ Project Contact ]** Kambiz Chizari
**[ Link ]** https://github.com/ColperScience
**[ Track ]** Open Innovation
**[ Hub ]** Mozilla Science - wrangler: [@stephwright](https://github.com/stephwright)
**[ Location & Timezone ]** Montreal - Canada (ET)

### Description
We are launching a podcast on open science showing its advantages in research. Most of the episodes will be the interviews with researchers who had published a paper using open science in any form, such as open data or open source programs, and accomplished useful results. The purpose of this podcast is mainly to share stories related to the Open Science methods. We hope to share novel methods and models used by researchers, librarians, developers and others world-wide which could inspire others to follow similar paths, and make Open Science the norm.

We have a website (http://blog.colperscience.com/) and a functional RSS feed for the podcast (http://feeds.feedburner.com/ColperScience). Episode 1 is already online.

We need help for several elements listed in the Issues of repositories, among them are episodes transcriptions, advice on the best setup to record Hangout calls, etc ...
We are also on the lookout for people we could interview! We provide examples of the kind of persons we would like to interview in our repository.
***

## Want to contribute to this Project during the Global Sprint?
Join us at the Global Sprint, June 1-2 ([registration opens soon](https://mozilla.github.io/global-sprint)). Leave a comment in this issue to let the project lead know you're interested in contributing during #mozsprint 2017!

***

## Note to the Project Lead
Congrats, <%= facilitator %>! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete the following checklist:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project
  * [Repository](https://github.com/ColperScience/podcasting)
- [x] Provide a link to your README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
  * [Readme](https://github.com/ColperScience/podcasting/blob/master/README.md)
- [x] Turn on your Issue Tracker and create issues that describe each task that you need help with, and how a contributor can get started on that task.  
  * Done
- [x] Confirm in a comment that at least one person will be available to review and answer questions on this project from 9-5 in their timezone on both June 1 & 2. :clock1:
  * Done

#### Requirements Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on Network Pulse, complete the following documentation. In past Sprints, well-documented featured projects have had 5 times as many contributions as projects that only meet the basic requirements for project registration.

If you complete all steps, your project will be featured on [Network Pulse](http://mozillapulse.org/) during [#mozsprint 2017](https://mozilla.github.io/global-sprint). As you complete each exercise, check off the box and comment with a link to your completed resource. D
Details about each item and more information about how to create them are [here on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-requirements/). 
This [template repository WE NEED TO UPDATE THIS- WE ARE NOT DOING VISION STATEMENTS AND ASKING FOR SOME OTHER STUFF](https://github.com/acabunoc/mozsprint-repo-template) is here to help you if you get stuck!
* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)

Once all of the above is complete,
- [x] post to [Network Pulse](http://mozillapulse.org/). We'll review this issue to approve your post :balloon: :cake:

**Comment by ilyasst** [comment]
![colper_solid](https://cloud.githubusercontent.com/assets/443955/26594829/4325b856-4537-11e7-867c-6d6e925ab104.png)

**Comment by ilyasst** [comment]
@KambizChizari will be available from 9-5 EST June 1 and 2 t answer questions.

**Comment by ilyasst** [comment]
This is ready for Mozilla Pulse

**Comment by abbycabs** [comment]
Pulsed! https://www.mozillapulse.org/entry/380

sorry for the delay

**Comment by joseph-njogu** [comment]
i am interested on contributing to it

**Comment by ilyasst** [comment]
Hello @joseph-njogu !

We'd be super glad if you could contribute :)
We have a public Telegram group to exchange and discuss: https://t.me/joinchat/BPCby0MS-hl-y6WCZ31HSA
If you are not really into Telegram, you can also simply contact us by e-mail, we can then discuss what you're interested in, and how we could all promote Open Science together :)

We hope to meet you really soon on the Telegram group :+1: 

Ilyass

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
