### ISSUE TITLE
NYC Open Data for All Workshop Curriculum for Parks TreesCount! Data

### ISSUE THREAD

**Issue by NYCOpenData4All** [mozilla/global-sprint#133]
**[ Project Contact ]** Adrienne Schmoeker
**[ GitHub Repo ]** https://docs.google.com/document/d/1PH1A6FwfQw3OkB2TQooalpg3XJUDCK3OI9T2T4XJEW4/edit?usp=sharing
**[ Track ]** Web Literacy, Open Innovation, Digital Inclusion
**[ Community ]** Hive Networks (Austin, Chattanooga, Chicago, Kansas City, NYC, Toronto) - wrangler: @omnignorant
**[ Location ]** There will be virtual availability on Thursday June 1st and request for comments on the project during all 48 hours of the Sprint! Adrienne Schmoeker will be available from 10:30am - 1pm EST on Thursday June 1st
### Description
In 2015 NYC declared "Open Data for All" - in partnership with NYC Parks, the Mayor's Office of Data Analytics is developing Open Data for All Workshops around specific datasets to teach New Yorkers how to use NYC Open Data. The beta curriculum for these workshops, with a focus on NYC Parks street tree data, is what we are looking for feedback on as a part of the Mozilla Global Sprint. This is our first time participating in the Global Sprint - we're looking forward to your feedback and ideas!
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, Adrienne Schmoeker! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [ ] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [ ] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [ ] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [ ] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @omnignorant. We're here to help you through this process.

**Comment by abbycabs** [comment]
Hey @NYCOpenData4All! We need you to complete the first 5 items to participate in the sprint.

I'd love to see this project in the sprint! Can you complete those steps before tomorrow?

**Comment by abbycabs** [comment]
Closing this in the meantime -- @NYCOpenData4All let me know if you get a chance to work on the first few points and we can open this again!

**Comment by NYCOpenData4All** [comment]
Thanks  Abigail but I wasn't able to get this together in time on GitHub (I'm a new user) - hoping to find another Mozilla event to collaborate on for this project in the future!

________________________________

**Comment by abbycabs** [comment]
@NYCOpenData4All we have a guide to help you if you have some time to go through the steps for your project :)
https://mozilla.github.io/global-sprint/project-lead/templates/
