### ISSUE TITLE
990 Scraper

### ISSUE THREAD

**Issue by mayawagon** [mozilla/global-sprint#137]
**[ Project Contact ]** @mayawagon
**[ GitHub Repo ]** https://github.com/opentechinstitute/990-scraper
**[ Track ]** Decentralization, Open Innovation, Internet Policy & Advocacy
**[ Community ]** 
**[ Location ]** Worcester, MA, UTC-05:00
### Description
The 990 Scraper is a script for gathering information on nonprofits across the United States based on 990 tax data. This can include total revenues, number of employees, number of volunteers, location, the year it was formed, and more. The Open Technology Institute is using this tool to visualize data on nonprofits that build, use, or engage with technology for social justice, but presumably the tool could be used for any list of nonprofits you want. The script uses the ProPublica Nonprofit Explorer API, and places whatever pieces of information you want into a Google spreadsheet. 
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @mayawagon! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by mayawagon** [comment]
![form-990-img](https://cloud.githubusercontent.com/assets/598198/26683523/0f23b0f4-46b2-11e7-95d7-faa9e48d6e31.jpg)

**Comment by drewrwilson** [comment]
👍 🐙 veryyy cool!

**Comment by mayawagon** [comment]
This is ready for Mozilla Pulse.

**Comment by omushpapa** [comment]
Interesting

**Comment by abbycabs** [comment]
Great project @mayawagon! Have you looked at [Open Funders Canada](https://www.mozillapulse.org/entry/245)?

Pulsed:
https://www.mozillapulse.org/entry/341 🎉

**Comment by mayawagon** [comment]
@acabunoc no, but that looks super relevant! @lesliePhD maybe we can collaborate in some way?

**Comment by lesliePhD** [comment]
@mayawagon and @acabunoc Thanks for the connections - looks like there is alot of overlap between the work that I do at [Powered by Data](http://poweredbydata.org/) as well as on this project.  Here in Canada, our equivalent is the T3010 and it has been open data via an API since I believe 2009.  Our sister company, Ajah uses it to make a commercial funding prospect tool called Fundtracker.  

Our project Landscape or Open Funders Canada scrapes data with project descriptions from websites to give extra searchability on fields of interest.  

anyways, I would love to chat about what you are doing in the US - as we also have a similar pilot in the US.  

feel free to get in touch.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by drewrwilson** [comment]
That was fun last year! I'll gladly do it again this year!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
