### ISSUE TITLE
Open Derby

### ISSUE THREAD

**Issue by jpwrobinson** [mozilla/global-sprint#14]
**[ Project Contact ]** @jpwrobinson
**[ GitHub Repo ]** https://github.com/jpwrobinson/OpenDerby
**[ Track ]** Web Literacy, Open Innovation
**[ Community ]** Mozilla Science - wrangler: @stephwright 
**[ Location ]** Victoria, BC Canada, PST
### Description
Promoting reproducibility and openness in research by teaching open science tools on-the-fly in a collaborative research project.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @jpwrobinson! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by chadsansing** [comment]
@stephwright - open science tools. Looks like a project for the Science community.

**Comment by stephwright** [comment]
Hey @jpwrobinson ... checking in on prep.  The Sprint is 3 weeks away and you're so close to this being a featured project!  Looks like we just need to see a LICENSE.md and an image and I can get this up for you.

**Comment by jpwrobinson** [comment]
Great! Image attached and license in repo.

![open-derby-logo](https://cloud.githubusercontent.com/assets/5231402/26074665/7dc1759e-3967-11e7-802f-3425c1a9101d.png)

**Comment by jpwrobinson** [comment]
This is ready for Mozilla Pulse

**Comment by stephwright** [comment]
You've been Pulsed! https://www.mozillapulse.org/entry/284

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
