### ISSUE TITLE
Neutrino

### ISSUE THREAD

**Issue by eliperelman** [mozilla/global-sprint#141]
**[ Project Contact ]** @eliperelman
**[ GitHub Repo ]** https://github.com/mozilla-neutrino/neutrino-dev
**[ Track ]** Web Literacy, 
**[ Location ]** Persia, IA CST
**[ Coach ]** @Wiroll & @psubhashish

### Description
Create and build modern JavaScript applications with zero initial configuration.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by eliperelman** [comment]
I forgot to add the `mozsprint` and `2018` tags to my pulse submission, could someone help?

**Comment by abbycabs** [comment]
I added the two tags for you!

Thanks for your speedy work @eliperelman 🐇 👟

**Comment by eliperelman** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hi @eliperelman,

@Wiroll & @psubhashish will be your Project Coaches for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by abbycabs** [comment]
Hey @eliperelman! Your project is on pulse: https://www.mozillapulse.org/entry/600  🎉 
And on the list of featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

@Wiroll & @psubhashish - let me know if you have any feedback on this project 😃

**Comment by psubhashish** [comment]
Everything looks good to me, Abby. @eliperelman amazing work behind this project. Wish you all the best!
