### ISSUE TITLE
openSNP

### ISSUE THREAD

**Issue by gedankenstuecke** [mozilla/global-sprint#142]
**[ Project Contact ]** @gedankenstuecke
**[ GitHub Repo ]** https://github.com/opensnp/snpr
**[ Track ]** Openness, 
**[ Location ]** UTC-7 (California, USA), UTC+2 (Berlin, Germany), UTC+8 (Perth, Australia)
**[ Coach ]** @quirksahern & @fimakeswork 

### Description
openSNP is a web project for customers of genotyping data such as 23andMe to share their genetic data with the public. It's named after a type of genetic variants - Single Nucleotide Polymorphisms or short SNP (pronounced Snip). 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by gedankenstuecke** [comment]
`Do we have to re-submit for Mozilla Pulse to become a featured project? 😄 `

Nevermind, I just did a submission again to also update things 👍

**Comment by gedankenstuecke** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hi @gedankenstuecke ,

@quirksahern & @fimakeswork will be your Project Coaches for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by quirksahern** [comment]
Hi @gedankenstuecke 

Have had a look through, all looks good, but what is snp? It's not explained anywhere?

**Comment by gedankenstuecke** [comment]
Whops, my bad. I added a short explanation to the description here. :-)

**Comment by quirksahern** [comment]
Where?

**Comment by quirksahern** [comment]
Sorry, just seen it. Happy to approve for Mozilla Pulse - good luck with the Global Sprint!
@acabunoc I cannot see this in Mozilla Pulse, can it please be approved

**Comment by gedankenstuecke** [comment]
thanks! 👍

**Comment by quirksahern** [comment]
There are two approved openSNP issues currently on Mozilla Pulse. @acabunoc - I am going to close this issue for now.

**Comment by abbycabs** [comment]
Hey @quirksahern! re-opening since this is the list of *all* global sprint projects (not just featured) :)

The older entries on pulse are from previous sprints and are tagged differently

**Comment by quirksahern** [comment]
Ok, cool. Tad confusing.

**Comment by quirksahern** [comment]
Hi @gedankenstuecke, did you complete the Mozilla Pulse form? I havent seen the project appear for moderation

**Comment by gedankenstuecke** [comment]
Oh, I was pretty sure that I had submitted openSNP for the Mozilla Pulse. But if it's missing right now I'd be happy to make another submission if that helps?

**Comment by abbycabs** [comment]
Sorry both, it's already featured here!
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

The page was looking empty so I think someone must have pre-approved it :)

**Comment by quirksahern** [comment]
It might just be me being confused - Is 'openSNP - Sharing Personal Genomes' the correct project? If so, already approved for 2018. There is also an openSNP project from 2017.

**Comment by gedankenstuecke** [comment]
Phew, and I thought I was growing forgetful! 👴 Thanks for checking @acabunoc! 💓

**Comment by quirksahern** [comment]
Thanks for the clarification @acabunoc thought I was going a little mad lol
