### ISSUE TITLE
Open Humans

### ISSUE THREAD

**Issue by gedankenstuecke** [mozilla/global-sprint#143]
**[ Project Contact ]** @gedankenstuecke
**[ GitHub Repo ]** https://github.com/OpenHumans/open-humans
**[ Track ]** Openness, 
**[ Location ]** Berkeley, CA, USA | San Diego, CA, USA | Boston, MA, USA | United Kingdom
**[ Coach ]** @tpoisot 

### Description
Open Humans is a platform that allows you to upload, connect, and privately store your personal data – such as genetic, activity, or social media data. Once you've added these data, you can choose how to use and donate it: Share some publicly or join participant-lead and academic research projects.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi @gedankenstuecke,

@tpoisot will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by HadrienG** [comment]
Hi @gedankenstuecke,

I will be participating remotely to #mozsprint 2018 (my very first 🎉) to I'd love to contribute to Open Humans!

[Open Humans](https://www.openhumans.org/ ) looks like an amazing idea and I'm familiar with git, python and sql, and in the process of learning js so I think your project is a good fit. Since I'm participating remotely I thought I'd quickly announce myself here. Is there anything extra important I should know before next week?

Looking forward to work with the openhumans team!

Best,
Hadrien

**Comment by gedankenstuecke** [comment]
Hey @HadrienG, that's awesome. We still have to put up some issues that we want to work on during the Sprint. And it's all a bit confusing as we have too many repos that can be worked on, so I'll probably end up doing a micro-site that lists things 😉 

The whole Open Humans itself is fully remote, so that should work out fine. Given our remote nature you can always find us on Slack. You can join our Slack at http://slackin.openhumans.org/ and there's a #globalsprint channel that we can use for coordination and just hanging out. Does that sound good? 😄

**Comment by HadrienG** [comment]
sounds perfect!

**Comment by gedankenstuecke** [comment]
As promised, here's our microsite that lists all the different places in which people can contribute along with ways to contribute there: http://openhumansfoundation.org/globalsprint-2018/ 

We have non-code issues, issues that are largely data analysis in Python/R/Julia and even some iOS programming issues to choose from

**Comment by tpoisot** [comment]
Can you make a list of issues tagged `mozsprint` so I can feature this on pulse?

**Comment by gedankenstuecke** [comment]
A list of the issues or are the links to the repo's ok too? 

- https://github.com/OpenHumans/ohjh-example-notebooks/issues?q=is%3Aissue+is%3Aopen+label%3Amozsprint 
- https://github.com/gedankenstuecke/twitter-analyser/issues?q=is%3Aissue+is%3Aopen+label%3Amozsprint
- https://github.com/gedankenstuecke/ftdna-upload/issues?q=is%3Aissue+is%3Aopen+label%3Amozsprint

**Comment by tpoisot** [comment]
Links to the repos are OK as long as they're easy to find -- can you put a list of these links somewhere prominent on the microsite?

**Comment by gedankenstuecke** [comment]
Sure, just put the links in on top of the `index`!
