### ISSUE TITLE
Web + Messaging

### ISSUE THREAD

**Issue by autonome** [mozilla/global-sprint#144]
**[ Project Contact ]** @autonome
**[ GitHub Repo ]** https://github.com/autonome/web-and-messaging
**[ Track ]** Openness, 
**[ Location ]** Portland, OR in Pacific time zone
**[ Coach ]** @gilbertslade

### Description
Let's explore how the web and messaging apps can play together.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by autonome** [comment]
This is ready to be featured on Mozilla Pulse...

... except I forgot to add the mozsprint and 2018 tags to my Pulse submission, and I can't figure out how to find it and edit it there! Can you help?

**Comment by abbycabs** [comment]
Hi @autonome,

@gilbertslade will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by autonome** [comment]
Great! Let me know if I can provide any more information.

**Comment by gilbertslade** [comment]
Hey Dietrich, your repo looks good!  There's some stuff that looks like templating text that you forgot to delete in your contributing file, but otherwise I think it's ready!

**Comment by autonome** [comment]
Hi @gilbertslade! Sorry, I'd moved the relevant information on contributing into the main README.md. I've removed the generic Contributing.md file that came along with the template repo.

**Comment by zee-moz** [comment]
this project is now on Pulse! thanks for your patience. Happy Sprinting 😸 https://www.mozillapulse.org/entry/604

**Comment by autonome** [comment]
Yay, thanks Zannah!
