### ISSUE TITLE
Project JavaScript Translated Edition ( Jste )

### ISSUE THREAD

**Issue by GeeekyBoy** [mozilla/global-sprint#145]
**[ Project Contact ]** @GeeekyBoy
**[ GitHub Repo ]** https://github.com/project-jste/framework
**[ Track ]** Web Literacy, Openness, Privacy + Security, Digital Inclusion, Decentralization, 
**[ Location ]** Alexandria, Egypt
**[ Coach ]** @cbaba20

### Description
Project Jste aims to give the opportunity for everyone to code and develop his/her own website or web application by writing a code written in his/her local natural language.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by GeeekyBoy** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hi @GeeekyBoy,

@cbaba20 will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by GeeekyBoy** [comment]
Hello @cbaba20,
Have you reviewed my entry on Mozilla Pulse ?

**Comment by cbaba20** [comment]
Hello  @GeeekyBoy Ahmed,
Yes I have reviewed your entry and found it interesting and wanted to approve your entry for Pulse after few changes that you can do on your site : 
1) remove **jste://** from calculator app: [jste://http://jste-demos.herokuapp.com/en-us/calculator.html?page=calculator] 
2) I am not able to see the whole calculator, Can you recheck it on your browser? 
see the snapshot 
![image](https://user-images.githubusercontent.com/8758288/38945702-e678c46e-4354-11e8-907b-89f2ad35f509.png)

BR,
Chandan

**Comment by GeeekyBoy** [comment]
Hello @cbaba20,
Thanks for your response
It seems that you have understood the purpose of the calculator in a wrong way
Briefly, this calculator is a demo for a feature like instant apps which shows how Jste can be used to build web apps that can interact with native mobile device functions like controlling the flashlight
To try this demo, you have to install Jste Manager for Android first from: https://github.com/project-jste/manager-phone/raw/master/build/android-debug.apk then open it
After opening it it will show a splash screen which will disappear after a while
After the splash screen disappearance, try to open Jste website from Google Chrome on Android and click on the calculator link which will be opened automatically through Jste Manager
The purpose of "jste://" is to make the system open this link through Jste Manager and not through the browser
![screenshot_jste_manager_20180418-211127](https://user-images.githubusercontent.com/13814178/38953363-d10c77c0-434e-11e8-96f2-e32c88dca6a9.png)
![screenshot_jste_manager_20180418-211136](https://user-images.githubusercontent.com/13814178/38953364-d1c6c0f8-434e-11e8-8e4f-6c865ead2bff.png)

If you don't want to do all of the previous steps, you can simply open the website on Chrome PC in the mobile device mode as shown in the screenshot below
![screenshot from 2018-04-18 21-06-32](https://user-images.githubusercontent.com/13814178/38953374-da4af0c8-434e-11e8-9181-9cee94405b24.png)

**Comment by cbaba20** [comment]
Yeah... I got the steps on first read only but much clarification happened here. However I have used only firefox browser to check whether it works or not from site and there things messed up.
I will check today in chrome and update you.
Meanwhile have you filed the pulse form ? Once its good to go, it will be seen here: 
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

**Comment by GeeekyBoy** [comment]
I have filled the pulse form since I have registered as a project manager in Global Sprint 2018

**Comment by cbaba20** [comment]
Okay... Looks good to me so flagging it approved ! 

Best wishes for #mozsprint .
Don't forget to document it with awesome images. 👌👍

**Comment by GeeekyBoy** [comment]
Sure, I'll do this in addition to some video tutorials
Should I see my project at shown at https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/ now ?

**Comment by cbaba20** [comment]
Yeah, Just a bit change which I think need to remove the dullness of sentence, it is showing up in thumbnail that you may added during filling up pulse form.  

> Project Jste aims to give the opportunity for everyone to code and develop his/her own website or web application by writing a code written in his/her local natural language.
I don't think below sentence is saying different except the part of sentence marked in bold.
> Because Project Jste will give the opportunity for everyone to code and develop his/her own website or web application in his/her local natural plain language **instead of the currently used syntax which may be seemed complex for large portion of people.**

**Comment by cbaba20** [comment]
One more addition for better understanding for probable contributors : put few more appropriate labels in issues :   
for example : issue 2 can have **"help wanted:localization"** to tell contributors what exactly we are looking for without even reading the issue description.
Same goes to other issues.

**Comment by GeeekyBoy** [comment]
I mean in the bold part that Jste syntax is much simpler than the syntax that is currently used to develop web sites and apps like that of the pure JavaScript.
You can remove it if you see that it makes the project description unclear

**Comment by GeeekyBoy** [comment]
For your second comment, I will do this right now

**Comment by GeeekyBoy** [comment]
Does this look good ?
![screenshot from 2018-04-19 20-48-49](https://user-images.githubusercontent.com/13814178/39011918-26a16c3a-4413-11e8-978b-d096a94e0a53.png)

**Comment by cbaba20** [comment]
This looks fantastic :) Thanks. And regarding the removal of description I don't think I have the editing rights. I will ask someone from project coordination team.

**Comment by GeeekyBoy** [comment]
You are welcome :)

**Comment by cbaba20** [comment]
Hey @GeeekyBoy,
Does this project have logo ?

**Comment by GeeekyBoy** [comment]
Hello @cbaba20,
Yup, my project has a logo
You can see it below
![29762921](https://user-images.githubusercontent.com/13814178/39087580-4670236c-45a3-11e8-9bc5-7c56fbd6d5b7.png)

**Comment by abbycabs** [comment]
Great to see this featured! Nice work everyone 😃 @cbaba20 & @GeeekyBoy 

Featured: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
Pulse: https://www.mozillapulse.org/entry/602

**Comment by GeeekyBoy** [comment]
@acabunoc Hello,
Why the mozilla global sprint team has removed my project from the featured projects at: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

Thanks

**Comment by GeeekyBoy** [comment]
@acabunoc Please reply as fast as you could because I wanna know what is going wrong with my project
