### ISSUE TITLE
lab.js

### ISSUE THREAD

**Issue by FelixHenninger** [mozilla/global-sprint#146]
**[ Project Contact ]** @felixhenninger
**[ GitHub Repo ]** https://github.com/felixhenninger/lab.js
**[ Track ]** Web Literacy, Openness
**[ Location ]** Mannheim, Germany (CET)

### Description
**Our project makes open behavioral research easy! Together, we're building a graphical interface for conducting and sharing browser-based experiments in the cognitive and social sciences.** 
***

## Want to contribute to this project during #mozsprint?
Thanks for considering our project! We would love to have you around on May 10th and/or 11th. Please leave a comment below if you're interested in contributing, we'll get in touch!

**Comment by FelixHenninger** [comment]
This is ready to be featured on Mozilla Pulse (I hope), I would really appreciate the shout-out! Thanks a lot for your continued support 💙

**Comment by abbycabs** [comment]
You're on pulse: https://www.mozillapulse.org/entry/705 🎉

**Comment by FelixHenninger** [comment]
Whoop whoop, thanks a lot! Now I just need to organize the local site, get that read-write-participate interview done, and the sprint can come 🙂.

**Comment by chronicIntrovert** [comment]
Hi @FelixHenninger, I'm interested in joining this project for Global Sprint, how can I help?

**Comment by FelixHenninger** [comment]
**Hi @imthinhvu, thanks so much for reaching out** — I really appreciate your help, and would love to work with you!

There are a number of [issues for mozsprint](https://github.com/FelixHenninger/lab.js/labels/mozsprint) that you could pick from to get started, for example it would be awesome to start building an [interface walkthrough](https://github.com/FelixHenninger/lab.js/issues/13) for new users. There's lots more different things to do though, depending on what you find interesting — I'm all ears for ideas, and I'd be happy to help you find something that suits you and answer questions — you'll find me in the [project slack](https://slackin-nmbrcrnchrs.herokuapp.com/), the [global sprint chat](https://gitter.im/mozilla/global-sprint), or here (might take a little time to respond today, but I'm here all of the next days).

In case you want to get started right away, you'll find info on how to [build the project](https://labjs.readthedocs.io/en/latest/meta/contribute/build.html) and a [code overview](https://labjs.readthedocs.io/en/latest/meta/contribute/navigate.html#builder) in the docs, but again, I'm super-happy to help you get started.

Looking forward to sprinting with you — thanks again for stopping by! -Felix
