### ISSUE TITLE
Code Of Conduct Builder

### ISSUE THREAD

**Issue by alexmorley** [mozilla/global-sprint#147]
**[ Project Contact ]** @alexmorley
**[ GitHub Repo ]** https://github.com/alexmorley/CodeOfConduct.Builder
**[ Track ]** Digital Inclusion, 
**[ Location ]** UK GMT (Oxford/London)
**[ Coach ]** @meghanlazier

### Description
An easy way to build the perfect Code of Conduct for your event/community/organisation
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi @alexmorley,

@meghanlazier will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by meghanlazier** [comment]
Hi @alexmorley - You've made a ton of progress to get ready for the Sprint! Your work would make an excellent story for Mozilla Pulse. Fill out the form and add the required tags if you'd like to submit.

**Comment by alexmorley** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by alexmorley** [comment]
But I forgot to add the mozsprint and 2018 tags :worried: ...

Shall I resubmit or can we edit it somehow??

**Comment by abbycabs** [comment]
Hey @alexmorley, I added the tags for you!

@meghanlazier, you should be ready to moderate this project in pulse :)

**Comment by alexmorley** [comment]
Thanks @acabunoc !

**Comment by meghanlazier** [comment]
@alexmorley Your project is now live on Pulse! https://www.mozillapulse.org/entry/674

**Comment by intersectto** [comment]
This looks great! I'm interested in contributing to this project!

**Comment by lequanne** [comment]
I'm interested in contributing to this project!
