### ISSUE TITLE
Activismo lenguas: a online resource exchange for language digital activism

### ISSUE THREAD

**Issue by GuteMonik** [mozilla/global-sprint#150]
**[ Project Contact ]** @GuteMonik
**[ GitHub Repo ]** https://github.com/GuteMonik/Activismo_lenguas_EN
**[ Track ]** Openness, Digital Inclusion, 
**[ Location ]** Bogota, Colombia. -5UTC

### Description
The project seeks to create a portal for peer learning and exchange for communities participating in an open and linguistically diverse web. Built upon the shared experiences of indigenous language digital activists in Latin America, the portal will document existing initiatives of digital activism in native languages, resources to start a project what tools to use, and what strategies to follow to make your project of language digital activism sustainable.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by GuteMonik** [comment]
We're done! Let's continue working for an open and better Web!

**Comment by abbycabs** [comment]
Hi @GuteMonik! Can you drop a link to your project repository for review here? Thanks!

**Comment by GuteMonik** [comment]
Hi @acabunoc!
The link is: https://github.com/GuteMonik/Activismo_lenguas_EN
Thanks! :)

**Comment by abbycabs** [comment]
Thanks @GuteMonik!

A few things to address before featuring your project :) I left them in your repo in these issues:
* https://github.com/GuteMonik/Activismo_lenguas_EN/issues/4
* https://github.com/GuteMonik/Activismo_lenguas_EN/issues/5
* https://github.com/GuteMonik/Activismo_lenguas_EN/pull/3

**Comment by dannyrayman** [comment]
Hi @GuteMonik, we saw your project and we are very interested in talk with you. 
Kind regards from @beyondactivismo 😃

**Comment by GuteMonik** [comment]
@acabunoc Thanks! Made the modifications and complements.
@dannyrayman A pleasure, we can talk about it, please give me some contact information.
M.

**Comment by Beyondactivismo** [comment]
@GuteMonik you can write to us to contact@beyondactivismo.org 
If you want we can also try to contact you to your email.

Bests, 
Danny

**Comment by abbycabs** [comment]
Hey @GuteMonik!

Still a few open things before I can feature your work
* https://github.com/GuteMonik/Activismo_lenguas_EN/pull/3
* https://github.com/GuteMonik/Activismo_lenguas_EN/issues/5
* README needs an email linked here: https://github.com/GuteMonik/Activismo_lenguas_EN/blob/master/README.md#participation-guidelines

**Comment by abbycabs** [comment]
Hey @GuteMonik 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by GuteMonik** [comment]
Hi @acabunoc 
I tried to upload the information and description of the project to Pulse and it has not allowed me to do so. What I can do? Thanks for your attention and collaboration.
M.

**Comment by abbycabs** [comment]
You have to resubmit to update the description! I also can't approve your pulse since these issues are still open:
* https://github.com/GuteMonik/Activismo_lenguas_EN/pull/3
* https://github.com/GuteMonik/Activismo_lenguas_EN/issues/5
* README needs an email linked here: https://github.com/GuteMonik/Activismo_lenguas_EN/blob/master/README.md#participation-guidelines

**Comment by GuteMonik** [comment]
Hey  @acabunoc 
Issue solved! M.
