### ISSUE TITLE
Privacy Brigade

### ISSUE THREAD

**Issue by vyaspranjal33** [mozilla/global-sprint#151]
**[ Project Contact ]** @vyaspranjal33
**[ GitHub Repo ]** https://github.com/vyaspranjal33/privacy-brigade
**[ Track ]** Privacy + Security, 
**[ Location ]** Location : India State: Gujarat Timezone: IST
**[ Coach ]** @princiya 

### Description
Privacy Brigade is Project that aims to bring Awareness about Digital Privacy/Security among Individuals ,Corporate and Institutions/schools
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by vyaspranjal33** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hello @vyaspranjal33 - you new project coach is @princiya! Princiya will review this issue and approve you entry on Mozilla Pulse if everything looks good 🎉

**Comment by princiya** [comment]
Hi @vyaspranjal33 Thank you for your interest in the Global Sprint :) I really appreciate your effort in privacy advocacy 🎊 

There are few things we need to work on.

1 ) From your Readme file:

> Privacy Brigade is a campaign to try and educate people of how security online works and what steps can be taken to make their activity more secure and safe, to protect their data and identity. [stay safe](Learn & teach basic security things)

I think you intended to put a link here for `[stay safe]`?

> Facilitate and educate individuals to participate in developing addons, web-extentions and webapps to promote the conext of online privacy. The campaign is driven through the design of posters and flyers and presentations, where we get feedback from people about how their online experience has changed after participating in [Privacy Brigade].

- What exactly is the idea you wish to achieve during the sprint?
- From the above lines, there are two things I notice
   - Develop web extensions
   - Poster / flyer design
- We need to polish the above lines a bit to be more clear and precise

2) Please create atleast 3 issues in your project as per the above checklist

Please feel free to brainstorm here for more ideas.

**Comment by vyaspranjal33** [comment]
Hi @princiya  I don't have any Intention to Put link for staysafe

these are some idea i need to achieve during sprint
- hosting a privacy talk 
- evangelise about Web-extensions that can be used to ensure privacy
- developing/porting web extensions in context of privacy
-  Poster / flyer design

**Comment by princiya** [comment]
@vyaspranjal33 

> I don't have any Intention to Put link for staysafe

The format `[stay safe](Learn & teach basic security things)` meant you wanted to add hyperlink in markdown format. So I was wondering :) Then you could remove the additional braces? No big deal though, and we could leave it that way too.

> Regarding ideas:

Can you go about writing in brief how you plan to achieve them? This would also help you to create two additional issues in your project repo. We need minimum 3 issues :)

Points to consider:
- name a place where you want to host the privacy talk. online webinar or offline at a physical location?
- about web extensions. do you plan to write blog posts or address them in your above talk?
- who will design posters?

I think once we address the above points we are good to get started.

**Comment by vyaspranjal33** [comment]
@princiya  I've addressed Points

**Comment by princiya** [comment]
@vyaspranjal33 Thank you for the updates.

@acabunoc This is good to go. Could you please approve this on pulse?

**Comment by princiya** [comment]
@vyaspranjal33 On an additional note, if you have any templates for posters, you could add the links in the corresponding issue. This would be of a great help for newbies to get started on this initiative. The same applies to any talk formats, or blog posts.

Also for the website issue, I understand you have the label `help wanted`. But if you have any initial layout, template, drawings or any website similar to what you would want to see, please list it there. Also, try to write there what are the overall steps involved:

- Domain name (do you have one already, if yes, then mention it)
- Hosting (do you have one? if not, do you need inputs from people what are the best options?)
- Page contents / sections etc.

When potential contributors come to your repo, if the issue itself is well defined, then they could help with their expertise:
 - translations
 - specific page content
 - improving your slide deck
 - suggesting pointers for posters
 - etc. etc.

**Comment by princiya** [comment]
Also, there is another similar project on privacy for this sprint - https://github.com/mozilla/global-sprint/issues/194. You could take a look and let's talk about possible collaborations.

**Comment by princiya** [comment]
https://www.mozillapulse.org/entry/616 🎊  🎈

**Comment by vyaspranjal33** [comment]
@princiya  I've completed project with one issue closing remaining issues with Label "in progress" @acabunoc  Thank you for selecting my project , @princiya   Thanks for being mentor
