### ISSUE TITLE
An R software toolkit to simplify an open, collaborative scientific workflow

### ISSUE THREAD

**Issue by lwjohnst86** [mozilla/global-sprint#152]
**[ Project Contact ]** @lwjohnst86
**[ GitHub Repo ]** https://github.com/lwjohnst86/prodigenr
**[ Track ]** Openness, 
**[ Location ]** Aarhus, Denmark, UTC+1:00

### Description
Many fields of science are far behind adopting open scientific practices (e.g. share code). I believe these will be a requirement for publication in the future. However, one of the biggest challenges for many researchers/scientists is that it's not (at this point) easy to do these practices. This toolkit will simplify and automate many of these tasks. I have already started work on this software project with prodigenr.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by lwjohnst86** [comment]
My GitHub repo: https://github.com/lwjohnst86/prodigenr

**Comment by lwjohnst86** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hey @lwjohnst86!

Great repo! One thing I'd change is renaming CONDUCT.md -> CODE_OF_CONDUCT.md ([see github's documentation](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/))

I'm also reviewing your Pulse submission. Do you have an image we can use for the entry? We find that images are very important for bringing attention to your entry.

**Comment by lwjohnst86** [comment]
@acabunoc I don't have an image, but that is a great idea to have one! I should create one. Is there a deadline for when the image needs to be given by?

**Comment by abbycabs** [comment]
We’ll hold off featuring your project till there’s an image. No deadline, but getting featured earlier is better than later!

**Comment by KristijanArmeni** [comment]
@lwjohnst86 Just explored the repo, manifesto and tested briefly the package. Must say this looks like a very cool project. I can see mysef contribute either in brainstorming, writing or code. I come from neuroscience (mostly working on electrophysiology in MATLAB, have limited experience with developing R code; needs some brushing up), but developing tools for practicing open science speaks to me a lot generally.

Will explore a bit more, fork soon and then see you on the issues?

**Comment by lwjohnst86** [comment]
Hi @KristijanArmeni, thanks! I am 100% looking for contributors!! So you are definitely welcome in what ever form you can provide! I'm still fixing up the contributing guidelines, readme, and manifesto to make it clearer, so keep your eye out! :)

**Comment by lwjohnst86** [comment]
Hi @acabunoc, I put together an image! I hope it's good...
![rostools-pulse-image](https://user-images.githubusercontent.com/6662983/39044288-089ab4bc-4490-11e8-996f-d95fe87a448f.png)

**Comment by abbycabs** [comment]
Thanks! featured 🎉 https://www.mozillapulse.org/entry/643
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

**Comment by KristijanArmeni** [comment]
@lwjohnst86 I'm slowly tuning in for sprinting (after some logistic overhead). Is there a specific communication channel you use for online messaging these two days for this project? I'm logged in mozilla gitter channel. If there is, just let me know. I'll do my best to contribute sth over these two days :)

**Comment by lwjohnst86** [comment]
@KristijanArmeni Awesome! Yes, here is the [Gitter chat](https://gitter.im/prodigenr/Lobby)!
