### ISSUE TITLE
Endangered Data Week

### ISSUE THREAD

**Issue by hepplerj** [mozilla/global-sprint#153]
**[ Project Contact ]** @hepplerj
**[ GitHub Repo ]** https://github.com/endangereddataweek/resources
**[ Track ]** Web Literacy, Openness, Decentralization, 
**[ Location ]** Omaha, NE (Central)

### Description
Endangered Data Week is a collaborative effort coordinated across campuses, nonprofits, libraries, citizen science initiatives, and cultural heritage institutions, to shed light on public datasets that are in danger of being deleted, repressed, mishandled, or lost. Along with Mozilla Open Leaders Round 5, we are developing a simple, detailed, extensible toolkit for conducting action to preserve access to public data against political, social, and technical threats.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by hepplerj** [comment]
Repository and (drafty) README: https://github.com/endangereddataweek/resources

**Comment by daniellecrobinson** [comment]
👍 🎉

**Comment by hepplerj** [comment]
This is ready to be featured on Mozilla Pulse.

**Comment by daniellecrobinson** [comment]
:tada:

**Comment by abbycabs** [comment]
Pulse: https://www.mozillapulse.org/entry/692 🎉 
Featured here: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
