### ISSUE TITLE
bioSyntax

### ISSUE THREAD

**Issue by alyeffy** [mozilla/global-sprint#154]
**[ Project Contact ]** @alyeffy
**[ GitHub Repo ]** https://github.com/bioSyntax/bioSyntax
**[ Track ]** Openness, 
**[ Location ]** Vancouver, BC: GMT/UTC -08:00
**[ Coach ]** @SamanthaHindle & @aariops

### Description
Syntax Highlighting for Computational Biology
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi @alyeffy,

@SamanthaHindle & @aariops will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by alyeffy** [comment]
Hi @SamanthaHindle & @aariops!
This is ready to be featured on Mozilla Pulse.

**Comment by abbycabs** [comment]
Hi @SamanthaHindle & @aariops! How are things going reviewing this project? Let me know if you have any questions 😃

**Comment by SamanthaHindle** [comment]
Hi @acabunoc and @alyeffy! 
Sorry for the delay. @alyeffy your repo looks great and very well put together. I am going to get on this tomorrow and review in more detail. I hope that's ok, and thanks for bearing with me! ❤️

**Comment by aariops** [comment]
Hey @alyeffy 

Sorry for taking us a while to get back to you. Great repo and great issue tagging. I think the `moderate-difficulty` and `beginner-friendly` tags are really useful for getting different types of people involved. Also, your issues seem to be really well structured (to-do lists are awesome). I'll be sure to show them to communities that may me struggling a bit with creating issues. I hope you don't mind.

I have approved your Mozilla Pulse entry now. https://www.mozillapulse.org/entry/655 :smile:
