### ISSUE TITLE
WikiPathways

### ISSUE THREAD

**Issue by AlexanderPico** [mozilla/global-sprint#155]
**[ Project Contact ]** @AlexanderPico
**[ GitHub Repo ]** https://github.com/wikipathways/wikipathways.org
**[ Track ]** Web Literacy, Openness, Decentralization, 
**[ Location ]** San Francisco, CA, PT

### Description
WikiPathways is an open, collaborative platform for drawing pathway models of biological processes. Each pathway "article" includes an interactive and fully annotated diagram along with descriptions and structured information. These pathway models are used by researchers, educators and clinicians for learning, data visualization, analysis and active research projects.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by AlexanderPico** [comment]
https://github.com/wikipathways/wikipathways.org

**Comment by AlexanderPico** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by AlexanderPico** [comment]
...though I forgot to add `mozsprint` and `2018` tags to our Pulse application. I'll add them once I have access to the project, i.e., after it's accepted, I presume.

**Comment by abbycabs** [comment]
Hey @AlexanderPico I added the tags for you 😄 

Great repo & issues! I'm having trouble finding the code of conduct or the contributing guidelines? https://github.com/wikipathways/wikipathways.org

Let me know when those are in place and I can approve your Pulse entry :)

**Comment by AlexanderPico** [comment]
oh... no... oh no... Ack! I forced a push a few days back and deleted all commits during Feb and early Mar!  This was mainly a ton of new documentation work inspired by the OL program. Ugh. I need to find copies somewhere, somehow :cry

**Comment by AlexanderPico** [comment]
Maybe I *should* have attended the Git101 😢

**Comment by AlexanderPico** [comment]
api.github.com is now my best friend... digging through patches...

**Comment by AlexanderPico** [comment]
Restored!  😓 

Please checkout our README again with links to CONDUCT, SOP, CONTRIBUTING and ROADMAP. 

And thank you for pointing this out!

**Comment by abbycabs** [comment]
🤣 sorry you had to go through all that! Looks great now 👍 & you're featured on pulse: https://www.mozillapulse.org/entry/621
