### ISSUE TITLE
p5.js

### ISSUE THREAD

**Issue by lmccart** [mozilla/global-sprint#156]
**[ Project Contact ]** @lmccart
**[ GitHub Repo ]** https://github.com/processing/p5.js
**[ Track ]** Web Literacy, Openness, Digital Inclusion, 
**[ Location ]** LA / SF (PST)

### Description
p5.js is an open-source JavaScript framework that makes learning to code and expressing yourself creatively on the web accessible to artists, designers, educators, beginners, engineers, activists, journalists, students, teachers, and anyone!
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by lmccart** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Featured 🎉  https://www.mozillapulse.org/entry/681
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

Make sure you add a `mozsprint` label to anything you'd like worked on during the sprint :)

**Comment by m90** [comment]
I'd much love to join here. That being said, I'm slightly confused about the how, so any hints about how to start this are much appreciated.

**Comment by raulgrell** [comment]
I have a few hours to spare, count me in! I'll be going over issues to see if there's anything I can throw myself at. What does the mentored label mean?

**Comment by lmccart** [comment]
hey @m90 and @raulgrell thanks so much! I've just posted an issue that more clearly documents how to contribute to the p5.js project for the sprint: https://github.com/processing/p5.js/issues/2865

we are focusing on documentation for this sprint, but you are of course welcome to jump into any [issue](https://github.com/processing/p5.js/issues/) if you feel comfortable.

@raulgrell the mentored label I believe just means that this is a project mentored through the [mozilla open leaders program](https://mozilla.github.io/leadership-training/). @acabunoc and @katjaq are my mentors for this project.

welcome!

**Comment by cecilebertin** [comment]
Hi @lmccart, I would love to join too. I will be at the Mountain View site on Thursday and Friday.
