### ISSUE TITLE
Aardwolf

### ISSUE THREAD

**Issue by BanjoFox** [mozilla/global-sprint#157]
**[ Project Contact ]** @BanjoFox
**[ GitHub Repo ]** https://github.com/BanjoFox/aardwolf
**[ Track ]** Openness, Privacy + Security, Digital Inclusion, Decentralization, 
**[ Location ]** US/New York City, New York
**[ Coach ]** @aj-ptw

### Description
An open, federated, Facebook-like social networking application.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi @BanjoFox,

@aj-ptw will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by BanjoFox** [comment]
Thank you @acabunoc!
Right now the repo is still a total mess (IMO) but it is constantly improving!

@aj-ptw  -- I have a CONTRIBUTING.md currently which -should- be okay, but I've also been working on the "Hackers Guide to Aardwolf" which aims to supplement that with a project walkthrough (in the README.md) as well as some feature/target-specific documentation.  

Will have to poke the rest of the team to see how we want to handle the '''mozsprint''' and '''2018''' tags.  There is still much chaos to be wrangled. -.-

**Comment by andrewjaykeller** [comment]
Wrangle away! 

> Will have to poke the rest of the team to see how we want to handle the '''mozsprint''' and '''2018''' tags

Do you have any questions I can try and answer to help you figure out how to best use these? I see that you are using the 'mozsprint' tag, maybe you can check the box above in this issue?

**Comment by BanjoFox** [comment]
Yeah I did a bit of housekeeping with my buddy David Ross (who led me here).  So I think things are shaping up a lot better now :)

Essentially I copy/pasted the documentation from "Hackers-Guide-to-Aardwolf" into actual GitHub issues so that they can be commented on without having to do a Pull Request.  They should also be cross-linked now.  I might poke at the Projects tab a bit more today as well.

Any thing else you might suggest? :)

Addendum:
Do you have access to the Mozilla Pulse form?  I forgot to add the tags -.-  Managed to read, and understand the instruction, but completely glazed over it when I got to that point.

P.s.  Your brain/browser interface looks AMAZING... I am going to start stashing money away to buy one hahah :D

**Comment by BanjoFox** [comment]
This is ready to be featured on Mozilla Pulse

-- Ripping off the bandage XD.  I am working on a banner image as well, but pretty much everything else should be in place.  Also need to double-check that the ` mozsprint` and `2018` tags were added x.X

**Comment by andrewjaykeller** [comment]
Alright I have an hour blocked off today to go through this!

**Comment by BanjoFox** [comment]
Good to know :)

All of my "public" contact info is also here: [banjo.codes](http://banjo.codes/)
Please feel free to poke me on any of them.  You are also more than welcome to hang out in chat if you want.

**Comment by andrewjaykeller** [comment]
Advice: Create a roadmap.md instead of a contribution wish list, most contributing guides go right into how contributions should be made.

Add a welcome message, and restate the project vision.

**Comment by andrewjaykeller** [comment]
You have the same info twice in the contributing page:

```
## Contribution Tips and Tricks
- Please review our [Code of Conduct](CODE_OF_CONDUCT) before contributing.
- Contributions should be made as Github pull requests. If this sounds daunting, we can help! Don't get discouraged, because we were all beginners once.
- Rust code lives in /src/, WebUI lives in /templates/
- If you see an issue you'd like to work on, leave a comment on the issue in order to prevent duplicate efforts, and so interested folks have a point of contact for collaborating.
- Verify code changes (cargo run --bin aardwolf-server) are functional before submitting, and ask for help when you run into problems.
- All pull requests will be reviewed by at least one [core contributor](https://github.com/BanjoFox/aardwolf/wiki/Contributors) (someone with permission to merge PR's) before merging. Core contributors will also follow this process.
- You may find [the project's references](https://github.com/BanjoFox/aardwolf/wiki/Project-References) and [the project's wiki](https://github.com/BanjoFox/aardwolf/wiki) helpful.
- When in doubt, [ask for help](#communication)!

## Pull Request Checklist

- Branch from the master branch and, if needed, rebase to the current master branch before submitting your pull request. If it doesn't merge cleanly with master you may be asked to rebase your changes.
- Commits should be as small as possible, while ensuring that each commit is correct independently (i.e., each commit should compile and pass tests).
- If your patch is not getting reviewed or you need a specific person to review it, please do one of the following: request a reviewer in the pull request (upper right corner of the PR), @-reply a reviewer in a comment, request a review in [#aardwolf-discussion:matrix.org](https://riot.im/app/#/room/#aardwolf-discussion:matrix.org) or on the mailing list `aardwolf-development@lists.riseup.net` (you do not need to join the mailing list to do this).
- Add relevant tests to the fixed bug or new feature. For a DOM change, this will usually be a web platform test; for layout, a reftest. **TIP:** You may find [Servo's testing guide](https://github.com/servo/servo/wiki/Testing) helpful.
- **TIP:** Check out [@mikeizbicki's Git Cheat Sheet](https://github.com/mikeizbicki/ucr-cs100/blob/2015winter/textbook/cheatsheets/git-cheatsheet.md) and [Gun.io's How to Github](https://www.gun.io/blog/how-to-github-fork-branch-and-pull-request).

## Communication

- Most of the core contributors use Riot/Matrix room [#aardwolf-discussion:matrix.org](https://riot.im/app/#/room/#aardwolf-discussion:matrix.org)
- You can also join the [aardwolf-development mailing list](https://lists.riseup.net/www/info/aardwolf-development).
- @-Mentioning someone here will also receive a prompt response.
=======
# Contributing to aardwolf

Contributors are always welcome! Hopefully this guide will provide some pointers :D

## Getting started

High level approach:

1. Find something to fix/improve
2. Change code (Rust code lives in /src/, WebUI lives in /templates/`)
3. Run the app to verify (cargo run --bin aardwolf-server), make changes until it works
4. Open a PR (also can be done between 2. and 3. if you run into problems)

## Contributions

All contributions to Aardwolf or its dependencies should be made in the form of GitHub
pull requests (PR's). Each pull request will be reviewed by a core contributor
(someone with permission to merge PR's) and either merged in the main tree or
given feedback for changes that would be required. All contributions should
follow this format, even those from core contributors.

Should you wish to work on an issue, please claim it first by commenting on
the GitHub issue that you want to work on it. This is to prevent duplicated
efforts from contributors on the same issue.

Head over to [Aardwolf Starter Issues](TBD) to find good tasks to start with. 
If you come across words or jargon that do not make sense, please feel free to ask. 
We will probably be working on a proper glossary at some point after get a proper 
application running. 

## Pull Request Checklist

- Branch from the master branch and, if needed, rebase to the current master
  branch before submitting your pull request. If it doesn't merge cleanly with
  master you may be asked to rebase your changes.

- Commits should be as small as possible, while ensuring that each commit is
  correct independently (i.e., each commit should compile and pass tests). 

- If your patch is not getting reviewed or you need a specific person to review
  it, you can @-reply a reviewer asking for a review in the pull request or a
  comment, or you can ask for a review in [#aardwolf-discussion:matrix.org](https://riot.im/app/#/room/#aardwolf-discussion:matrix.org)
  or the mailing list `aardwolf-development@lists.riseup.net`.

- Add tests relevant to the fixed bug or new feature.  For a DOM change this
  will usually be a web platform test; for layout, a reftest.  See our [testing
  guide](https://github.com/servo/servo/wiki/Testing) for more information.

For specific git instructions, see [GitHub workflow 101](https://github.com/servo/servo/wiki/Github-workflow).
(( Yes this links to a different repo but I like how it reads so :P ))

```

**Comment by andrewjaykeller** [comment]
Add a welcome message to your readme! I always use the same message and i think it gives a nice flare and immediately welcoming feeling!

example:

```
## Welcome!

First and foremost, Welcome! :tada: Willkommen! :confetti_ball: Bienvenue! :balloon::balloon::balloon:

Thank you for visiting the Aardwolf repository.
```

**Comment by BanjoFox** [comment]
Yeah wow... I was so busy working on the other parts of documentation cleanup that I missed the duplication :)

I also like your other ideas so far.  Will draft them out over lunch, and post updates accordingly.

**Comment by andrewjaykeller** [comment]
Cool I will go through the docs again tomorrow around the same time and keep exploring more docs as we get these refined.

Also thanks for checking out my project! I think this is a great project too :)

**Comment by BanjoFox** [comment]
It would be much easier to get work done if all I had to do was "think" about what I wanted to write ;)

**Comment by andrewjaykeller** [comment]
Fam! You're telling me! lol keep up the great work, I'll join your social network! I've been FB free for 3+ years

**Comment by andrewjaykeller** [comment]
Welp I couldn't help myself haha https://github.com/BanjoFox/aardwolf/pull/109

**Comment by andrewjaykeller** [comment]
I know this is not a requirement but you should add a "good first issue" label, i linked to labels with mozfest for now

**Comment by andrewjaykeller** [comment]
You're readme could be revamped in a similar manor to match mozilla's style, I continuously employ it

Check it out in action:
https://github.com/OpenBCI/OpenBCI_WIFI/blob/master/README.md

**Comment by BanjoFox** [comment]
Of course I cannot seem to find it now, nor do I have it bookmarked, but one of the guides I read ages ago mentioned that "Good First Issue" tags should be for issues that are reasonably simple to resolve, and have known solutions.  That way beginners can get involved, and be mentored along the way.  Unfortunately I'm not sure if we have any of those yet, or at least not that fit that precise description.  Too many "work in progress", and "undefined" items.  if you have suggestions for Good First Issue I would gladly implement :)

I am actually going to print out a copy of your Mozilla-style README, and probably make notes on it.  Looks good, and easier to navigate.  The verbiage on Aardwolf currently pretty much matches what is on [the homepage - aardwolf.social](https://aardwolf.social)

**Comment by andrewjaykeller** [comment]
> I read ages ago mentioned that "Good First Issue" tags should be for issues that are reasonably simple to resolve, and have known solutions. That way beginners can get involved, and be mentored along the way. Unfortunately I'm not sure if we have any of those yet, or at least not that fit that precise description.

You are very correct! Should be mainly documentation, making a logo, etc...

One thing I keep seeing is that you mention it's not important if the reader does not know Rust, well either don't say that line at all or provide examples of the other languages they could use, aka CSS makes up more than 50% of your code base and that's taught to middle schoolers, so if you can figure out how to get this install process so simple, you could really open your self up to a whole other form of contributor!


Yup here is a bunch of examples of the readme style, seriously i keep using it hahah

https://github.com/OpenBCI/OpenBCI_JavaScript_Utilities
https://github.com/OpenBCI/OpenBCI_Python/blob/1.0.0/README.md
https://github.com/OpenBCI/OpenBCI_GUI/blob/master/README.md

**Comment by BanjoFox** [comment]
I do actually have a... (let's face it undocumented) repo for the [Interface-only parts](https://github.com/BanjoFox/aardwolf-interface)

But I see your point :)

(( Aside: I read the "Not sure what to buy?" on the OpenBCI homepage and my brain immediately responded with "Uhm... All of it?"))

**Comment by BanjoFox** [comment]
Also not a fan of how GitHub does code breakdown.  It is mostly "CSS" because I added a static copy of ForkAwesome to avoid the CDN requirement.  Functional code is still mostly Rust/HTML ;D

**Comment by andrewjaykeller** [comment]
Ahh that's a bummer, but yeah that could be a really great area for newbies to chip in! And another repo you could roll out your snazy readmes into.

**Comment by andrewjaykeller** [comment]
Have you made an [Open Canvass](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/) yet? It was super helpful for me!

**Comment by andrewjaykeller** [comment]
And you're based in NYC?!? We should grab a coffee one of these days!

**Comment by BanjoFox** [comment]
I am Central New Jersey but yeah I can make it up to NYC in about an hour (or 4 depending on traffic hahah :D)

Updated README in the "mozsprint_doc-updates" branch ;)
https://github.com/BanjoFox/aardwolf/blob/mozsprint_doc-updates/README.md

**Comment by BanjoFox** [comment]
Guess I'm ALSO doing an OpenCanvas this weekend LOL

**Comment by BanjoFox** [comment]
Made some README updates (finally).  Have a lot more TODO's on my list though, including some documentation bugs to fix haha.

https://github.com/BanjoFox/aardwolf/blob/mozsprint_doc-updates/README.md

**Comment by andrewjaykeller** [comment]
@BanjoFox please let me know when you feel this is truly ready and I'll follow my duties which im still trying to figure out ;) 

Apparently I just remove the first comment, somewhere.

**Comment by BanjoFox** [comment]
Sure thing coach!
I posted that update to the branch as I was walking out the door to go home last night XD.
Should have everything "finalized" today.  Going through all the verbiage to minimize my "informal" tone ;)

**Comment by BanjoFox** [comment]
Okay.  Updates have been merged.  Unless you see anything else that should be changed I believe we are good to go :)

**Comment by andrewjaykeller** [comment]
@BanjoFox can you please add in mozilla pulse:

- [ ] Project Image
- [ ] Fix description, take copy (words and sentences) from your website to update
- [ ] List any other creators of the project
- [ ] Fix syntax error in contributions section (remove "and" before the word "work")

**Comment by BanjoFox** [comment]
Do you have a link for me to edit to the Mozilla Pulse form accordingly?
I keep trying to find it, but the only thing I see is to create a new one.

Addendum:
Also asking in the Gitter chat.

**Comment by andrewjaykeller** [comment]
@acabunoc any ideas? i was going through the instructions you sent me and pulled out what needs to be touched up on @BanjoFox mozila pulse page

**Comment by BanjoFox** [comment]
@aj-ptw -- According to @acabunoc from the Gitter chat.  The shortest path to edits is for you to reject the application, so that I can submit a new one :)

Probably needs to be in that order.  Otherwise I would be doing it now ;)

**Comment by andrewjaykeller** [comment]
done!

**Comment by BanjoFox** [comment]
So.... I messed up, and re-submitted the sprint application, BUT... I quickly realized my mistake, and Re-did the PULSE form which is what you were talking about in the first place.

That'll teach me to multi-task at work ;D

Also had to do a bit of work re-sizing the image, but I think it's okay.

**Comment by andrewjaykeller** [comment]
Awesome I’ll check it out as soon as I’m back to my computer tomorrow morning!! Thank!

**Comment by BanjoFox** [comment]
:+1:

**Comment by andrewjaykeller** [comment]
Ok I switched to approved!!

**Comment by BanjoFox** [comment]
Wooo!

Do you know what comes next?

**Comment by abbycabs** [comment]
Quick update: I added some missing tags so your project now appears here on your featured list: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/ 🎉

**Comment by BanjoFox** [comment]
Cool! Thanks @acabunoc !  I always seem to under-emphasize myself, as well as my projects ;)

Just curious about what tags were missing?

p.s.
It looks like there was an extra comma after Eric Chadbourne in the list of contributors... oops XD

**Comment by abbycabs** [comment]
`mozsprint` and `2018`

**Comment by BanjoFox** [comment]
oh... der... -.-

XD
