### ISSUE TITLE
Author Carpentry

### ISSUE THREAD

**Issue by tmorrell** [mozilla/global-sprint#158]
**[ Project Contact ]** @tmorrell
**[ GitHub Repo ]** https://github.com/AuthorCarpentry/planning
**[ Track ]** Web Literacy, Openness, Digital Inclusion, 
**[ Location ]** Pasadena, CA, PST
**[ Coach ]** @anmechung 

### Description
AuthorCarpentry is a set of open lessons designed to enhance scientific authorship and publishing in the digital age. Its aim is to promote and support best practices in open science and research communication. AuthorCarpentry lessons cover tools, workflows, practices, and skills that help researchers prepare, submit, and publish contributions that add value to an open scholarly record and invite others to adapt and build upon their work.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by tmorrell** [comment]
Our planning GitHub repo is located at: https://github.com/AuthorCarpentry/planning

You can find more information about the project at https://authorcarpentry.github.io
Each lesson has its own GitHub repo, linked from the lessons page.

**Comment by tmorrell** [comment]
We've got a pulse page from last year: https://www.mozillapulse.org/entry/271

Should we submit the form to create a new one or should we somehow reuse the old one?

**Comment by abbycabs** [comment]
Hi @tmorrell ,

@anmechung will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉 

Also, please submit a new entry to pulse!

**Comment by tmorrell** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by anmechung** [comment]
@tmorrell Are there any updates you'd like to add since last year?  I noticed that all the issues are from May 2017.  Also, could you tag with 2018 to these issues so that people know they are still relevant for this year, assuming this is the case?

**Comment by tmorrell** [comment]
@anmechung I submitted a new entry to pulse with a better image and a few other updates.  Thanks for the suggestion on the issue tagging, I've added 2018.  We should also have a few more issues and new content to review before the sprint.

**Comment by anmechung** [comment]
@tmorrell terrific!

**Comment by abbycabs** [comment]
I saw your new pulse entry and went ahead and approved it!
You're featured here: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/ 🎉 

@anmechung let us know if you have any additional feedback :)
