### ISSUE TITLE
Aletheia

### ISSUE THREAD

**Issue by KadeMorton** [mozilla/global-sprint#159]
**[ Project Contact ]** @KadeMorton
**[ GitHub Repo ]** https://github.com/aletheia-foundation/aletheia-admin, https://github.com/aletheia-foundation/aletheia-app, https://github.com/aletheia-foundation/aletheia-events-and-outreach
**[ Track ]** Openness, Digital Inclusion, Decentralization, 
**[ Location ]** New Zealand UTC +12
**[ Coach ]** @erindcole

### Description
A Decentralised, Open Access, Publishing Platform for Scientific Research
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi @KadeMorton ,

@erindcole will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by KadeMorton** [comment]
@acabunoc Much appreciated! 

This is ready to be featured on Mozilla Pulse

**Comment by erindorothy** [comment]
Hi @KadeMorton, great to meet you. I've been looking over your repo, wondering if we could chat about some ideas I have to encourage more contributors.

**Comment by KadeMorton** [comment]
Hi @erindcole , I'd be happy to talk! Did you want to run through stuff here, email, skype?

**Comment by erindorothy** [comment]
How about a Skype call? I can email you to figure out a time if you like :smile:

**Comment by KadeMorton** [comment]
Sent you an email!

**Comment by erindorothy** [comment]
Hi @KadeMorton I'm sorry we were never able to connect. Seems we have conflicting schedules. If you add more labels to your Issues, you should be good to go. That was the my minimal suggestion.

**Comment by abbycabs** [comment]
Hey @KadeMorton  

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Only thing I see left to do is adding the `mozsprint` label on some of your issues so you appear here: https://github.com/search?q=label%3Amozsprint&state=open&type=Issues

Let us know if you have any questions! And happy sprinting :)

**Comment by KadeMorton** [comment]
I added labels a little while ago, wanted to confirm if there is anything else I need to do to make the featured projects page?  Or if there is an issue with the labels?

![image](https://user-images.githubusercontent.com/24201238/39746566-cd9bf998-52fe-11e8-8fe0-092c2a7e7c0e.png)

![image](https://user-images.githubusercontent.com/24201238/39746609-f2fb5aa8-52fe-11e8-8c1f-077277e5f1ca.png)

![image](https://user-images.githubusercontent.com/24201238/39746646-123dc5a4-52ff-11e8-8b81-429dd272c5e6.png)

**Comment by abbycabs** [comment]
Ah, we only have one repo in your registration and I don’t see the mozsprint label there: https://github.com/aletheia-foundation/aletheia-admin/issues

Please list all the repos you’ll be working on during the sprint!

**Comment by KadeMorton** [comment]
Is separation by comma in the original post OK?
