### ISSUE TITLE
Internet Safety Driving Licence

### ISSUE THREAD

**Issue by lisahandsonline** [mozilla/global-sprint#16]
**[ Project Contact ]** @lisahandsonline
**[ GitHub Repo ]** https://github.com/lisahandsonline/Internet-Safety-Driving-Licence
**[ Track ]** Web Literacy, Privacy + Security
**[ Community ]** Teach the Web - @jvallera 
**[ Location ]** Dublin, Ireland GMT
### Description
Open online course that will enable young people to stay safe & protect their online reputation on social media sites & on the Internet.

Course content to include:

- best practice tips & templates
- role play activities
- thought provoking videos
- recommended reading material
- webinars from trainers
- gameful learning
- online mentoring
- final test
- certificate of achievement

5 modules:

- Cyberbullying
- Online Privacy & Security
- Social Media Use
- Online Reputation
- Webiquette
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @lisahandsonline! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @chadsansing. We're here to help you through this process.

**Comment by chadsansing** [comment]
Very cool, @lisahandsonline. Might be helpful to share your project when ready and to recruit participants from our curriculum and Mozilla Clubs communities on Discourse, our public forum.

- [Curriculum](https://forum.learning.mozilla.org/c/curriculum)
- [Clubs](https://forum.learning.mozilla.org/c/mozilla-clubs)

**Comment by lisahandsonline** [comment]
Thanks Chad - will do!

**Comment by lisahandsonline** [comment]
Hi Chad,

I just shared my project with the curriculum community on Discourse -
hopefully it will get a bit traction.  Thanks for the heads up again.

Best,
Lisa

**Comment by chadsansing** [comment]
Super cool. I will share the link on @MozLearn this week. Let me know how your repo progresses - I can share that, too.

**Comment by lisahandsonline** [comment]
https://github.com/lisahandsonline/Internet-Safety-Driving-Licence

Would appreciate your feedback.  Next step is to get my existing draft
course content into Drive & share it in the repo :)

Best,
Lisa

**Comment by chadsansing** [comment]
Great title and breakdown of the sections and work, @lisahandsonline. I especially like the Code of Conduct. Will the curriculum ultimately be available with an open license and in a place that doesn't require a login? For example, will the Google Docs remain open? It looks like the Kilroy's College site uses copyright and Moodle requires a login.

**Comment by lisahandsonline** [comment]
Hi Chad,

Thanks for your feedback.  I amended the README a little after reading your
comment.  It is envisioned that the curriculum will be available with an
open licence - but it will always require a login.

After chatting with my mentor Achintya last week, I decided to initially
plan to offer the first module "Cyberbullying Awareness" on my own Moodle
site (Kilroy's College).  This is so that I can run a beta test and track
progress and get feedback from a group of secondary school kids on the
content.  I would be absorbing the cost of this set up into my business.

I would then love to be able to build a dedicated website and associated SM
sites and move to and offer a HTML version - learners would still need to
login but this via SM login.  I will need funding for this however for the
set up and on-going maintenance and admin.  Achintya had mentioned that
there might be some EU or US mini grants available and he also pointed me
towards Patrion/tipping service model.  I also plan to go back to some
corporate entities that I met with previously to see if they will sponsor
the website and/or contribute content/resources.

On the content - going forward when building the rest of the modules that
comprise the full course I would keep Google docs open or I can move all
the content into Github - it is very important that contributors and
educators can freely access the content - I had not thought about that
aspect!  What would you recommend here?

This is my first time working in open so I am a novice and would appreciate
as much feedback as possible :)

On another note I have been invited to talk on a radio show (RTE 1) here in
Dublin this Friday.  I am hoping to be able to mention my project and the
Global Sprint.  Where should I direct listeners so that they can find out
more about all of the projects?

Thanks again for your input.

Best,
Lisa

**Comment by chadsansing** [comment]
@lisahandsonline - thank you for taking the plunge into working open! I think the [Global Sprint](https://mozilla.github.io/global-sprint/) site might be the best place to direct people right now. @zee-moz, what do you think?

In terms of where to keep work open, I think GDocs or GitHub would be fine, but it would also be great to have the work in both places so that people who feel most comfortable on one platform or another can contribute there. Make sense?

I'm sure others are also problem-solving long-term, sustainable hosting. Maybe you could file an issue in your repo that asks people to share best practices for sustainability of open projects?

Thanks again for sharing your project with the Sprint!

**Comment by lisahandsonline** [comment]
👍🏻

**Comment by zee-moz** [comment]
@chadsansing @lisahandsonline yes, absolutely, point people to the Global Sprint site--- we've just opened the [registration page](https://mozilla.github.io/global-sprint/register/), too, so you can mention that people can look for sites and sign up there, or sign up virtually. And oh WOW, it would be so great if you could send us a link to any info or promotional material about your appearance on the show, and/or where it's archived online after the broadcast. I'd love to share it as part of our Sprint promotions. 😸  Thank you! z

**Comment by lisahandsonline** [comment]
Hi Zannah,

I will do my best to get a plug in - it's radio so will work best if I just
tell people to google Mozilla Global sprint 2017.  The interview is
actually about my daughter Natasha (15) who got into Early University
Entrance so I plan to say that she is going to help me build the module.
It is on the Brenda Donoghue show on RTE 1 (think it will be aired next
Wednesday so it is not live I hope!)

I'll let you know :))

**Comment by lisahandsonline** [comment]
Hi Zannah,

I spoke to the RTE interviewer before the recording and told her about my
project.  She is planning another segment about teens and is going to
interview me again specifically about the Mozilla project.

The interview was at Dublin City University which has a programme for
gifted kids called CTYI - I mentioned my project to the CTYI Programme
Director and he is going to put me in touch with a couple of people at DCU
who might like to collaborate - they have already out together some content
on bullying.  He also said that the kids might like to get involved which
would be great.  They have an exchange programme with the Herberger Academy
and Arizona State University (which my daughter attended last summer) and
there might also be some interest from the kids at Herberger.  I will reach
out to them too.

I will keep you posted on the radio interview.

Best,
Lisa

**Comment by jvallera** [comment]
This is great! @lisahandsonline can't wait to get this project featured on Pulse. Let me know when you think it is ready. We will need a picture as well, which you can add here.

**Comment by stephwright** [comment]
Hi @lisahandsonline ... this looks like a great project and I'd love to see it get traction during the Global Sprint.  I just submitted a pull request to update the link to your actual CONTRIBUTING doc.  I love your Code of Conduct!  Could you link that from your README too?  You're so close to this being able to be made a featured project on Pulse (https://www.mozillapulse.org/latest)!

**Comment by lisahandsonline** [comment]
Hi Stephanie - I just made those amendments - thanks you for input :)

**Comment by stephwright** [comment]
🎉 awesome!  Such a speedy response!  Thank you!  Once you get a few issues in your issue tracker, this project will be ready for @jvallera to add to Pulse!

**Comment by jvallera** [comment]
Great! Once the checklist is complete above (i.e. still need pic) please respond here with "this is ready for Pulse" and I will add it asap. Thanks!

**Comment by lisahandsonline** [comment]
Hi Stephanie,

I just added an issue
<https://github.com/lisahandsonline/Internet-Safety-Driving-Licence/issues/2>
(looking
for graphic designers to help design new characters for the digi comics)

Please let me know if this is ready to add to Pulse.

Best,
Lisa

**Comment by jvallera** [comment]
Hi @lisahandsonline It is almost ready! I just need an image to use for the project listing. YOu can upload one here - it can be anything...a photo, logo, graphic, etc. 

Thanks for adding an issue. I suggest adding a few more before the sprint starts, to get a diversity of contributors with different skills looking at your project. Here is a good example of a variety of simple issues: https://github.com/dunebuggie/participation-collaboration-mozillaclubs/issues

**Comment by lisahandsonline** [comment]
​
​
​
​

**Comment by lisahandsonline** [comment]
Hi Chad,

Here is my image for Pulse - thanks a mill!

![internet-safety-driving-licence png](https://cloud.githubusercontent.com/assets/27348227/26559745/5f8cf5ce-44a9-11e7-8b51-8381ef19a12d.jpg)

**Comment by lisahandsonline** [comment]
This is ready for Mozilla Pulse

**Comment by jvallera** [comment]
great image @lisahandsonline !
Before posting to our site I want to make sure it is openly licensed - is it something you created? If not, can you confirm if it is available for re-use? Creative commons is a good place to find freely licensed content: https://creativecommons.org/use-remix/

Once I hear back from you I will get it up on Pulse ASAP.

**Comment by lisahandsonline** [comment]
Hi,

It is openly licenced - I created the original (Cyberbullying module) for a client & have their permission to re-use the content for the project. So it is good to go.

The rest of the modules are yet to be written or drafted!

Thanks a mill,

Lisa

**Comment by jvallera** [comment]
Great! project is posted here: https://www.mozillapulse.org/entry/323

**Comment by Saallen** [comment]
Hi @lisahandsonline delighted to see a fellow 🇮🇪 
I am hosting the presentation on June 1st and 2nd but I needed to move the times from 10am to 11am. Hope this still suits you? let me know

**Comment by lisahandsonline** [comment]
Hi Sarah,

That's perfect for me - thanks for hosting!  Are you in Dublin?  Perhaps we
could meet for a post sprint coffee?!

**Comment by Saallen** [comment]
Hello! Unfortunately not- I am based in London now.
Glad the new time still works- looking forward to meeting on vidyo tomorrow!
S

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
