### ISSUE TITLE
Parliamentary Debates Open

### ISSUE THREAD

**Issue by borbota** [mozilla/global-sprint#160]
**[ Project Contact ]** @borbota
**[ GitHub Repo ]** https://github.com/k-monitor/parldata
**[ Track ]** Openness, 
**[ Location ]** Barcelona, Spain

### Description
The tool aims to make parliamentary speeches open and accessible covering Hungarian parliamentary debates since 1990.
The scraped speeches are processed using Natural Language Processing, ElasticSearch is used for search backend.
The minimal viable product is a filterable dashboard for name, party, and date, returning the relevant speeches. Additional features will include topics, top lists, histograms and comparisons.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @borbota 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by borbota** [comment]
The project's [main github repo](https://github.com/k-monitor/parldata) contains the [CONTRIBUING.md](https://github.com/k-monitor/parldata/blob/master/CONTRIBUTING.md) describing where the project is currently, and the same repo has a [list of issues](https://github.com/k-monitor/parldata/issues?q=is%3Aopen+is%3Aissue+label%3Amozsprint), where we expect contributors during the Mozilla Global Sprint. 
If you would like to talk to me during the Sprint, please reach out to me at the [Etherpad](https://public.etherpad-mozilla.org/p/Parliamentary_Debates_Open) of the project set up for the event (No registration is needed to use Etherpad. It is synched constantly, so everyone can edit it at the same time and see the same text).
