### ISSUE TITLE
WordPress Plug-In Observatory

### ISSUE THREAD

**Issue by akritiko** [mozilla/global-sprint#161]
**[ Project Contact ]** @akritiko
**[ GitHub Repo ]** https://github.com/socialmind/wordpress-plugin-observatory
**[ Track ]** Openness, 
**[ Location ]** Thessaloniki, Greece (UTC+2)

### Description
We are creating a platform with the aim of crowd-sourcing experience on using or combining plug-ins in WP installations. In addition, we are going to combine those data with the application of state of the art software metrics to provide a preliminary study on the structure of the source code of the plug-ins. This way we provide valuable feedback to WP developers and WP end-users about the effectiveness and security of their installations.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by akritiko** [comment]
Forgot to add mozsprint and 2018 tags in the form :( Other than that [ I think ]

This is ready to be featured on Mozilla Pulse.

**Comment by abbycabs** [comment]
Thanks @akritiko - your repo looks great!

I'm looking at your Pulse submission -- do you have an image to use for the entry? We find it helps a lot.

**Comment by akritiko** [comment]
Thanks a lot Abby,

do we have a proposed size for the image? I will be creating one the
following days.

Cheers,

A.

--
*Apostolos Kritikos*
*"open mind is the Social Mind <http://www.socialmind.gr>"*

apostolos.kritikos.me
m: +30 6976 432 234

2018-03-27 4:06 GMT+03:00 Abigail Cabunoc Mayes <notifications@github.com>:

**Comment by abbycabs** [comment]
1200 x 630 px

**Comment by abbycabs** [comment]
Hey @akritiko - any update on an image?

**Comment by akritiko** [comment]
Made sth. Can be improved though :)




--
*Apostolos Kritikos*
*"open mind is the Social Mind <http://www.socialmind.gr>"*

apostolos.kritikos.me
m: +30 6976 432 234

2018-04-23 20:35 GMT+03:00 Abigail Cabunoc Mayes <notifications@github.com>:

**Comment by abbycabs** [comment]
Hi @akritiko -- not sure if you attached the image, but email attachments don't appear in the GitHub issue. Can you add the image in a comment? Or send a link? Thanks 😃

**Comment by akritiko** [comment]
![healthywp cover](https://user-images.githubusercontent.com/445175/39153677-7b4421da-4754-11e8-9ef4-a728dd57df03.png)

lets try again :)

**Comment by abbycabs** [comment]
YAY! updated: https://www.mozillapulse.org/entry/640

Abigail Cabunoc Mayes
Practice Lead, Working Open
Mozilla Foundation
@abbycabs / @acabunoc

**Comment by akritiko** [comment]
Looks so much better now! Thanks Abby :)

**Comment by akritiko** [comment]
Hi Abby,

I created an updated version of the cover image. Please update if it's not too much trouble. 
Many thanks in advance :)

![healthywp_cover](https://user-images.githubusercontent.com/445175/39188861-7eaadc4e-47d9-11e8-9b36-b1bdaa91e4dc.png)
