### ISSUE TITLE
gPanel

### ISSUE THREAD

**Issue by george-e-shaw-iv** [mozilla/global-sprint#162]
**[ Project Contact ]** @george-e-shaw-iv
**[ GitHub Repo ]** https://github.com/Ennovar/gPanel
**[ Track ]** Web Literacy, Openness, Privacy + Security, Digital Inclusion, Decentralization, 
**[ Location ]** Wichita, Kansas - Central Time
**[ Coach ]** @princiya

### Description
An open source web-hosting control panel written in Golang.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by george-e-shaw-iv** [comment]
GitHub repository for work and discussion: https://github.com/Ennovar/gPanel

**Comment by george-e-shaw-iv** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hi @george-e-shaw-iv ,

@princiya will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by princiya** [comment]
Hi @george-e-shaw-iv I am sorry for the delay in my side.

Firstly, thank you for being here :)

I noticed two things missing - `LICENSE.md` and `CONTRIBUTING.md`. Please correct me if I missed out seeing something.

**Comment by george-e-shaw-iv** [comment]
Hi @princiya no problem, and I'm glad to be here.

Those files are placed in my `.github` folder. I like to maintain a clean project root with as few files as possible.

Here is the link: https://github.com/Ennovar/gPanel/tree/master/.github

**Comment by princiya** [comment]
@george-e-shaw-iv I understand your concern to maintain a clean project structure.

Normally we are used to seeing these files in the root directory, and this is why people might miss out on them; happened to me, I didn't notice.

Could you either move them to the root directory or create links in Readme so that people know where to find these files.

We are good to go otherwise 👍

**Comment by abbycabs** [comment]
I'll add that github provides a lot of features if you place these files in the root directory. It detects your license, contributing guidelines and code of conduct and will prompt new contributors to look at these after certain actions (like creating a new issue). So, not required, but it can be helpful to add these to your root directory!

**Comment by george-e-shaw-iv** [comment]
@princiya @acabunoc No problem, I moved them back into the root!

**Comment by princiya** [comment]
@george-e-shaw-iv Thank you for considering the proposed changes.

Could you update the image for Mozilla pulse? A more clear image might help.

Also, please update the 'Help' link in the Mozilla pulse to point to your Github issues.

**Comment by george-e-shaw-iv** [comment]
@princiya I sent a request for them to update the link, and I was wondering what kind of image you think I should upload? Should I try and create an infographic or something? There really isn't a lot of still images from the software itself that I could use

**Comment by princiya** [comment]
@george-e-shaw-iv No, don't spend much time on it if it is too much of a work. For now, let's go with this one. In the days ahead, if you find a better clear image, then let's update :)

**Comment by princiya** [comment]
https://www.mozillapulse.org/entry/633 🎊 🎈

**Comment by princiya** [comment]
@acabunoc There are two entries for this project on pulse. Could you look into that and delete the other one please?

https://www.mozillapulse.org/search?keyword=gpanel

<img width="1004" alt="screen shot 2018-04-11 at 13 00 28" src="https://user-images.githubusercontent.com/8022693/38612888-60695234-3d88-11e8-9c14-272e97cc51e1.png">

**Comment by george-e-shaw-iv** [comment]
@princiya I sent in a request to delete the one with the unupdated get involved link, should be deleted as soon as someone gets around to responding to that request! If I can think of something clever to put into an infographic that would better suit this project, I will do so. Thank you for all of your help getting this ready!

**Comment by princiya** [comment]
@george-e-shaw-iv So the other entry has been deleted. And the issues link has been updated too :) You are all set 🎊 ㊗️
