### ISSUE TITLE
Pawah! Tech for human rights

### ISSUE THREAD

**Issue by InnovaPolitica** [mozilla/global-sprint#163]
**[ Project Contact ]** @InnovaPolitica
**[ GitHub Repo ]** https://github.com/InnovaPolitica/Pawah-tech-for-human-rights
**[ Track ]** Privacy + Security, 
**[ Location ]** La Paz, Bolivia. GMT-4

### Description
Pawah! is a tool that aims to strengthen plausible deniability and transitional justice
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by InnovaPolitica** [comment]
This is ready to be featured on Mozilla Pulse.

**Comment by abbycabs** [comment]
Hey @InnovaPolitica!
The repo you listed is giving me a 404: https://github.com/InnovaPolitica/Pawah.TechforHumanRights
But this one works! https://github.com/InnovaPolitica/Pawah-tech-for-human-rights

Is the 2nd one the correct one?

**Comment by InnovaPolitica** [comment]
Yes, the link was wrong. The second one is the correct. Thank you

**Comment by abbycabs** [comment]
You're on pulse! https://www.mozillapulse.org/entry/785 🎉 

You're on the featured projects page: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
