### ISSUE TITLE
PhyloProfile

### ISSUE THREAD

**Issue by trvinh** [mozilla/global-sprint#164]
**[ Project Contact ]** @trvinh
**[ GitHub Repo ]** https://github.com/BIONF/PhyloProfile
**[ Track ]** Openness, 
**[ Location ]** Frankfurt am Main - Germany, CET (UTC +1)

### Description
PhyloProfile is a dynamic visualisation and analysation R-based tool for multi-layered phylogenetic profile. The benect of having multi-layered information is that the profiles will be more informative, making the profiling results more reliable. Together with the dynamic ability for visualising and exploring data, this tool enables a comprehensive analysis of phylogenetic profiles.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by trvinh** [comment]
`This is ready to be featured on Mozilla Pulse` ^_^

**Comment by abbycabs** [comment]
Forgot to comment, featured! https://www.mozillapulse.org/entry/657 🎉 
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
