### ISSUE TITLE
phageParser

### ISSUE THREAD

**Issue by mbonsma** [mozilla/global-sprint#165]
**[ Project Contact ]** @mbonsma
**[ GitHub Repo ]** https://github.com/phageParser/phageParser
**[ Track ]** Openness, 
**[ Location ]** Toronto, Ontario (ET)
**[ Coach ]** @quirksahern & @fimakeswork

### Description
A project to extract CRISPR information from open genetic data.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi @mbonsma ,

@quirksahern & @fimakeswork will be your Project Coach for the Sprint! They will review this issue and approve your entry on Mozilla Pulse if everything looks good 🎉

**Comment by quirksahern** [comment]
Hi @mbonsma,

I've just a read through of your project documents and it seems really interesting.
Do you currently have a project canvas? - when I clicked on the link it returned a 404 error.

**Comment by mbonsma** [comment]
@quirksahern, good catch! The link was broken when we moved some folders around, I fixed it in the README. (https://github.com/phageParser/phageParser/blob/master/documentation/Open_canvas.png)

**Comment by quirksahern** [comment]
Nice, clear canvas. Also, a really good read me. Just a couple more things to check off then I think you're good to be featured.

**Comment by quirksahern** [comment]
Hi @mbonsma, how are you getting on?

**Comment by mbonsma** [comment]
Hi @quirksahern, thanks for the check-in! I still need to go through the issues and make / edit some for the sprint, and I'm leaving Open Leadership 101 unchecked as a reminder to go through it again. I hope to be done all the checklist things in the next 1-2 weeks!

**Comment by quirksahern** [comment]
Hi @mbonsma, thanks for the update.
Please let me know if you need a hand with anything.

**Comment by quirksahern** [comment]
hi @mbonsma , how's it going?

**Comment by mbonsma** [comment]
This is ready to be featured on Mozilla Pulse! I'll be adding / modifying more issues before next week, but I have a few ready for the sprint.

**Comment by quirksahern** [comment]
Approved
