### ISSUE TITLE
Open Web For Social Good

### ISSUE THREAD

**Issue by shashikanth171** [mozilla/global-sprint#166]
**[ Project Contact ]** @shashikanth171
**[ GitHub Repo ]** https://github.com/FOSS-World/Open-Web-for-Social-Good
**[ Track ]** Web Literacy, Openness, Privacy + Security, Digital Inclusion, Decentralization, 
**[ Location ]** New Delhi, India - IST

### Description
Support Non-Government Organizations and Non-Profit Organizations in using Open Web (Internet) to do their best in doing social good.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by shashikanth171** [comment]
Github Repository for the Project: https://github.com/FOSS-World/Open-Web-for-Social-Good

**Comment by abbycabs** [comment]
Hey @shashikanth171  

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by abbycabs** [comment]
Hi @shashikanth171 please add the `mozsprint` label to some issues! The Sprint has started
