### ISSUE TITLE
Designing offline activities & games for digital literacy

### ISSUE THREAD

**Issue by nam-301** [mozilla/global-sprint#167]
**[ Project Contact ]** @nam-301
**[ GitHub Repo ]** https://github.com/nam-301/culturabinaria
**[ Track ]** Web Literacy, Digital Inclusion, 
**[ Location ]** Physical location: Rovereto, Italy.  Timezone: CEST

### Description
I am managing an online repository containing teaching materials (especially hands-on offline activities and games -- as the teaching methods are inspired by principles of non-formal education) for an ongoing digital skills course aimed at low-educated migrants & asylum seekers who arrive in a new community. During the global sprint, there will be a hackaton (both in real life and from remote) aimed at expanding & improving the repository's contents.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by nam-301** [comment]
Hi! [This it the link](https://github.com/nam-301/culturabinaria) to my project's GitHub repo.

**Comment by nam-301** [comment]
Hi @acabunoc! I submitted the form in Mozilla Pulse a few weeks ago already (I was prob too early then), but I have not heard anything afterwards -- I did forget to add the tags mozsprint and 2018. To add to the confusion, I gave it a slightly different name than the mozspring submission here. Can we check what happened to that submission (+ maybe it can be modified?) before I go on with another one? Thank you! :balloon:

**Comment by abbycabs** [comment]
Hi @nam-301 -- we won't review your submission till you check off everything in the checklist. If you're unhappy with your current submission, feel free to resubmit!

If you'd like us to review your submission, go ahead and finish checking off items on your list :)

**Comment by nam-301** [comment]
This is ready to be featured on Mozilla Pulse.

**Comment by abbycabs** [comment]
Thanks @nam-301 I left one issue in your repo: https://github.com/nam-301/culturabinaria/issues/24

But otherwise, this is great! You're featured on pulse: https://www.mozillapulse.org/entry/800
And you're on the featured projects page: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/ 🎉 

happy sprinting!

**Comment by johngoodness** [comment]
hi, am interested in this project

**Comment by nam-301** [comment]
Thank you @johngoodness! Unfortunately, the materials are in Italian only at the moment, but you can read about what we are trying to do in the README and leave a comment in the [issues](https://github.com/nam-301/culturabinaria/issues) :)
