### ISSUE TITLE
OpenHeart Project

### ISSUE THREAD

**Issue by JoPauls** [mozilla/global-sprint#168]
**[ Project Contact ]** @JoPauls
**[ GitHub Repo ]** https://github.com/JoPauls/OpenHeart-Project
**[ Track ]** Openness, 
**[ Location ]** Brisbane, Australia / Australian Eastern Standard Time (AEST)

### Description
Within the OpenHeart Project we are working with other PhD students and early career researchers within the field of mechanical circulatory support to create an open-source community / network / platform so that undergrad and PhD students and early career researchers can collectively improve collaboration and standardization within the field of MCS, while gaining access to improved education and training tools.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by JoPauls** [comment]
https://github.com/JoPauls/OpenHeart-Project

**Comment by ece7048** [comment]
Hello, 
I am interested in contributing to this project during #mozsprint 2018. 
What shall I do? 
Thanks for your time.

**Comment by JoPauls** [comment]
Hello Michail,

thanks for your interest in the OpenHeart Project.
Currently I am prepping the project for the sprint, but feel free to visit the github repository. I will update the issues, README and contributors guidelines shortly.

Also, please visit www.openheartproject.org to find out more about the project. If you are keen to become a member of the OpenHeart community, fill out the Join form on the website and I will be able to create an account for you. Happy to answer questions you might have so feel free to shoot an email to contact@openheartproject.org. I will get the email. Looking forward to hear from you.

Cheers
Jo

**Comment by ece7048** [comment]
Hello Jo,

I am very excited concerning the OpenHeart project. Surely, I will fill out the Join Form. 
Thank you for your time. I am looking forward to participating in this interesting project.

Regards,

Mike

**Comment by JoPauls** [comment]
This is ready to be featured on Mozilla Pulse. 🎉 🎈

**Comment by abbycabs** [comment]
Excellent repo, @JoPauls!

Featured: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
Pulse: https://www.mozillapulse.org/entry/697

🎉
