### ISSUE TITLE
Foundation For Public Code

### ISSUE THREAD

**Issue by bvhme** [mozilla/global-sprint#169]
**[ Project Contact ]** @bvhme
**[ GitHub Repo ]** https://github.com/publiccodenet/about
**[ Track ]** Openness, 
**[ Location ]** Amsterdam, CEST

### Description
We create a viable future for cities and civic operating systems that are highly participatory and drive societal engagement. A public digital infrastructure that is inclusive, usable, adaptive, open and sustainable.

To achieve this we maintain, manage, contribute to and grow an ecosystem of public software and policies that help governments, communities and citizens improve their city.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by bvhme** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Featured! https://www.mozillapulse.org/entry/649 🎉 

https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

Make sure you add the `mozsprint` label to any issues you'd like worked on during the sprint :)
