### ISSUE TITLE
OpenGrid.io

### ISSUE THREAD

**Issue by PriyaDoIT** [mozilla/global-sprint#17]
**[ Project Contact ]** @PriyaDoIT
**[ GitHub Repo ]** https://github.com/Chicago/opengrid
**[ Track ]** Open Innovation
**[ Community ]** 
**[ Location ]** Chicago, IL CST
### Description
Open-source, interactive map platform that allows users to explore multiple data sources in an easy-to-use interface. Developed to support situational awareness, incident monitoring and responses, historical data retrieval, and real-time advanced analytics. Users can perform advanced queries to filter data, search within custom boundaries, or based on the users location. Other GIS data, such as weather and Shapefiles can be overlaid on the map with other data.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @PriyaDoIT! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by PriyaDoIT** [comment]
Hi @acabunoc, not sure why my posting was cut off?  Could you help include the rest of the template for me to fill out?  Thanks!

**Comment by abbycabs** [comment]
@PriyaDoIT -- Added!

**Comment by PriyaDoIT** [comment]
https://raw.githubusercontent.com/Chicago/opengrid/master/img/branding/OpenGrid_Logo_Horizontal_3Color.png

**Comment by PriyaDoIT** [comment]
opengrid/img/branding/OpenGrid_Logo_Horizontal_3Color.png

**Comment by stephwright** [comment]
Hi @PriyaDoIT ... looks like you're really close to having this ready to be a featured project.  Really just needs a link to a code of conduct or our community guidelines in the README.

**Comment by PriyaDoIT** [comment]
Hi @stephwright , since this project is through the City of Chicago, a government entity, our Code of Conduct has to undergo a review from our Law Department.  This may not be ready in the near future.

**Comment by stephwright** [comment]
Hi @PriyaDoIT ... Does the City of Chicago have a Code of Conduct you could use here?  Maybe from one of its other projects so it's already gone through review?

**Comment by omnignorant** [comment]
@stephwright @PriyaDoIT just to be clear, the remaining steps are to be featured on Pulse right? If it's not feasibly, the project can still participate in the sprint, correct?

**Comment by stephwright** [comment]
@omnignorant Oh yes!!! Absolutely! Even if you can't get a Code of Conduct attached, this should be a featured project.  In fact, if you have an image @PriyaDoIT (or don't want an image) I'd say this is ready to get Pulsed.

**Comment by PriyaDoIT** [comment]
Hi @stephwright , Chicago has many projects on GitHub, but I learned the importance of a Code of Conduct through the Mozilla training and it is at that point that I created one, so unfortunately we don't already have one.  As for an image, we have one here:
https://github.com/Chicago/opengrid/blob/master/img/branding/OpenGrid_Logo_Horizontal_3Color.png

**Comment by omnignorant** [comment]
Hi @PriyaDoIT thanks for the update and link to an image. @stephwright I want to be clear that you're suggesting to feature this project on Pulse as-is?

**Comment by stephwright** [comment]
Yep! Pulse away, I say :)

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
