### ISSUE TITLE
Spread Open Healthy Web (SOHW)

### ISSUE THREAD

**Issue by FahimaZulfath** [mozilla/global-sprint#170]
**[ Project Contact ]** @FahimaZulfath
**[ GitHub Repo ]** https://github.com/SOHW/Blogs
**[ Track ]** Web Literacy, Openness
**[ Location ]** Salem, Tamil Nadu, India and GMT+0530 (IST)
**[ Coach ]** @pransh15

### Description
SOHW is an open platform which enables people to learn, teach, develop and participate in web. Web Literacy acts a vital role in SOHW. It provides resources and information on current trending technologies across several science field and also welcomes resources from anyone, to share thoughts on different tracks (such as  Digital Inclusion, Openness, Privacy, etc), We gathers information about various available online tools which contains open license which makes everyone to learn and explore.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by FahimaZulfath** [comment]
This is ready to be featured on Mozilla Pulse!! 💯 @pransh15

**Comment by pransh15** [comment]
I think this looks fine and is ready to get featured on Mozilla Pulse!
Great work, @FahimaZulfath! 💯

Over to @acabunoc & @zee-moz for the rest! 😃

**Comment by abbycabs** [comment]
Great work!
Pulse: https://www.mozillapulse.org/entry/788
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/ 🎉

**Comment by FahimaZulfath** [comment]
Thanks, @pransh15 & @acabunoc !! 🎉 😃
