### ISSUE TITLE
floWeaver

### ISSUE THREAD

**Issue by ricklupton** [mozilla/global-sprint#171]
**[ Project Contact ]** @ricklupton
**[ GitHub Repo ]** https://github.com/ricklupton/floweaver
**[ Track ]** Openness, Decentralization, 
**[ Location ]** Cambridge, UK

### Description
Many kinds of data can be thought of as 'flows': energy and materials moving through industry, money flowing through the economy, telephone lines moving between providers, voters moving between parties. floWeaver helps you to analyse and exchange this type of flow data and visualise it using Sankey diagrams. It provides a set of Python tools that work standalone and with Jupyter notebooks for exploratory data visualisation, and a standard data format for flow data to support interoperability.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by cmaumet** [comment]
Hey @ricklupton! Thanks for submitting your project! I think this is almost ready for Mozilla pulse. Could you review the items above and check off the one you have done? For example, I know your README is ready, you do have a GitHub repo, you did complete Open leadership 101 (first week of OL5), etc.

Let me know if I can help you with any of the points above!

**Comment by ricklupton** [comment]
Project repo: https://github.com/ricklupton/floweaver

Thanks @cmaumet for the reminder :), I've added [CONTRIBUTING.md](https://github.com/ricklupton/floweaver/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](https://github.com/ricklupton/floweaver/blob/master/CODE_OF_CONDUCT.md) so I just need to sort out the issue tracker and good first issues.

**Comment by ricklupton** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by cmaumet** [comment]
Thank you @ricklupton! I have reviewed your project proposal. Do you think it would be possible to add a link to the code of conduct directly in the README?

**Comment by cmaumet** [comment]
Sorry if I missed it? Once this is done, I think your project will be ready!

**Comment by ricklupton** [comment]
Thanks @cmaumet, I added a link.

**Comment by cmaumet** [comment]
@acabunoc: I have reviewed @ricklupton's project and he has completed all the tasks to get featured for #mozsprint  🎉

**Comment by abbycabs** [comment]
YAY! Pulse: https://www.mozillapulse.org/entry/764
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

🎉 happy sprinting 🎉
