### ISSUE TITLE
Data + Friends

### ISSUE THREAD

**Issue by meagdoh** [mozilla/global-sprint#172]
**[ Project Contact ]** @meagdoh
**[ GitHub Repo ]** https://github.com/meagdoh/data-and-friends
**[ Track ]** Digital Inclusion
**[ Location ]** Washington, DC EST

### Description
A paper-based game addressing data literacy needs of the advocacy community.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by meagdoh** [comment]
[ GitHub Repo ] https://github.com/meagdoh/data-and-friends

**Comment by meagdoh** [comment]
@acabunoc I submitted to Mozilla Pulse and missed the `mozsprint` and `2018` tags. Should I re-submit?

**Comment by meagdoh** [comment]
This is ready to be featured on Mozilla Pulse.

**Comment by meagdoh** [comment]
Hi @acabunoc ! Is there anything else I need to update before getting on Mozilla Pulse?

**Comment by abbycabs** [comment]
Great work on your repo! I added the missing tags for you 🎉 
Pulse: https://www.mozillapulse.org/entry/686
Featured: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
