### ISSUE TITLE
India.data: Indian OGD (open government data) inference portal

### ISSUE THREAD

**Issue by karansapolia** [mozilla/global-sprint#174]
**[ Project Contact ]** @karansapolia
**[ GitHub Repo ]** https://github.com/karansapolia/India.data
**[ Track ]** Openness, Digital Inclusion, Decentralization, 
**[ Location ]** Jammu, India, IST (GMT +5:30)

### Description
It is a community built and maintained open data and data inference portal for all publicly available Indian survey and government data. It also maintains a quality ('health') check for data emitted by the government of india's open data APIs.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by karansapolia** [comment]
Github Repo: [India.data](https://github.com/karansapolia/India.data/blob/master/README.md)

**Comment by sourabhsmf** [comment]
Great Idea. Would love to participate

**Comment by karansapolia** [comment]
Hey @sourabhsmf! You can look into issues at the source repo or can contact me through @karansapolia on twitter if you want to join in before the sprint begins

**Comment by abbycabs** [comment]
Hey @karansapolia 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by joelvinaykumar** [comment]
Great idea. How do I join you ? @karansapolia

**Comment by digital-carver** [comment]
Hi @karansapolia, could you give us an idea of what you have in mind for the project? The Roadmap page gives a high level summary of the goal, but do you have a more concrete vision of what the project will contain and how it will be accessed and used?
