### ISSUE TITLE
Open Apparel Registry (OAR)

### ISSUE THREAD

**Issue by rhearakshit** [mozilla/global-sprint#175]
**[ Project Contact ]** Rhea Rakshit
**[ GitHub Repo ]** https://github.com/rhearakshit/open-apparel-registry
**[ Track ]** Digital Inclusion, 
**[ Location ]** New York / Mumbai

### Description
The Open Apparel Registry (OAR) is a tool to identify every apparel factory worldwide. It is is designed to be an open, crowdsourced database of apparel factories around the world, which normalizes information - i.e. factory names and locations - across multiple data sources.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi @rhearakshit! I assume this is the repo you'll be using for the sprint: https://github.com/rhearakshit/open-apparel-registry -- let me know if it's something else.

**Comment by rhearakshit** [comment]
Yep, that's the the one - thank you!

**Comment by abbycabs** [comment]
Hey @rhearakshit 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉
