### ISSUE TITLE
FlyCAGE

### ISSUE THREAD

**Issue by CodingBash** [mozilla/global-sprint#177]
**[ Project Contact ]** @CodingBash
**[ GitHub Repo ]** https://github.com/CodingBash/FlyCAGE
**[ Track ]** Openness, 
**[ Location ]** Bloomington, IL (CT Timezone)

### Description
FlyCAGE is a bioinformatics web application that conducts statistical analysis of gene expression data to retrieve insights about gene similarity. Simply, FlyCAGE observes the activity of genes and searches for other genes with a similar pattern of activity.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @CodingBash 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)
