### ISSUE TITLE
Privacy and anonimity tutorials for journalists

### ISSUE THREAD

**Issue by deimidis** [mozilla/global-sprint#180]
**[ Project Contact ]** @deimidis
**[ GitHub Repo ]** https://github.com/deimidis/privacy-journalists
**[ Track ]** Web Literacy, Privacy + Security, 
**[ Location ]** Buenos Aires, Argentina

### Description
A website where journalists can find information and tutorials to understand and use tools to protect their privacy
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by EileenDG** [comment]
Hello. I'd like to participate during Mozilla Global Sprint but I don't know how the plataform works (just joined GitHub). I will be very grateful to have some more information. Regards!

**Comment by abbycabs** [comment]
Hey @deimidis 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by deimidis** [comment]
Hello @EileenDG !

Thanks for your interest in the project. I will be glad to help you. Are you using [Gitter](https://gitter.im/) We create a Spanish mozsprint chat room to have conversations and help other.

Also, I sent you an email for your interest to join the mozsprint at the lab.

**Comment by deimidis** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hey @deimidis! I couldn't find your submission on pulse (https://www.mozillapulse.org/add). Otherwise, looks good!

**Comment by deimidis** [comment]
You are right, it had a problem submitting. Now it's works
