### ISSUE TITLE
MBac - Taking a closer look on how bacteria move!

### ISSUE THREAD

**Issue by vektorious** [mozilla/global-sprint#181]
**[ Project Contact ]** @vektorious
**[ GitHub Repo ]** https://github.com/vektorious/mbac
**[ Track ]** Openness, 
**[ Location ]** Munich, UTC+2h

### Description
MBac comprises software tools and an optional low-cost hardware setup for bacterial motility determination. The analysis is picture based can be used for monitoring bacteria movements on agar plates. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by vektorious** [comment]
Here is the link to the [project repository](https://github.com/vektorious/mbac) :fire:

**Comment by vektorious** [comment]
Yay! :tada:
This is ready to be featured on Mozilla Pulse!

**Comment by abbycabs** [comment]
Left one issues: https://github.com/vektorious/mbac/issues/10

But otherwise I thinks this is good to go! Featured: https://www.mozillapulse.org/entry/676 🎉 

https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

**Comment by vektorious** [comment]
Great! I already fixed the issue!

Thank you 😄

**Comment by vektorious** [comment]
@acabunoc 
I had a look at 
https://www.mozillapulse.org/entry/676
and I don't know why but there is a gray shade around the MBac logo. I uploaded a .png and it seemed to work fine for the small image in the [project collection](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/). 

It's not a big deal but is it possible to change the image afterwards? 
If not... well it doesn't matter too much.

**Comment by 2alin** [comment]
Hi, I'm adilson and I'm very interested and excited to contribute in this project. I have some skills in programming and math. Right now I'm more into javascript and web development but I learned python 3-4 years ago and coded with it for a couple of years (nothing great though, only small projects). I read you are suggesting OpenCV, which I haven't used in the past. But I will give it a read in the next 5 days and start preparing for your project :sunglasses:

**Comment by vektorious** [comment]
Hey Adilson! 
That's awesome 🎉 Welcome to the team!

You can join the [gitter channel for the sprint](https://gitter.im/mbac-project/global-sprint) if you like!

And if you have a particular issue you want to work on you can comment it so others will know
😄 

Looking forward to an awesome sprint! 🔥

**Comment by 2alin** [comment]
Thank you! Joining there then.
