### ISSUE TITLE
Make Rwanda Web Literate

### ISSUE THREAD

**Issue by solangetuyisenge** [mozilla/global-sprint#182]
**[ Project Contact ]** @solangetuyisenge
**[ GitHub Repo ]** https://github.com/solangetuyisenge/MakeRwandaWebLiterate/
**[ Track ]** Web Literacy, 
**[ Location ]** CAT

### Description
Make Rwanda Web Literate project will equip citizens with digital skills, and make sure they feel safe on internet focusing on people from underserved communities and women.
With the help of youth known as digital ambassadors we carry out awareness campaigns and willing citizens join our training program. Participants are given one month training and then form learning clubs where they keep learning together and use the gain skills to design income generating projects.

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by solangetuyisenge** [comment]
This is my project GitHub repository
https://github.com/solangetuyisenge/MakeRwandaWebLiterate

**Comment by abbycabs** [comment]
Hey @solangetuyisenge 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉
