### ISSUE TITLE
Voices under Threat

### ISSUE THREAD

**Issue by Kritzolina** [mozilla/global-sprint#183]
**[ Project Contact ]** @Kritzolina
**[ Github Repo ] <https://github.com/Kritzolina/Voices-under-Threat>** 
**[ Track ]** Privacy + Security, Digital Inclusion, Decentralization, 
**[ Location ]** Munich, GMT +1

### Description
Voices under Threat is a project run by the Support and Safety team at the Wikimedia Foundation. The project lead is Christel Steigenberger, also known as Kritzolina. Together with volunteers and helpers like you, we want to find, build and collect resources to help individual contributors and groups supporting open knowledge who face external risks and threats, because they share knowledge freely.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @Kritzolina 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by Kritzolina** [comment]
Done - I thought I did that a while ago, but apparently did not save the changes. Thanks for reminding me!
