### ISSUE TITLE
Open Sourcing DuraCloud: Beyond the License

### ISSUE THREAD

**Issue by erintripp** [mozilla/global-sprint#184]
**[ Project Contact ]** @erintripp
**[ GitHub Repo ]** https://github.com/duracloud/duracloud
**[ Track ]** Openness, Decentralization, 
**[ Location ]** Moncton, NB, Canada. ADT

### Description
DuraCloud, our successful digital preservation storage service, uses an open source license, but lacks the community contribution model that typically defines an open source project. Our Mozilla Open Leadership Training project aims to correct this by developing strategies and communication techniques to foster greater engagement and collaboration around digital preservation and the software used to ensure digital content remains accessible to everyone for the long term.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by erintripp** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by bbranan** [comment]
The [Github Repo] for this project can be updated to: https://github.com/duracloud/duracloud/blob/master/README.md

**Comment by abbycabs** [comment]
This is great! Featured: https://www.mozillapulse.org/entry/671 🎉 
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
