### ISSUE TITLE
Redeveloping a Rapid Prototyping Curriculum to be more open

### ISSUE THREAD

**Issue by manasvil** [mozilla/global-sprint#185]
**[ Project Contact ]** @manasvil
**[ GitHub Repo ]** https://github.com/manasvil/RapidPrototyping-Curriculum
**[ Track ]** Web Literacy, Openness, 
**[ Location ]** EST

### Description
This repository aims to open up a maker oriented course, originally offered  at Georgia Tech, which aims to provide basic technical efficacy to people who from a variety of backgrounds. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by manasvil** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by cmaumet** [comment]
Hey @manasvil! This looks good! I think there are two small remaining items before this is fully ready:  "create at least three issues to describe each task that you need help with and how a contributor can get started on that task" and "Create a label called mozsprint and apply it to your issues". 

The issues you define can be simple tasks, such as reviewing part of the material or the README or getting help transferring the files from Google drive, etc. 

Sorry I missed this yesterday when we worked on your submission! Let me know when this is done and I'll let Abby know that I have reviewed your submission :)

**Comment by cmaumet** [comment]
@acabunoc: Following your suggestion, I have reviewed @manasvi's project and confirm that she has completed all the tasks to get featured at #mozsprint 🎉

**Comment by abbycabs** [comment]
That's great!

One thing that before making Pulse submission live: @manasvil, do you have an image we can use for the entry? We find it helps a lot for drawing attention to your project. If you'd like to add an image, you can resubmit your project on Mozilla Pulse (and please add the `mozsprint` and `2018` tags this time!).

**Comment by manasvil** [comment]
Thanks for reviewing @cmaumet. @acabunoc how do i edit my entry? I can only see an option to edit my personal profile on Pulse.

Edit: I see you said resubmit, my bad. Will do.

**Comment by abbycabs** [comment]
Hi @manasvil! You'll have to resubmit (sorry for the extra work).

Edit: just saw your edit! :)

**Comment by manasvil** [comment]
Finished resubmitting! Thanks for following up.

**Comment by abbycabs** [comment]
Pulsed! https://www.mozillapulse.org/entry/659 🎉
