### ISSUE TITLE
Mission:Information Algorithm Lesson

### ISSUE THREAD

**Issue by secmorris** [mozilla/global-sprint#186]
**[ Project Contact ]** @secmorris
**[ GitHub Repo ]** https://github.com/nucleus-network/missioninfo
**[ Track ]** Web Literacy, 
**[ Location ]** Austin, TX Central Time 

### Description
I'm developing a computer-science focused lesson as part of a broader, Mozilla grant funded project called Mission:Information which is curriculum that helps teens strengthen their media and web literacy skills. I hope to spend the sprint working on this new CS lesson and hope to work with contributors, including educators or technologists who are inspired to build related tools. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by ottagit** [comment]
Hi @acabunoc I can see that this project already features on Mozilla Pulse. What happens in such a case? Thanks @secmorris

**Comment by abbycabs** [comment]
Hey Chris,

I don’t see this project on our featured projects page: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

I think you’re seeing an old listing on pulse. She still needs to complete the tasks listed to get featured for the 2018 Sprint.

**Comment by secmorris** [comment]
This is ready to be featured on Mozilla Pulse - thanks all, just completed all the tasks!

**Comment by ottagit** [comment]
Thanks @acabunoc for the clarification. I surely was seeing an old listing on pulse. Glad you're done @secmorris

**Comment by abbycabs** [comment]
Hey @secmorris do you have an image you'd like to use as the header in your pulse entry? Having a good image helps a lot of engagement on social :)

If so, can you resubmit your Pulse entry? And please add the `mozsprint` and `2018` tags in pulse!

**Comment by secmorris** [comment]
@acabunoc Resubmitted!

**Comment by abbycabs** [comment]
https://www.mozillapulse.org/entry/704 🎉  you're featured!
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
