### ISSUE TITLE
IGNITE

### ISSUE THREAD

**Issue by graciellehigino** [mozilla/global-sprint#189]
**[ Project Contact ]** @graciellehigino
**[ GitHub Repo ]** https://github.com/graciellehigino/IGNITE
**[ Track ]** Web Literacy, Openness, Decentralization, 
**[ Location ]** Brazil, UTC -03:00

### Description
Although we have amazing communicators doing their jobs in SciComm, we need scientists to help us in this mission. However, scientists are not trained to communicate their work to non-specialists (which can be really hard!), and they often think they can't do it. Because SciComm is an interdisciplinary field, why not gather people with different skills to build a fun, short, crowdsourced and reproducible SciComm workshop aimed at young scientists?
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by graciellehigino** [comment]
This is ready to be featured on Mozilla Pulse. ❤️ 🎉

**Comment by abbycabs** [comment]
Nice work! Featured: https://www.mozillapulse.org/entry/682 🎉 
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
