### ISSUE TITLE
Parkology: An Open Online Community for People Who Love Parks

### ISSUE THREAD

**Issue by garciajnatalie** [mozilla/global-sprint#190]
**[ Project Contact ]** @jeffreykeefer @garciajnatalie 
**[ GitHub Repo ]** https://github.com/jeffreykeefer/Parkology
**[ Track ]** Openness, Digital Inclusion, 
**[ Location ]** New York, New York; Eastern Standard Time

### Description
Parkology will help members of urban communities to share ideas, tools, and resources to be empowered to promote access to a quality park within a 10-minute walk from their homes. We hope to attract local community members across the United States who are passionate about improving access to and quality of green spaces in their neighborhoods. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by garciajnatalie** [comment]
#mozsprint #2018

**Comment by garciajnatalie** [comment]
@acabunoc, can you please add @jeffreykeefer as a participant to this? Thank you!

**Comment by garciajnatalie** [comment]
Also, @acabunoc just wondering how we can link this page to our site in tito, so that participants can make the connection between them. We'd like for this connection to be made prior to us submitting this to be a featured project. Thanks!

**Comment by abbycabs** [comment]
Hi @garciajnatalie! @jeffreykeefer is already tagged here! Sadly, only the person who create the issue can edit it, so I hope the two of you can work together to check off the items here :)

You should be able to edit your Ti.to page to add links to your project. Here are the Ti.to instructions:

* Click on the link in the email you received and create an account. 
* Once you’ve created an account, you should see a page that shows “All Upcoming Events. “ Your mozsprint listing should be there. Click on it.
* On the page related to your Event, you’ll see a “dashboard” of summary information and a left sidebar menu of actions, info, and options for your event.
* Select "Customize" > "Basics" and verify your contact information for the site
* Select "Customize" > "Location" to verify the site location/address and if needed edit the map
* Select "Customize" > "Homepage" to edit any site details on the event page, such as special hours or directions
* If needed, select “Tickets”  to edit the number of available tickets for your event.
* Under “Attendees”  you can see the list of people who have registered for your event
* Under “Messages” you can use the interface to send messages to attendees with any special instructions, updates, reminders, etc specific to your event

**Comment by jeffreykeefer** [comment]
This is ready to be featured on Mozilla Pulse.
@acabunoc @garciajnatalie

**Comment by abbycabs** [comment]
And you're featured!! 🎉 🎉 https://www.mozillapulse.org/entry/685

https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

**Comment by garciajnatalie** [comment]
@acabunoc Fantastic thank you! We'd love to know how to get higher placement on the featured page, are there additional steps we can take to do so? Additionally, if I send another image of our logo with a white background and centered, could we easily upload and change that?

**Comment by nyakwakah** [comment]
Super proud of your work so far ! @garciajnatalie @jeffreykeefer :grin:

**Comment by iamjessklein** [comment]
Hello all! I'd love to help out with this amazing project. I'm a ux/learning designer based in Brooklyn.

**Comment by jeffreykeefer** [comment]
Great; would love to have you take a look at the site or come on down and visit us here in Manhattan today @iamjessklein !

**Comment by iamjessklein** [comment]
@jeffreykeefer I'd love to do that. Where is the sprint happening? I can *try* to come but if that doesn't work out I can work remotely for the time being.  I'm  also @iamjessklein on twitter

**Comment by garciajnatalie** [comment]
We'd really appreciate your help! If you can not reach us onsite, you can
view our github repository here: https://github.com/jeffreykeefer/Parkology

We completed parkology without a lot of input from a designer, it would be
really great if you could let us know

what components of the site are easy to navigate
what improvements you can suggest
are the icons clear?
is it easy/ intuitive to get to your profile?
is it easy/ intuitive to understand the different components of parkology?
what improvements would you make to make it more intuitive/ user friendly?

**Comment by jeffreykeefer** [comment]
We are in NOHO https://ti.to/Mozilla/global-sprint-trust-for-public-land-new-york18 so you are welcome to join us or help online. We appreciate it @iamjessklein

**Comment by iamjessklein** [comment]
Is there a specific set of times that you are working at the site?

**Comment by jeffreykeefer** [comment]
We are monitoring the online site here all day, and are also welcoming sprinters here in #NYC all day today as well @iamjessklein!!

**Comment by garciajnatalie** [comment]
We'll be onsite until 5pm!

**Comment by iamjessklein** [comment]
do you have a slack or irc channel that I can join?

**Comment by jeffreykeefer** [comment]
We are somewhat monitoring the mozilla/global-sprint chat on Gitter, but do not really use Slack or IRC.

**Comment by iamjessklein** [comment]
I'm getting 404 errors for all of the links in the "What do we need" in the README. Do you have the website up on a staging site or something yet?

**Comment by jeffreykeefer** [comment]
Oh goodness!
You got a 404 Error at https://github.com/jeffreykeefer/Parkology/blob/master/README.md 
@iamjessklein

**Comment by garciajnatalie** [comment]
I just updated some of the links in the readme, they should all be working
now. You can also work directly on www.parkology.org

**Comment by iamjessklein** [comment]
I just refreshed and the links are working now (I'm sure this was just my error). Should I create a separate ticket somewhere to write design feedback?

**Comment by garciajnatalie** [comment]
Feel free to post them all here:
https://github.com/jeffreykeefer/Parkology/issues/17

**Comment by jeffreykeefer** [comment]
Phew; thanks!!
