### ISSUE TITLE
Coding the Mind: Advancing Global Wellbeing Through Open Digital Health

### ISSUE THREAD

**Issue by ktrang1** [mozilla/global-sprint#191]
**[ Project Contact ]** @ktrang1
**[ GitHub Repo ]** https://github.com/ktrang1/coding-the-mind
**[ Track ]** Openness, Digital Inclusion, 
**[ Location ]** Hanoi, Vietnam (ICT)

### Description
Given the explosion of knowledge about psychiatric disorders, our workshop and online platform (codingthemind.org) will delineate how a cognitive sciences and neuroscience approach can inform the selection, operationalization, and design of digital health technology to intervene in processes hindering wellbeing worldwide. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @ktrang1 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by abbycabs** [comment]
Hi @ktrang1 please add the 'mozsprint' label to some of your issues - the Sprint has started!
