### ISSUE TITLE
(Oregon) Nonprofit Index

### ISSUE THREAD

**Issue by walecain** [mozilla/global-sprint#193]
**[ Project Contact ]** @walecain
**[ GitHub Repo ]** https://github.com/walecain/nonprofit-index
**[ Track ]** Digital Inclusion, 
**[ Location ]** Eugene, Oregon / PST

### Description
This is the nonprofit index project. Starting with Oregon, the purpose of this index is create a usable database of nonprofit organizations around the world and provide critical information about these organizations.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by walecain** [comment]
This is ready to be featured on Mozilla Pulse.

**Comment by abbycabs** [comment]
Hi @walecain! I'm having trouble finding your project on Pulse. Did you complete all the instructions here? https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/ would love to feature your work!

**Comment by abbycabs** [comment]
Hey @walecain 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)
