### ISSUE TITLE
Observed.City

### ISSUE THREAD

**Issue by fionacu** [mozilla/global-sprint#194]
**[ Project Contact ]** @fionacu
**[ GitHub Repo ]** https://github.com/fionacu/kickstart-the-city
**[ Track ]** Web Literacy, Privacy + Security, Digital Inclusion, Decentralization, 
**[ Location ]** Birmingham, UK – GMT

### Description
Observed.City is Birmingham UK’s first email newsletter covering data privacy, art, tech and activism. It will connect activity and engage new audiences in an easy and direct way, and aims to make data privacy more accessible, engaging and FUN!
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by fionacu** [comment]
This is ready to be featured on Mozilla Pulse (I think!)

**Comment by princiya** [comment]
@fionacu This looks brilliant. I like your initiative and good luck 👍 

@acabunoc This is good to go!

**Comment by abbycabs** [comment]
You're on pulse! https://www.mozillapulse.org/entry/644 🎉

**Comment by fionacu** [comment]
Thank you! This has made my day. Might reward myself with a 🍪. 😜

**Comment by princiya** [comment]
@fionacu & @vyaspranjal33 Connecting you two here :) Your projects look similar, but from different geography. Let's talk about possible collaborations.

cc @Veerskyfire @acabunoc

**Comment by alljames** [comment]
Bostin! I'm keen to chip in :grinning:

**Comment by fionacu** [comment]
@alljames Hello Aled - and thank you. Bostin bab!
