### ISSUE TITLE
ContextExplorer: Facilitate microscope image analysis of cells

### ISSUE THREAD

**Issue by joelostblom** [mozilla/global-sprint#195]
**[ Project Contact ]** @joelostblom
**[ GitHub Repo ]** https://gitlab.com/stemcellbioengineering/context-explorer
**[ Track ]** Openness, 
**[ Location ]** Toronto, Canada, UTC-04:00

### Description
ContextExplorer is a software program that facilitates analyses of data extracted from microscope images of cells. The analyses methods in  ContextExplorer focus on how populations of cells are affected by their microenvironment, including local variations in cell signaling and cell density.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
hey @joelostblom! so glad you're using gitlab!
We'll be visualzing github data during the sprint (sadly we don't have gitlab support for the data viz). do you have a github repo for this work? Let me know :)

**Comment by joelostblom** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by joelostblom** [comment]
@acabunoc Yes, GitLab is really cool! I like that they are a community effort and support openness throughout their platform =)

 Unfortunately I don't have a GitHub repo for this. I could create one, but I am not sure it is meaningful since the development will be happening at GitLab, so you would not get any data about contributions etc from a potential GitHub repo. Let me know what you think.

**Comment by abbycabs** [comment]
Featured on pulse: https://www.mozillapulse.org/entry/779
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

🎉 happy sprinting! 🎉
