### ISSUE TITLE
Translating open agricultural research to local language 

### ISSUE THREAD

**Issue by solomon3m** [mozilla/global-sprint#197]
**[ Project Contact ]** @solomon3m
**[ GitHub Repo ]**  https://github.com/agritrans/agritrans.github.io
**[ Track ]** Openness, Digital Inclusion, 
**[ Location ]** Addis Ababa, Ethiopia GMT+3

### Description
The project proposes to translate open research outputs in agriculture into local languages like Amharic, and to communicate scientific terms in plain language that farmers can understand. The translations will be openly available to farmers and the general public using an online platform to facilitate citizen engagement in open science, including data collection and data analysis, with the expectation that citizen involvement will increase agricultural productivity.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by GienSRG** [comment]
I'm interested.

**Comment by agritrans** [comment]
@GienSRG , Thank you very much for your interest to work with us. You are warmly welcome to join this project. I hope u will join us during global sprint.

**Comment by abbycabs** [comment]
Hey @solomon3m & @agritrans 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by solomon3m** [comment]
Thanks @acabunoc , I have completed the checklist and also applied to be featured on Mozilla Pulse.

**Comment by abbycabs** [comment]
Hi @solomon3m I left one issue in your repo: https://github.com/agritrans/agritrans.github.io/issues/10

Other than that, this looks good to go!
Pulse: https://www.mozillapulse.org/entry/790 🎉 
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
