### ISSUE TITLE
Open Online Study Group (OOSG)

### ISSUE THREAD

**Issue by iceLearn** [mozilla/global-sprint#199]
**[ Project Contact ]** @iceLearn
**[ GitHub Repo ]** https://github.com/iceLearn/Open-Online-Study-Group-OOSG
**[ Track ]** Web Literacy, Openness, Decentralization, 
**[ Location ]** Colombo, Sri Lanka IST time zone and PDT Palo Alto California USA
![app co](https://user-images.githubusercontent.com/12571844/38247853-3c68ea22-3764-11e8-8545-aa000fae183a.png)

### Description
Have you taken any (Massive) Open Online Course MOOCs? In such platforms  i,e Coursera, edX, FutureLearn etc.. learners are information consumers. The learning platforms are decentralized to learn but suppressed the interaction and collaboration between  learners. Learning experience in these platforms isolated learners, yet learners better learn while learning together. 

![how to join](https://user-images.githubusercontent.com/12571844/38206305-8a0f798c-36c7-11e8-8bc3-007d6ed59025.png)

This project we will build a open online learning community platform and grow the community to learn with each other. 
![how to join 1](https://user-images.githubusercontent.com/12571844/38206298-81c0e66c-36c7-11e8-912c-1bdbb8e12e6c.png)

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by iceLearn** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Excellent work! You're featured: https://www.mozillapulse.org/entry/650 🎉 
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

**Comment by chized** [comment]
Hi, we want to join this project from our site in Nigeria. How can we join?

**Comment by msharafjr** [comment]
Hi I'm Mohamed and I'd love to help out on this project!

**Comment by deHasara** [comment]
@chized  @msharafjr You can see some open issues interest to you
https://github.com/iceLearn/Open-Online-Study-Group-OOSG
Also you can join our slack channel in order to get to know the project and ask questions from the community.
https://gitter.im/Open-Learn-Research/openLearnResearch
