### ISSUE TITLE
Aerogami: Learning How Things Fly by Making Paper Planes

### ISSUE THREAD

**Issue by kshitizkhanal7** [mozilla/global-sprint#20]
**[ Project Contact ]** @kshitizkhanal7
**[ GitHub Repo ]** https://github.com/kshitizkhanal7/Aerogami
**[ Track ]** Open Innovation, Digital Inclusion
**[ Community ]** Mozilla Science
**[ Location ]** Kathmandu (GMT + 5.75)
### Description
This project is an open educational practice. It aims to teach participants how things fly using simple English words, the most basic of understandings about how things work, and playing in real world (by making paper planes) and virtual world (an interactive graphical web application).
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @kshitizkhanal7! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by kshitizkhanal7** [comment]
Ticked some boxes in the checklist

**Comment by chadsansing** [comment]
Hi, @kshitizkhanal7! Do you think this project addresses one track more than the others?

**Comment by kshitizkhanal7** [comment]
@chadsansing I think it addresses Digital Inclusion more than the other two.

**Comment by stephwright** [comment]
Hey there @kshitizkhanal7!  I saw you closed this issue... was wondering if you were still planning on leading this for the Global Sprint.

**Comment by kshitizkhanal7** [comment]
I think I misunderstood what closing the issue meant.

**Comment by stephwright** [comment]
No worries! We keep all the project issues open in this repo as a list of the available projects for folks to contribute to in the Global Sprint.  It doesn't really make that clear anywhere here, though does it? 

Glad to see you're still planning on joining us! 👏

**Comment by kshitizkhanal7** [comment]
![aerogami](https://cloud.githubusercontent.com/assets/3065858/25644829/af699d22-2fc8-11e7-94d0-f7edb3ce3e25.jpg)

**Comment by kshitizkhanal7** [comment]
This is ready for Mozilla-Pulse

**Comment by kshitizkhanal7** [comment]
Do I close the issue or leave comment to a community wrangler? @stephwright @acabunoc @chadsansing ?

**Comment by stephwright** [comment]
Sorry @kshitizkhanal7 ... I was traveling for the last several days.  This has been Pulsed! https://www.mozillapulse.org/entry/255  
Leave the issue open as this is maintained as a list of Sprint projects for sprint participants to look at and decide where to jump in.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
