### ISSUE TITLE
Sentencing By Numbers

### ISSUE THREAD

**Issue by fourthletter** [mozilla/global-sprint#200]
**[ Project Contact ]** @fourthletter
**[ GitHub Repo ]** https://github.com/fourthletter/SentencingByNumber
**[ Track ]** Privacy + Security, 
**[ Location ]** New York City EST

### Description
My proposed project will help communities promote more transparent and accountable algorithms used for surveillance. Communities should have a right to dismantle these “black boxes” and evaluate whether these tools are perpetuating biases and undermining human rights. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by fourthletter** [comment]
This is ready to be featured on Mozilla Pulse! Thank you, Abby!

**Comment by abbycabs** [comment]
Hey @fourthletter!

Thanks for submitting your project to pulse! We're still missing a few things from the checklist: 
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.
* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [ ] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
