### ISSUE TITLE
Viva Las Venus

### ISSUE THREAD

**Issue by cyb3113** [mozilla/global-sprint#204]
**[ Project Contact ]** @VivaLasVenus
**[ GitHub Repo ]** https://github.com/VivaLasVenus/VivaLasVenus
**[ Track ]** Web Literacy, Internet Privacy, 
**[ Location ]** UTC−3  - Sao Paulo - Brazil 

### Description
Mostly of our lives are online, but in times of excessive mass surveillance, data collection, harassment, doxxing, cyber bullying, net neutrality in danger, it becomes more than necessary to know how to protect yourself and the loved ones through learning about privacy and security in digital media. Viva Las Venus is a long term project that the main focus is to aware and teach mostly but not exclusvely, women- cis and trans - through workshops, debates, talks, in person and online. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by cyb3113** [comment]
This is ready to be featured on Mozilla Pulse :purple_heart:

**Comment by abbycabs** [comment]
https://www.mozillapulse.org/entry/668 🎉
