### ISSUE TITLE
We Are All Connected 

### ISSUE THREAD

**Issue by EducationalVideoCenter** [mozilla/global-sprint#205]
**[ Project Contact ]** @educationalvideocenter
**[ GitHub Repo ]** https://github.com/EducationalVideoCenter/WAC
**[ Track ]** Openness, Digital Inclusion, 
**[ Location ]** New York, NY / EST

### Description
The We are All Connected open educational resource site works to bridge urban/rural and digital divides. This digital media curriculum fosters dialogues among rural/urban youth, addresses project challenges in rural areas, embodies social justice/digital equity values & best practices of urban & place-based rural pedagogies. This model of digital media teaching/learning is to be shared and contributed to by organizations and youth media educators/practitioners from communities around the world.

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @EducationalVideoCenter 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by EducationalVideoCenter** [comment]
Hey Abby! The 6 items on the checklist are complete. Let us know if there's anything else we need to do!
