### ISSUE TITLE
Night Vision Data

### ISSUE THREAD

**Issue by agharsallah** [mozilla/global-sprint#206]
**[ Project Contact ]** @hunter-x
**[ GitHub Repo ]** https://github.com/hunter-x/night-vision-data
**[ Track ]** Openness, 
**[ Location ]** Tunisia, UTC + 1
**[ Coach ]** @chadsansing 

### Description
 Night Vision Data is a web app that will mostly work with Governments data to make informations more Open and Presentable  to citizens and society so that they can clearly understand what’s happening under the hood.

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by chadsansing** [comment]
Hi, @hunter-x. Let me know how to be of help and please let me know me when you are ready for a review.

**Comment by abbycabs** [comment]
Hey @hunter-x 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)
