### ISSUE TITLE
GirlsGetGeeky

### ISSUE THREAD

**Issue by cesswairimu** [mozilla/global-sprint#207]
**[ Project Contact ]** @cesswairimu , @StlMaris123
**[ GitHub Repo ]** https://github.com/cesswairimu/GirlsGetGeeky
**[ Track ]** Openness, 
**[ Location ]** Nairobi, Kenya. Eastern Africa Time (EAT)
**[ Coach ]** @annakrystalli

### Description
Build a fun offline course available on usb sticks and at the same time help others learn/get started with a programming language based on what worked for others.The off-line course should have important resources that one needs to effectively learn the programming language in question. We will begin with Ruby on Rails then later add more languages. This project will give people in areas with poor internet connection a chance to learn programing with less hassle. 

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by cesswairimu** [comment]
This is ready to be featured on Mozilla Pulse. @acabunoc

**Comment by cesswairimu** [comment]
@acabunoc I just realized I forgot to add an image how can I edit pulse submission? I tried looking around the buttons but no avail. Thanks

**Comment by abbycabs** [comment]
HI @cesswairimu! Please resubmit with an image :)

**Comment by cesswairimu** [comment]
@acabunoc I have submitted another one please take a look. Thanks

**Comment by abbycabs** [comment]
This is great! I made a PR to update the year: https://github.com/cesswairimu/GirlsGetGeeky/pull/12

But otherwise, this is ready for pulse! https://www.mozillapulse.org/entry/775
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

🎉 happy sprinting! 🎉
