### ISSUE TITLE
Crowd2Map Tanzania - using OpenStreetMap to help protect girls from FGM and to empower communities in rural Tanzania

### ISSUE THREAD

**Issue by janetchapman** [mozilla/global-sprint#208]
**[ Project Contact ]** @jachapman82
**[ GitHub Repo ]** https://github.com/janetchapman/contribute-Crowd2Map
**[ Track ]** Web Literacy, Openness, Digital Inclusion, 
**[ Location ]** London UK UTC+1
**[ Coach ]** Your OL5 Mentor

### Description
Since Crowd2Map launched at Mozfest2015, we have been adding schools, hospitals, roads, buildings and villages to OpenStreetMap, an open source map available to all, with the help of over 5000 volunteers worldwide and 600 on the ground in Tanzania. With minimal budget and no staff we have so far added over 2.1 million buildings and trained community mappers in 23 areas of Tanzania.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by acabunoc** [comment]
Hey @janetchapman -- sorry your checklist got cut off! I updated your issue so you can see the rest of the tasks for a featured project :)

**Comment by janetchapman** [comment]
Thanks!

**Comment by acabunoc** [comment]
You're on pulse!

**Comment by bunnybooboo** [comment]
Adding Mozilla Pulse link for greater discoverability https://www.mozillapulse.org/entry/679
