### ISSUE TITLE
#M4Labs

### ISSUE THREAD

**Issue by virbrussa** [mozilla/global-sprint#212]
**[ Project Contact ]** Virginia Brussa @virbrussa
**[ GitHub Repo ]** https://github.com/virbrussa/M4Labs/
**[ Track ]** Web Literacy, Openness, 
**[ Location ]** Rosario, Argentina (UTC -3 )

### Description
The project aims to collect digital resources related to the methodologies used by global labs for innovation. The main goal of M4labs is to systematize the methodologies  and identify possible links between education, science and open data movements. 
M4lab will be carried out a Met-a-thon  + talks ( virtual) + workshop ( local meeting) at the Global Sprint .
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by virbrussa** [comment]
`This is ready to be featured on Mozilla Pulse`

**Comment by abbycabs** [comment]
This is great!
Featured on pulse:
https://www.mozillapulse.org/entry/758
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

🎉 happy sprinting! 🎉
