### ISSUE TITLE
ME-BIDS

### ISSUE THREAD

**Issue by emdupre** [mozilla/global-sprint#213]
**[ Project Contact ]** @emdupre
**[ GitHub Repo ]** https://github.com/ME-ICA/tedana
**[ Track ]** Openness, 
**[ Location ]** Montreal, QC, CAN - Eastern time
**[ Coach ]** @KirstieJane

### Description
Functional magnetic resonance imaging (fMRI) is a widely used tool providing a non-invasive, high-resolution index of brain activity. Recently, the Brain Imaging Data Structure (BIDS) was introduced to standardize fMRI data sets, enabling data discovery and—through associated BIDS Apps—analysis. A remaining challenge of fMRI data is its sensitivity to artifacts. Multi-echo analysis (Kundu et al., 2011, NeuroImage) was developed to address this; however, no multi-echo BIDS App currently exists. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by emdupre** [comment]
This is ready to be featured on Mozilla Pulse !

**Comment by abbycabs** [comment]
Nice work!

Pulse:
https://www.mozillapulse.org/entry/797
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

happy sprinting! 🎉
