### ISSUE TITLE
Live Whiteboard

### ISSUE THREAD

**Issue by apoorvaagupta** [mozilla/global-sprint#214]
**[ Project Contact ]** @apoorvaagupta, @bhavyaagg
**[ GitHub Repo ]** https://github.com/coslos/LiveWhiteboard-App ; https://github.com/coslos/LiveWhiteboard-Website 
**[ Track ]** Web Literacy, Openness, Digital Inclusion, Decentralization, 
**[ Location ]** Location: Delhi, India | Timezone: UTC+05:30 

### Description
Internet has replaced almost everything but conventional teaching methods.Though there are many online resources but they lack one to one interaction of teacher and students. Live Whiteboard app/website is a solution for them to connect with everyone and write/discuss/scribble their ideas.The main goal is to help distance learning students to get the blackboard teaching experience.Also, people can collaborate on remote projects to discuss the ideas graphically or just to scribble their thoughts!
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by apoorvaagupta** [comment]
Github Repositories for Work:
https://github.com/coslos/LiveWhiteboard-Website
https://github.com/coslos/LiveWhiteboard-App

**Comment by bhavyaagg** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by bhavyaagg** [comment]
@acabunoc We have completed the checklist.

**Comment by zee-moz** [comment]
Hi, on both of the repos I get a 404 error when I try to link to Contributing Guidelines-- it still says "will be added/updated soon."  Please update these links! 😄 
LiveWhiteBoard app also does not have any open issues-- could you add some for the Sprint? 

Let me know when you've done this, and I'll add to Pulse.

**Comment by abbycabs** [comment]
Hey @apoorvaagupta @bhavyaagg 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by yayimadinosaur** [comment]
im interested!

**Comment by bhavyaagg** [comment]
@acabunoc @zee-moz I will just complete the last steps. Thank you for informing.

**Comment by bhavyaagg** [comment]
@acabunoc @zee-moz I have checked the contributing file. Both the projects have contributing.md now whereas the contributors.md will be updated later which will contain the info about the users who contributed to the project. Thank you

**Comment by bhavyaagg** [comment]
@yayimadinosaur Thank you for showing interest. You can start with the contributing file and try to build the project locally.

**Comment by bhavyaagg** [comment]
@zee-moz @acabunoc I have added issues as well. Do we need to submit this again(the form)?

**Comment by abbycabs** [comment]
Pulsed! https://www.mozillapulse.org/entry/773 🎉 
Featured page: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
