### ISSUE TITLE
Reading for Gender Bias

### ISSUE THREAD

**Issue by molliem** [mozilla/global-sprint#216]
**[ Project Contact ]** @molliem
**[ GitHub Repo ]** https://github.com/molliem/gender-bias
**[ Track ]** Digital Inclusion, 
**[ Location ]** Portland, OR

### Description
Implicit gender bias in evaluations negatively impacts women at every stage of their career. The goal of this project is to create a web-based text-mining tool that scans and reveals language bias associated with evaluations and letters of recommendation written for trainees and applicants. Bringing awareness to the existence of implicit bias may impact how evaluations for women are drafted and judged, thereby providing a concrete way to tackle gender disparities.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by molliem** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Nice work on your repo!
Pulse: https://www.mozillapulse.org/entry/807
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

🎉 happy sprinting! 🎉

**Comment by molliem** [comment]
Thanks so much!!!! It’s my first repo.  I was worried about it. 

:)

mollie

**Comment by cmd16** [comment]
I am interested in contributing to this

**Comment by Enddyscholar** [comment]
I am interested.

**Comment by molliem** [comment]
Wonderful!  I've tried to divide the issues into pieces that can be tackled with a single script.  I could use help with web design, coding (using Python), and documentation.  I'm on the Sprint gitter channel and on [slack](https://join.slack.com/t/readingforbias/shared_invite/enQtMzU2Mzk2MjY2NDA2LTI1MzNjYzVjYWJlZWNjNDEwNjJkYWI1ZGVlYTZhNWM1YzIzOTAyM2E0MjZlMGM3YzVmZmM5MjJjNThlMDc2NzY), so feel free to reach out with questions. Thanks for your interest!
