### ISSUE TITLE
StoryEngine

### ISSUE THREAD

**Issue by ankuhl** [mozilla/global-sprint#217]
**[ Project Contact ]** @ankuhl @prefontaine
**[ GitHub Repo ]** https://github.com/LoupDesign/StoryEngine
**[ Track ]** Openness, 
**[ Location ]** Washington, DC, Eastern Standard Time
**[ Coach ]** Your OL5 Mentor

### Description
StoryEngine is a way to do research and evaluation for any organization who wants to listen to the people that matter most to them. StoryEngine uses interviews to draft stories that are then edited with each participant. These stories can then be used for marketing, communications, advocacy, and more — while forming a dataset that can be used to surface insights and learning.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by ankuhl** [comment]
This is ready to be featured on Mozilla Pulse! @acabunoc Thank you!

**Comment by zee-moz** [comment]
Great work-- your project has been featured: https://www.mozillapulse.org/entry/786 😸

**Comment by prefontaine** [comment]
Awesome! Thanks @zee-moz ... any way we can do some small copyedits to the entry?

**Comment by zee-moz** [comment]
I would have to do them manually, in the Pulse back end. Let me know if you want me to do that.

**Comment by prefontaine** [comment]
That would be awesome. Limit 300 words?

**Comment by zee-moz** [comment]
Christine,
Maybe it's easiest if you just submit a second Pulse listing--just email me
once you submit,  and I can approve and delete the old one. The link is
here: https://www.mozillapulse.org/add

Best,
Zannah

**Comment by prefontaine** [comment]
Thanks! Working on that now.

**Comment by prefontaine** [comment]
@zee-moz Re-submitted. I could not add more tags because there was a glitch in the form. I don't need to change that... just an FYI. Thank you!

**Comment by jamezylong** [comment]
i want scholarship

**Comment by prefontaine** [comment]
Oh @zee-moz I also just noticed there is a duplicate entry from a year ago. https://www.mozillapulse.org/search?keyword=storyengine

**Comment by zee-moz** [comment]
Hi Christine, I approved your new listing: https://www.mozillapulse.org/entry/822
And I've removed the older one-- does that work?

**Comment by prefontaine** [comment]
Thank you! Yes. Works awesome.
