### ISSUE TITLE
HorseGeneAnnotation

### ISSUE THREAD

**Issue by schae234** [mozilla/global-sprint#218]
**[ Project Contact ]** @schae234
**[ GitHub Repo ]** https://github.com/UMN-EGGL/HorseGeneAnnotation
**[ Track ]** Openness, 
**[ Location ]** St Paul, MN (CST)
**[ Coach ]** @tpoisot

### Description
HorseGeneAnnotation is a manually-curated, crowd-sourced gene annotation website for the horse. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by tpoisot** [comment]
Hi @schae234 -- do you need some help getting started with the README or with picking a license?

**Comment by schae234** [comment]
Hey @tpoisot 

Thanks for the ping, when I registered, I dropped in this repository specifically for the global sprint do to a bunch of haphazard organization around the other projects going on right now on LinkageIO. Ill dedicate some time to organizing some tasks and creating a README/Roadmap for the sprint. It'll all be CC-BY/MIT which makes it easy!

**Comment by tpoisot** [comment]
Perfect -- let me know if/how I can help or advise!

**Comment by schae234** [comment]
hi @tpoisot and @acabunoc 
So I was talking with some other members of my lab about the global sprint and something amazing happened. We've been tossing around this idea for a while now about a project and it occurred to me that it would be **perfect** for the global sprint. Being that my submitted project is very high level, I was wondering if it would be cool with you guys if we swapped this out and took a swing at something new. 

The lab I'm in studies horse genetics. Being a non-model species, we have somewhat limited resources. One of our problems is that our reference genome has lots of errors in it. We currently have a tutorial in our lab on how to manually, hand-annotate the horse genome. The process involves pulling down data from some government databases and comparing the gene sequences by hand between the horse and human (and sometimes other species). We are currently developing a website that will interface the gov website and pull down the necessary data so that that user only has to worry about performing the tasks that annotate the gene errors. The target here is university level students and non-experts. We envision this website being used by genetics classes and veterinary programs to help students learn about genetics and to also crowd source manual annotation efforts.

### We want to sprint on this!!!!!! :running_man: :running_woman: :athletic_shoe: :medal_sports:  
I've already got two other students in my lab on board and I really think this is a project that would have general interest.

We plan on migrating all of our materials in the next few days to github anyways, but I think we can have a prototype ready for the global sprint. Is this ok with you guys?

**Comment by abbycabs** [comment]
@schae234 for sure -- swap away!

**Comment by schae234** [comment]
![hype train](https://media.giphy.com/media/cMq7gwTNX4jTO/giphy.gif)

**Comment by schae234** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by schae234** [comment]
Hey @tpoisot  and @acabunoc Anything else I need to do on this Issue? I'm really excited for next week!

**Comment by schae234** [comment]
Hey @tpoisot is there still time to review this so it can be featured on Pulse?

**Comment by tpoisot** [comment]
:heavy_check_mark: 

![screenshot from 2018-05-08 13-15-29](https://user-images.githubusercontent.com/579329/39772092-3dc1b61e-52c2-11e8-8bc3-2a9cf1e7d7ae.png)

:tada:

**Comment by schae234** [comment]
Thank you!!!

**Comment by loisaidasam** [comment]
Stumbled across this project via the global sprint and would love to get involved somewhere down the line - very cool!

**Comment by schae234** [comment]
Hi @loisaidasam! Thanks for the shout out, it'd be great to have you involved. We are trying to keep our development process updated in the github page, so whenever you want to drop by, check out what we are working on [here](https://github.com/UMN-EGGL/HorseGeneAnnotation/issues)
