### ISSUE TITLE
Open Funders Canada

### ISSUE THREAD

**Issue by lesliePhD** [mozilla/global-sprint#22]
**[ Project Contact ]** @lesliePhD
**[ GitHub Repo ]** https://github.com/lesliePhD/open_funders_canada
**[ Track ]** Open Innovation, Digital Inclusion
**[ Community ]** Internet Policy & Advocacy - wrangler: @Melechuga 
**[ Location ]** Montreal, Quebec, Canada EST
### Description
We are creating an open tool to help find out who is funding who, for what, and when over time.  Bonus is that it creates open data as a result. This will help both funders and nonprofits do their work more effectively.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @lesliePhD! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @vanessarhinesmith. We're here to help you through this process.

**Comment by chadsansing** [comment]
Very cool, @lesliePhD - let me know how to be of help.

**Comment by lesliePhD** [comment]
Thanks @chadsansing!  

Just still getting my project set up on Github (I'm new to it).  We have a pilot already, but just trying to get feedback and more funders in there.   In general looking for: 

- UX feedback from nonprofits and funders

- some design help on our pilot to respond to the feedback

- someone or many ppl to teach me and help scrape data from websites

I am sure I will think of more as I get the project set up.

**Comment by chadsansing** [comment]
@lesliePhD - that's very helpful! We'll have to make sure you connect with Hive TO to see if you can data share re: funders.

**Comment by lesliePhD** [comment]
Here is my very unpopulated repo - stay tuned for more!
https://github.com/lesliePhD/open_funders_canada

**Comment by lesliePhD** [comment]
Landsli...I mean Landscape!. 
![landslide_i_mean_landscape](https://cloud.githubusercontent.com/assets/26332336/25398776/2703b020-29bb-11e7-9adf-4c46b0151c36.jpg)

**Comment by lesliePhD** [comment]
This is ready for Mozilla Pulse.

**Comment by chadsansing** [comment]
@lesliePhD - is your image set? For Pulse, the best images are about 1200 x 630, landscape. Also...

- Your README and roadmap cover a lot of the same ground. You might be able just to list your milestones in your roadmap doc.
- Your CONTRIBUTING file is empty - do you want to copy your "How to Get Involved" section there?
- The contributor guidelines you cite are Mozilla's Community Participation Guidelines, which are largely about how we treat one another. Are there any particular technical or procedural steps you want contributors to follow in their workflow for the project? If so, those could go into the CONTRIBUTING doc, as well.

Do those questions make sense? Let me know what you think and decide. It's shaping up great!

**Comment by lesliePhD** [comment]
@chadsansing 
1. I can find a new photo...i really didn't have any ideas for a photo.  
2. README - I find most of my documents cover the same ground, so maybe I just have too little content.  But I can lighten them if you think its best.  
3.  Contributing file now has content.  redundant probably.  
4. I don't have any technical desire for contributing just now.  Any suggestions?

**Comment by chadsansing** [comment]
@lesliePhD - sounds good. Maybe an [open-source](http://search.creativecommons.org/) landscape photo of someplace iconic in Canada?

I think the copy works - just wanted to make sure you didn't feel like you had to include more than you wanted in each section.

Let's go to Pulse once we have an image that fits :)

**Comment by lesliePhD** [comment]
@chadsansing 

how about a screenshot of our tool?  Size should be good.  

![screen shot 2017-04-25 at 2 14 54 pm 2](https://cloud.githubusercontent.com/assets/26332336/25400794/b13ea6f4-29c1-11e7-8998-236cf37b2d98.png)

**Comment by chadsansing** [comment]
Perfect. Will put this on Pulse later today or first thing tomorrow.

**Comment by lesliePhD** [comment]
Great!  Thanks! Phew - got it done!

**Comment by chadsansing** [comment]
😄

**Comment by chadsansing** [comment]
Pulsed!

https://www.mozillapulse.org/entry/245

**Comment by Melechuga** [comment]
Hi @lesliePhD,
Very cool! Do you have some more details about the backend tools that potential contributors could build on? Is the repo for the data set open and accessible? Thanks!

**Comment by lesliePhD** [comment]
Hi @Melechuga 
Thanks for your note.  I am trying to figure that out right now - we used import.io as a paid subscription to scrape data and I am in the process (or intend to) of learning how to use it and set up a template spreadsheet to export the information to.  I haven't had a chance to look at our account yet, but I would like that template to be accessible in time for the global sprint as I would like to work on it - I think ppl could use whatever tool they like, as long as there is a template of the data required, correct?

**Comment by stephwright** [comment]
Hi @lesliePhD ... how's it going with figuring out the backend?  Do you have a few more actionable tasks you can add to your issues for folks to dive in on during the Global Sprint?

**Comment by lesliePhD** [comment]
@stephwright  still working on it - haven't had a chance to do it, but I want to pull out the fields template to give ppl more guidance.  Its on my list for the next two weeks.  I need to set aside a couple hours next week for it.  thanks for checking in.

**Comment by stephwright** [comment]
Sure thing! 👍

**Comment by DennisDaddy** [comment]
Great project count me there

**Comment by lesliePhD** [comment]
@DennisDaddy sent you some messages at your twitter too - check out the project repo here: https://github.com/lesliePhD/open_funders_canada.  Easier to chat there or on twitter.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
