### ISSUE TITLE
Beyond Activismo

### ISSUE THREAD

**Issue by Beyondactivismo** [mozilla/global-sprint#220]
**[ Project Contact ]** @beyondactivismo
**[ GitHub Repo ]** https://github.com/Beyondactivismo/Beyondactivismo
**[ Track ]** Openness, Inclusion, Decentralization, 
**[ Location ]** Berlin, Central Europe
**[ Mentor ]** @cameralibre
![captura de pantalla 2018-04-14 a las 5 36 52 p m](https://user-images.githubusercontent.com/32823481/38769888-7f244cea-400a-11e8-80a7-293dc415c086.png) 
### Description
Beyond Activismo is an open project that tries to connect and share the stories and experiences of human rights activists, in a multilingual platform in an attractive and creative way.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Mozilla Global Sprint](http://mozilla.github.io/global-sprint/) May 10-11, 2018! We'll be gathering in-site in the [Mozilla Berlin Office](https://www.google.com/maps?q=52.4995,13.4493+Mozilla+Berlin,+Building+3,+3rd+floor,+Schlesische+Stra%C3%9Fe+27,+Berlin,+Germany) and online to collaborate on this project and learn from each other.

If you're interested in contributing to this project during #mozsprint 2018 please let us a comment here. 

If you want to know more about Beyond Activismo you can visit us [here](https://github.com/Beyondactivismo/Beyondactivismo/edit/master/README.md). :tada:

If you want to know who is behind Beyond Activismo please come by and say hi [here](https://github.com/Beyondactivismo/Beyondactivismo/issues/46)! 😃

**Comment by Beyondactivismo** [comment]
Hi @acabunoc  and @zee-moz  this is ready to be featured on Mozilla Pulse 😃

**Comment by zee-moz** [comment]
@Beyondactivismo great work 😸! Your project is now on Pulse! https://www.mozillapulse.org/entry/778

**Comment by dannyrayman** [comment]
Hi @zee-moz ! Thanks you very much!  Why our issue is different now? The information is not acording to us in this issue.

**Comment by zee-moz** [comment]
@dannyrayman ah- I was deleting the checklists from the issue as you'd completed them, and there must have been a copy-paste error-- is it fixed now?

**Comment by dannyrayman** [comment]
Ah ok, is not like before but don't worry I will rewrite it. Thanks for all @zee-moz !

**Comment by zee-moz** [comment]
apologies-- I replaced the text with what we received in your registration
form :(
it's such a great project-- looking forward to your sprint!

**Comment by dannyrayman** [comment]
Please don't apologies is everything ok! Thanks again for your work @zee-moz !
