### ISSUE TITLE
Open Advocacy

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/global-sprint#221]
**[ Project Contact ]** @ranjithrajv
**[ GitHub Repo ]** https://github.com/ranjithrajv/open-advocacy
**[ Track ]** Openness, Internet Privacy, 
**[ Location ]** Hyderabad, India and IST
**[ Coach ]** Your OL5 Mentor

### Description
Open Advocacy is a collection of Open Source Advocacy tools/services, exciting part is all these are secure. Advocacy is a essential part of socities and so does Internet, in this era of data tracking, mass-surveillance and unethical attempts of monetization of advocacy platforms, this project will be a very needed resource to provide free, accessible, open-source, privacy secured apps/services at one place.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @ranjithrajv 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by abbycabs** [comment]
@ranjithrajv please add the `mozsprint` label to some issues -- the Sprint has started!

**Comment by ranjithrajv** [comment]
@acabunoc adding, thanks.

**Comment by abbycabs** [comment]
https://github.com/ranjithrajv/open-advocacy/issues ?
