### ISSUE TITLE
Learn by Teaching - Rust

### ISSUE THREAD

**Issue by nomadicmehul** [mozilla/global-sprint#222]
**[ Project Contact ]** @rowdymehul
**[ GitHub Repo ]** https://github.com/rowdymehul/Learn-By-Teaching-Rust
**[ Track ]** Openness, 
**[ Location ]** India and IST Time
**[ Coach ]** @gilbertslade

### Description
We will derive an overview on how you can find interested people and get a learning group together to grow and keep your local community. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by nomadicmehul** [comment]
This is ready to be featured on Mozilla Pulse.  @gilbertslade @acabunoc

**Comment by abbycabs** [comment]
Hi @rowdymehul I can't find your submission to Pulse

**Comment by passcarlean** [comment]
interested

**Comment by gilbertslade** [comment]
Hey @rowdymehul, I can't find you on Pulse either.  Also, it looks like you've still have some editing and writing to do on your Contributing page.  Let me know if you need any help!
