### ISSUE TITLE
ETER

### ISSUE THREAD

**Issue by thessaly** [mozilla/global-sprint#224]
**[ Project Contact ]** @thessaly
**[ GitHub Repo ]** https://github.com/rlyehlab/eter
**[ Track ]** Openness, Decentralization, 
**[ Location ]** Buenos Aires, Argentina (GMT-3)
**[ Coach ]** Your OL5 Mentor

### Description
Open air-quality monitor for community science
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by thessaly** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by zee-moz** [comment]
Great work, so excited for this project. You are now on pulse: https://www.mozillapulse.org/entry/776

**Comment by thessaly** [comment]
Thanks @zee-moz :D
