### ISSUE TITLE
Money Talks and So Should We: Personal Assessment Tools for Finance Education

### ISSUE THREAD

**Issue by AndreaPocketsChange** [mozilla/global-sprint#225]
**[ Project Contact ]** @AndreaPocketsChange
**[ GitHub Repo ]** https://github.com/AndreaPocketsChange/PocketsChange-MoneyTalks
**[ Track ]** Web Literacy, Digital Inclusion, 
**[ Location ]** Santa Barbara, CA /PT 
**[ Coach ]** Your OL5 Mentor

### Description
At Pockets Change we’re changing the way money is taught. We combine Hip Hop, Finance, and Design Thinking to build financial capability in K-12 and early adulthood. 

Our workshops and lessons are a start but useful and accessible finance personal assessments are severely lacking in education. Those that exist do little to support the development of self-efficacy and understanding, rather they focus on calculating compound interest and other out of date skills. Let’s build them!! 

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @AndreaPocketsChange 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by AndreaPocketsChange** [comment]
This is ready to be featured on Mozilla Pulse. @acabunoc or @zee-moz

**Comment by abbycabs** [comment]
Pulsed: https://www.mozillapulse.org/entry/818 🎉 
Featured projects page: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
