### ISSUE TITLE
Digital Safety for Open Researchers

### ISSUE THREAD

**Issue by vkern** [mozilla/global-sprint#227]
**[ Project Contact ]** @vkern 
**[ GitHub Repo ]** https://github.com/opendigitalsafety/Digital-Safety-for-Open-Researchers
**[ Track ]** Web Literacy, Openness, Privacy and Security
**[ Location ]** Seattle, WA Pacific Daylight Time (GMT -7)
**[ Coach ]** Your OL5 Mentor

### Description
Helping researchers work open with confidence in their digital safety!
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @vkern et al! I updated the issue to include your full checklist. Happy sprinting! 🎉

**Comment by zee-moz** [comment]
Your project is on Pulse! Looks great, happy Sprinting 😸 
https://www.mozillapulse.org/entry/756

**Comment by stephwright** [comment]
@zee-moz, @acabunoc and @vkern ... the initial issue post indicates the repo is for ETER and is based out of ARgentina... that's a different project.

**Comment by thessaly** [comment]
Yup, it's Digital Safety issue with ETER's info

**Comment by zee-moz** [comment]
ugh, I was removing checklists, and somehow this happened. I will fix it.
