### ISSUE TITLE
SAFE Network

### ISSUE THREAD

**Issue by gnunicorn** [mozilla/global-sprint#23]
**[ Project Contact ]** @gnunicorn, @frabrunelle
**[ GitHub Repo ]** https://github.com/safenetwork/safenetwork 
**[ Track ]** Privacy + Security, Decentralization
**[ Community ]** Internet Policy & Advocacy - wrangler: @Melechuga 
**[ Location ]** Berlin / CET & Montreal Canada
### Description
The SAFE Network is a decentralized data storage and communications network that provides a secure, efficient and zero-cost infrastructure. Rather than using data centers and servers which are prone to data theft and surveillance, the SAFE Network uses advanced peer-to-peer technology that joins together the unused hard drive space, CPU power and Internet connections of all SAFE users, creating a global network.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @gnunicorn, @frabrunelle ! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @vanessarhinesmith. We're here to help you through this process.

**Comment by chadsansing** [comment]
Wow - who is your primary audience, @gnunicorn?

**Comment by gnunicorn** [comment]
@chadsansing 
> Wow - who is your primary audience, @gnunicorn?

We are looking for people, who want to build decentributed, privacy-first (web-)Apps (Developers, Designers, etc.). On a second note, if they also want to contribute to the project itself, that'd be amazing, too!

**Comment by chadsansing** [comment]
Great - thanks for helping me understand; do you envision the product being used by any community moreso than others, @gnunicorn?

**Comment by gnunicorn** [comment]
@chadsansing we are currently rolling out the second alpha version of the network and as the name suggest, this isn't stable enough for public consumption yet. We imagine that at the beginning it will be more attractive to people, who have stronger privacy needs or concerns - and as such more privacy concerned apps will leverage the infrastructure first. However, we are building it with the intent to become a new infrastructure to be used by anyone and everyone - basically as a new thin layer on top of our current internet, that protects your privacy and encrypts everything per default, without that particular person or even the app developer having to care too much about setting that up.

That said, I'd personally totally love to see a social network and other general purpose applications that classically won't have encryption needs being developed on it, too. And though privacy is our main concern, it brings along amazing distribution and load balancing features: once published your app can't be taken down - which makes it also attractive for anyone, who doesn't want to deal with setting up load balancers and deal with scalability issues. ...

**Comment by chadsansing** [comment]
I grok it - very cool.

**Comment by gnunicorn** [comment]
![](https://safenetwork.org/images/safenetwork.jpg)

**Comment by gnunicorn** [comment]
This is ready for Mozilla Pulse

**Comment by Melechuga** [comment]
Hi @gnunicorn,
This is very cool; thanks for sharing. I'm happy to put it up on Pulse, and before I do, I'm wondering if you have a lower-barrier activity that people could contribute to or get involved during the sprint days? I'll be including those opportunities in the Pulse posting as well.

Thanks,
Melissa

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
