### ISSUE TITLE
Information Activism Student Group

### ISSUE THREAD

**Issue by cynthinee** [mozilla/global-sprint#230]
**[ Project Contact ]** @cynthinee
**[ GitHub Repo ]** https://github.com/cynthinee/openstudentleaders
**[ Track ]** Openness, 
**[ Location ]** Los Angeles, Pacific 
**[ Coach ]** Your OL5 Mentor

### Description
Mobilizing student leaders to promote open.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @cynthinee 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉
