### ISSUE TITLE
Phinch: An interactive, exploratory data visualization framework for environmental –Omic datasets

### ISSUE THREAD

**Issue by hollybik** [mozilla/global-sprint#231]
**[ Project Contact ]** @hollybik
**[ GitHub Repo ]** https://github.com/PhinchApp/Phinch
**[ Track ]** Openness, Digital Inclusion 
**[ Location ]** Oakland/Los Angeles, CA (US Pacific Time)
**[ Coach ]** Tania Allard

### Description
Phinch is a open source browser-based, interactive data visualization tool for exploring environmental genomics datasets that enables rapid scientific visualization during the typical scientific research workflow. The project is a collaboration between Dr. Holly Bik (Assistant Professor at UC Riverside) and Pitch Interactive (a data visualization studio in Oakland, CA), and is funded by the Alfred P. Sloan Foundation. End users include researchers, educators, students, and citizen scientists.

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

**Comment by hollybik** [comment]
This is ready to be featured on Mozilla Pulse @acabunoc @zee-moz

**Comment by zee-moz** [comment]
approved-- looks great, congrats! have a good sprint :) https://www.mozillapulse.org/entry/803
