### ISSUE TITLE
Open Source Appliances for Sustainable development

### ISSUE THREAD

**Issue by goscommons** [mozilla/global-sprint#233]
**[ Project Contact ]** @goscommons
**[ GitHub Repo ]** https://goscommons.github.io
**[ Track ]** Openness, Digital Inclusion, Decentralization, 
**[ Location ]** delft, Netherlands

### Description
We are designing open source industrial machines and consumer goods. We started with a microwave oven, and its growing with plasma cutters, and agricultural machines. We are teaching open design standards to scale up distributed access and contribution to designs of the things that are used intensively in today's economies.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by goscommons** [comment]
Hi @acabunoc  ! Is ready for the mozilla pulse! We also created the issue: https://github.com/goscommons/goscommons.github.io/issues/5  for our event. on May 11th.

**Comment by abbycabs** [comment]
Thanks @goscommons! Wed to list a repo for this project, is https://github.com/goscommons/goscommons.github.io the one you'll be using?

I noticed you only have one issue with the `mozsprint` tag -- I'd recommend making a few more small tasks for the sprint :)

also, I LOVE the images in your repo! Nice work :)

You're featured here: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
Pulse link: https://www.mozillapulse.org/entry/687 🎉

**Comment by jurra** [comment]
Hi @acabunoc thanks a lot!
We are preparing the issues, but there are more in different repos that we have under @goscommons. So issues are under specific repos, we haven't yet put the #mozsprint tags though.

Thanks again for all the support and nice mentorship!

**Comment by abbycabs** [comment]
Thanks @jurra! Could you list all the repos you'll be using during the sprint here? This way you'll be part of our sprint activity visualization :)

**Comment by goscommons** [comment]
Abi @acabunoc we created a project board dedicated for the sprint. That should be the first landing space for people that decide to join: https://github.com/goscommons/goscommons.github.io/projects/2
We also added a list of issues and currently the project-repos:
https://github.com/goscommons/goscommons.github.io/issues/11

**Comment by abbycabs** [comment]
Ok! there are all the repos I'm listing for this project:
https://github.com/goscommons/goscommons.github.io, 
https://github.com/goscommons/Grapple, 
https://github.com/goscommons/microwave

let me know if I'm missing any

**Comment by jurra** [comment]
Abby thanks a lot. We suggest to point to the general issue we made for the
hackathon. Otherwise people might get lost. Is better if you publish the
link with the hackathon issue we gave you.

Best,
Jose

**Comment by abbycabs** [comment]
Thanks Jose — we’re visualizing and tracking github activity. We need a repo to do that!

**Comment by jurra** [comment]
Sure now I get it. :)
