### ISSUE TITLE
Resources for Open Science in Astronomy (ROSA)

### ISSUE THREAD

**Issue by rainsworth** [mozilla/global-sprint#234]
**[ Project Contact ]** @rainsworth
**[ GitHub Repo ]** https://github.com/rainsworth/ROSA/
**[ Track ]** Openness, 
**[ Location ]** Manchester, UK - BST (GMT+1)
**[ Coach ]** @SamanthaHindle & @aariops

### Description
Our mission is to compile and tailor open science best practices from around the web into a resource kit for astronomers to work openly from proposal to publication - we want to supply a single resource to early career scientists to empower them with the tools to practice open access/data/source/science! 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by rainsworth** [comment]
This is ready to be featured on Mozilla Pulse! @SamanthaHindle @aariops

**Comment by rainsworth** [comment]
@aariops @SamanthaHindle This is ready to be featured on Mozilla Pulse!

**Comment by aariops** [comment]
Hey @rainsworth 

Sorry for the lack of communication. :disappointed: 

ROSA has been featured for a while now. I just haven't posted it here.
https://www.mozillapulse.org/entry/684 

Let us know if you're looking for anything specific during the sprint. :smile:
