### ISSUE TITLE
Digital Grassroots

### ISSUE THREAD

**Issue by DigitalGrassroots** [mozilla/global-sprint#235]
**[ Project Contact ]** @DigitalGrassroots
**[ GitHub Repo ]** https://github.com/DigitalGrassroots/Digital-Grassroots/
**[ Track ]** Web Literacy, Openness, Digital Inclusion, 
**[ Location ]** GMT +2
**[ Coach ]** Renata Aquino Ribeiro

### Description
We engage our Digital Grassroots Ambassadors (young people around the world aged 14 - 29) on a 4 weeks Internet Literacy Course and mentorship, giving them an opportunity to kickstart active involvement and careers in internet governance. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by DigitalGrassroots** [comment]
This is ready to be featured on Mozilla Pulse @acabunoc @zee-moz

**Comment by abbycabs** [comment]
Hey @DigitalGrassroots!

You're so close to getting featured! I left a pull request renaming the file with the contributor covenant to code_of_conduct.md.
https://github.com/DigitalGrassroots/Digital-Grassroots/pull/9

We still need a CONTRIBUTING.md file in your repo before getting featured. Here is a template if you need some inspiration: https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md

**Comment by DigitalGrassroots** [comment]
Hi Abby,Thanks for your feedback 🙌🏻🙌🏻All set now, please review the repo https://github.com/DigitalGrassroots/Digital-GrassrootsThanks---- On Tue, 08 May 2018 02:58:54 +0300  Abigail Cabunoc Mayes<notifications@github.com> wrote ----Hey @DigitalGrassroots! You're so close to getting featured! I left a pull request renaming the file with the contributor covenant to code_of_conduct.md. DigitalGrassroots/Digital-Grassroots#9 We still need a CONTRIBUTING.md file in your repo before getting featured. Here is a template if you need some inspiration: https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by abbycabs** [comment]
Featured! https://www.mozillapulse.org/entry/806

**Comment by codefusser** [comment]
good day all, 
it's a privilege to be a part of #mozsprint, 2018. our ambassadors are already participating in various issues. what an amazing moment!
