### ISSUE TITLE
Map of the open movement

### ISSUE THREAD

**Issue by mrjohnc** [mozilla/global-sprint#237]
**[ Project Contact ]** @mrjohnc
**[ GitHub Repo ]** https://github.com/mrjohnc/Map-of-the-open-movement
**[ Track ]** Web Literacy, Openness, 
**[ Location ]** London

### Description
The Map of the Open Movement is an attempt to collate information on open organisations and open projects and visualise it on Wikidata, a sister project of Wikipedia, used to collate open data.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by mrjohnc** [comment]
https://github.com/mrjohnc/Map-of-the-open-movement

**Comment by abbycabs** [comment]
Hey @mrjohnc 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by mrjohnc** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by mrjohnc** [comment]
Also if the image I submitted looks bad, please use this one https://github.com/mrjohnc/Map-of-the-open-movement/blob/master/images/logo.png

**Comment by mrjohnc** [comment]
Thanks for the reminder, I made a mistake when I submitted, I didn't add
the 'Mozsprint' and '2018' tags, can you add them in?

Best

John

**Comment by abbycabs** [comment]
Looks great! I left one issue: https://github.com/mrjohnc/Map-of-the-open-movement/issues/6

But other than that, this is good to go :)
Pulse: https://www.mozillapulse.org/entry/816 🎉
