### ISSUE TITLE
Aquarius Project: Open Science Engagement

### ISSUE THREAD

**Issue by chrisbresky** [mozilla/global-sprint#239]
**[ Project Contact ]** @chrisbresky
**[ GitHub Repo ]** https://github.com/chrisbresky/Aquarius-Project
**[ Track ]** Openness, 
**[ Location ]** Chicago, Illinois CST
**[ Coach ]** Your OL5 Mentor

### Description
We are using ongoing science to create stories to produce open, interactive hands-on lesson plans in STEM.  We are using real science happening today to engage students not only with its relevance but with their ability to contribute, and packaging all that into ready to deliver lesson plans for teachers to use.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @chrisbresky 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by chrisbresky** [comment]
@acabunoc Thank you so much for the heads up. I missed these steps the first go round, thank you for pointing them out. The first six items are now completed. This is ready to be featured on Mozilla Pulse. Please contact me if anything else slipped by me.

**Comment by Monsauce** [comment]
Looks like all the tasks have been completed and ready to be featured on Pulse!

**Comment by zee-moz** [comment]
Done 👍 https://www.mozillapulse.org/entry/759
