### ISSUE TITLE
Local Web [old name: Localisation of school]

### ISSUE THREAD

**Issue by ghost** [mozilla/global-sprint#24]
**[ Project Contact ]** @drashti4
**[ GitHub Repo ]** https://github.com/drashti4/localisationofschool
                              https://github.com/drashti4/local-web
**[ Track ]** Web Literacy, Digital Inclusion
**[ Community ]** Teach the Web - wrangler: @amirad 
**[ Location ]**  IST (GMT+5:30)
### Description
We are bridge between newbies on Internet and remote volunteers/who don’t have time to go and teach them periodically. 

- We are looking for web developer. We already have most of content. 

-  Volunteers who can create video in their local language just by changing audio input 
- who visit school and deliver these video.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @drashti4! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by chadsansing** [comment]
@drashti4, this project will connect mentors and mentees online, is that correct?

**Comment by ghost** [comment]
Yes, Correct :+1: @chadsansing

**Comment by zee-moz** [comment]
This project feels like a great fit with our Web Literacy Hub and programs, and so I'd like to introduce @drashti4 to Amira Dhalla (@amirad) who can answer any questions you might have, add your project to Network Pulse as a "featured project" when you've completed all the requirements, and generally help you with any Sprint issues that come up. Happy Sprinting 🎉  👍 😃

**Comment by ghost** [comment]
Thanks for your words @zee-moz 

I got stuck in Development phase. Which software will be useful for creating videos and should be easy to handle by naive users. I have tried few but can not get one I'm looking for. This issue is already in process by mentor Baratang. Meanwhile if I can get your thoughts here, It would be helpful :smiley:

**Comment by ghost** [comment]
![finallogo](https://cloud.githubusercontent.com/assets/9081004/26389310/fcb2808a-4076-11e7-99b8-3f40d6a39917.png)

**Comment by ghost** [comment]
This is ready for Mozilla Pulse.

**Comment by amirad** [comment]
Hey @zee-moz I am still the wrangler for this or is this under the new Web Literacy track? LMK!

**Comment by ghost** [comment]
hey @chadsansing @zee-moz any updates on this?

**Comment by chadsansing** [comment]
@zee-moz, @acabunoc - who ought to Pulse this?

**Comment by abbycabs** [comment]
Just catching up here! @amirad -- this is still in your 'Teach the Web' track. Please pulse :)

**Comment by ghost** [comment]
Any updates on this? We are just 4 days away from sprint :1234:

**Comment by amirad** [comment]
Confirming this is pulsed: https://www.mozillapulse.org/entry/330 

@drashti4 can you point me to the exact file you want to delete? I don't see it in the repo! I also don't know why it wouldn't delete. So strange. Is it a blocker?

**Comment by abbycabs** [comment]
Added the image and renamed project in pulse!

**Comment by amirad** [comment]
ops sorry. thanks abby!

**Comment by abbycabs** [comment]
happy to be extra 👀 😄

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
