### ISSUE TITLE
Open to Discussion

### ISSUE THREAD

**Issue by baricks** [mozilla/global-sprint#240]
**[ Project Contact ]** Rebecca Ricks & Amel Ghouila
**[ GitHub Repo ]** https://github.com/baricks/opentodiscussion
**[ Track ]** Openness, 
**[ Location ]** NYC / EST and Tunis / DST
**[ Coach ]** @quirksahern & @fimakeswork

### Description
A major barrier in the shift to open science is that members of the community operate independent of one another. ‘Open to Discussion’ will give space for practitioners and scientists to come together and engage in conversations about what working open means for their work. Through a playful group exercise that involves using a deck of cards to ignite discussions, the goal is to facilitate listening and candidness among participants.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by quirksahern** [comment]
Hi @baricks ! Really like your project. If you need any guidance completing the docs please let me know.

**Comment by quirksahern** [comment]
Hi! How are you getting on?

**Comment by quirksahern** [comment]
Hi @baricks, how's it going? Let me know if you need any assistance?

**Comment by baricks** [comment]
@quirksahern Hi there! Thanks for your interest 😀We are still figuring out how best folks can contribute and will update the CONTRIBUTING.md accordingly.

**Comment by quirksahern** [comment]
Yeah, its surprisinly hard. I had similar difficulties when initially setting up the Data Literacy Playground project. It is still very much a work in progress and evolving. Am happy to review and feedback.

**Comment by quirksahern** [comment]
@baricks How's it going? Need any help?

**Comment by abbycabs** [comment]
Hey @baricks & Amel

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by quirksahern** [comment]
Hi @baricks, not long now! Are you ready to be featured on Mozilla Pulse?

Is there anything you need help with?
