### ISSUE TITLE
Content-o-Tron

### ISSUE THREAD

**Issue by booyaa** [mozilla/global-sprint#241]
**[ Project Contact ]** @booyaa
**[ GitHub Repo ]** https://github.com/rust-community/content-o-tron
**[ Track ]** Web Literacy, Openness, Digital Inclusion, Decentralization, 
**[ Location ]** Colchester, England

### Description
Helping the Rust community and newcomers to share their story of using Rust!
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by booyaa** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
https://www.mozillapulse.org/entry/662 🎉
