### ISSUE TITLE
HBASets

### ISSUE THREAD

**Issue by derekhoward** [mozilla/global-sprint#244]
**[ Project Contact ]** @derekhoward
**[ GitHub Repo ]** https://github.com/derekhoward/HBAsets
**[ Track ]** Openness, 
**[ Location ]** Toronto, ET
**[ Coach ]** @chadsansing

### Description
HBASets is a project for creating polygenic molecular maps of the brain
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by chadsansing** [comment]
Hi, @derekhoward - let me know how to help.

**Comment by abbycabs** [comment]
Hey @derekhoward 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by abbycabs** [comment]
Hey @derekhoward please add the `mozsprint` label to some issues - the Sprint has started!

**Comment by derekhoward** [comment]
I can't make this a priority for the Sprint but I'll be cheering on the other projects from the sidelines!
