### ISSUE TITLE
Broadband Performance and Internet Measurements in Africa

### ISSUE THREAD

**Issue by sktomor** [mozilla/global-sprint#245]
**[ Project Contact ]** @MsKiden
**[ GitHub Repo ]** https://github.com/MsKiden/africa-internet-measurements
**[ Track ]** Openness, Digital Inclusion, 
**[ Location ]** Cape Town, South Africa; UTC +2
**[ Coach ]** Bonface Ochieng

### Description
The project aims to build an open data platform containing Internet measurements and quality of service related information, , with the ability for users (even basic Internet end-users) to make sense of this data in terms of graphs, charts, images, etc to guide decision-making and improve service provision.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by sktomor** [comment]
@acabunoc This is ready to be featured on Mozilla Pulse. Thank you for the support.

**Comment by sktomor** [comment]
Hey @acabunoc it seems I have 2 Pulse accounts. I have contacted the team to fix the issue. I will let you know once this is done.

**Comment by abbycabs** [comment]
In the meantime:
Pulse: https://www.mozillapulse.org/entry/694 🎉 
Featured: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
