### ISSUE TITLE
Open Data Kit

### ISSUE THREAD

**Issue by lognaturel** [mozilla/global-sprint#248]
**[ Project Contact ]** @lognaturel
**[ GitHub Repo ]** http://github.com/opendatakit
**[ Track ]** Openness, Digital Inclusion, Decentralization, 
**[ Location ]** San Diego, CA; PDT
**[ Coach ]** Your OL5 Mentor

### Description
Open Data Kit replaces paper surveys with smartphones. It has been used to collect millions of data points for social good in challenging environments around the world.

Data collection is a key component of social good efforts ranging from polio elimination to rainforest conservation. Users of ODK software include Red Cross, World Health Organization, Centers for Disease Control, Jane Goodall Institute, Gates Foundation, the Carter Center, and many others.

**Ready to sprint with us? Please start [here](https://forum.opendatakit.org/t/welcome-mozilla-global-sprinters/12904)!**

Repositories actively seeking contributions:
- https://github.com/opendatakit/website - most of us will be focusing our time here
- https://github.com/opendatakit/collect - Android client
- https://github.com/opendatakit/briefcase - desktop Java tool for pulling down data for analysis
- https://github.com/opendatakit/docs - user documentation for all the tools 

[Code of conduct](https://github.com/opendatakit/governance/blob/master/CODE-OF-CONDUCT.md)
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018! We also encourage you to [read our welcome post](https://forum.opendatakit.org/t/welcome-mozilla-global-sprinters/12904) and join the [developer Slack](http://slack.opendatakit.org/).

***

**Comment by lognaturel** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by zee-moz** [comment]
@lognaturel hello! I'd like to feature this project on Mozilla Pulse, but I don't see a link to code of conduct or community participation guidelines here, in your various repos... 

And I didn't see that you'd made an entry on Pulse-- (see [instructions to submit your project to Mozilla Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/)).

Add a link to a COC in your repo(s) then make that Pulse submission and I can approve it, thanks!! 😸

**Comment by lognaturel** [comment]
Thanks, @zee-moz! I've submitted a new entry, not sure what happened before. 😿

We use the GitHub standard for codes of conduct and provide a .github/CODE_OF_CONDUCT.md file in each repo. These all point to our project-wide code of conduct at https://github.com/opendatakit/governance/blob/master/CODE-OF-CONDUCT.md. I've added a link in the description above as well.

**Comment by zee-moz** [comment]
Aha, thanks, that helps. And thanks for adding the link above. So I see that if I want to find the COC in each repo, I have to know to look into the .github folder for it. It's great that they are there, but I do think they could be more visible. Maybe just adding links from the contributing file in each repo to your COC would help people more easily find the file. 

And, I've pulsed your project! great work, excited for your sprint! 💯 https://www.mozillapulse.org/entry/805

**Comment by lognaturel** [comment]
Awesome, thanks so much!

> Maybe just adding links from the contributing file in each repo to your COC would help people more easily find the file.

That's a good idea, thanks! I thought GitHub asked for a specific filename to surface it and I thought I had seen it before but I'm not finding it now so clearly it's not visible enough.
