### ISSUE TITLE
Git Push Freshman

### ISSUE THREAD

**Issue by ottagit** [mozilla/global-sprint#25]
**[ Project Contact ]** @ottagit
**[ GitHub Repo ]** https://github.com/ottagit/git_push_freshman
**[ Track ]** Web Literacy, Open Innovation., Digital Inclusion
**[ Community ]** Mozilla Clubs
**[ Location ]** Kisumu, Kenya - EAT
### Description
GitHub hosted open source project that invites freshmen from Maseno University, Kenya, as contributors but still open to other interested contributors - acting as a training platform to enhance their skills in version control using Git and collaborative software development using GitHub.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @ottagit! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @jvallera. We're here to help you through this process.

**Comment by jvallera** [comment]
How is this going @ottagit ? Are you planning to have this project featured? If so, be sure to complete the checklist. I am particularly interested in the contributing.md file once it is ready. 

cc @carotejada

**Comment by ottagit** [comment]
Hi @jvallera The going's good. Yes! I'm planning to have the project featured and will make an effort to complete the checklist by the end of the weekend. Sorry for the delay.

**Comment by ottagit** [comment]
![git_push_freshman](https://cloud.githubusercontent.com/assets/12326211/25326524/44be9acc-28d9-11e7-9cf1-8547d78ef858.png)

**Comment by ottagit** [comment]
This is ready for Mozilla Pulse

**Comment by ottagit** [comment]
Hi @jvallera Do I get the green light now...? Your comments please. Thank you.

**Comment by jvallera** [comment]
Hi @ottagit. It is coming along nicely! There are a few more things I want you to work on before we put it on Pulse. Just want to make sure it is in tip top shape...

In general we need more of the "why" and "how" to be included in the readme file and the contribute file. Try to capture more about what the project it, who it is for and why it is important. Be clear about what you NEED from people. Sure, they can fork and remix, but for what reason? do you need their help with anything? It will also help for you to explain what the goals are of the project - where you want it to have an impact and how you are hoping it will help your work in the long run. 

Assume 99% of the people who will see it do not know what OLTS is or what Git is....if knowing both of these things is a requirement to contribute then say that at the very beginning of the contribute page.

Great job so far!

**Comment by ottagit** [comment]
Thanks @jvallera for the clarification. Working on the above recommendations.

**Comment by ottagit** [comment]
Hi @jvallera . Did some tweaks on the README.md and CONTRIBUTING.md files. Your thoughts please..thanks.

**Comment by jvallera** [comment]
Hi @ottagit thanks for the tweaks! I will get this posted on Pulse Asap.

One thing...the "edit" button on the gitbook was not an option for me. All I saw was "read". I recommend adding a note to your contributor file with instructions in case this happens and what people do if they run into this (would they just contribute to the github file in this case?) Another detail to include in the contributor file is info about using Markdown - some people (like educators) may not expect it. 

Here are some next steps for you:
1. Start adding issues to your repo. Be specific. An example is " write Instructions for branching". Issues will give people exact things they can start to contribute to
2. Spread the word! Starting letting people know you are seaking contributors for this. 

How does that sound? Excited to see this grow!

**Comment by jvallera** [comment]
Your project is posted. https://www.mozillapulse.org/entry/256

**Comment by ottagit** [comment]
Thanks @jvallera Working on the proposed changes.

**Comment by jvallera** [comment]
Hi @ottagit your updates look good. For your issues you can add the label "mozsprint" to each one. Also, it might help to elaborate on each issue a little more - so people have more context for example what that issue is accomplishing and/or if there is any preference for how it gets done.

**Comment by ottagit** [comment]
Thank you @jvallera At work ASAP.

**Comment by Carotejada** [comment]
Just saw this. I was getting the notifications on my old Mozilla email. Apologies for the delay. @ottagit awesome project! Looking forward to collaborate with you ;)

**Comment by ottagit** [comment]
Thanks @Carotejada Glad to have you as a contributor :+1:

**Comment by ottagit** [comment]
Hi @Carotejada Just sent you an invite to collaborate an help me build this project. Looking forward to your response.

**Comment by Carotejada** [comment]
@ottagit got it!! Thank you. Will dive in and reach out to you if I have any qs.

**Comment by ottagit** [comment]
@Carotejada splendid :+1:

**Comment by joseph-njogu** [comment]
Am interested in contributing to the project

**Comment by ottagit** [comment]
Hi @joseph-njogu Thanks for your interest in becoming a contributor. You can check out some of the [project issues](https://github.com/ottagit/git_push_freshman/issues ) and see which suits you best. Please let me know ASAP

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by joseph-njogu** [comment]
yeah.  I can table one project

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/

**Comment by ottagit** [comment]
Thanks @acabunoc for the link
