### ISSUE TITLE
Fogos.pt

### ISSUE THREAD

**Issue by tomahock** [mozilla/global-sprint#250]
**[ Project Contact ]** @tomahock
**[ GitHub Repo ]** https://github.com/fogospt
**[ Track ]** Web Literacy, Openness, 
**[ Location ]** Lisbon, UTC
**[ Coach ]** @Wiroll & @psubhashish

### Description
Real time map that shows wildfires in Portugal. Also an Android and iOS app to notify people when a new fire starts in their location.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by psubhashish** [comment]
Hi @tomahock, thank you for submitting this great project. As the clock is ticking for the Global Sprint, can you please check all the tasks that are pending, and sign off with a comment saying "This is ready to be featured on Mozilla Pulse" so that we coaches can review and approve it soon?

**Comment by abbycabs** [comment]
Hey @tomahock! I've listed these two repos for your project:
https://github.com/FogosPT/flutterfogos, https://github.com/FogosPT/fogospt

Let me know if I'm missing anything!

**Comment by erandraj** [comment]
I will join

**Comment by abbycabs** [comment]
Hey @tomahock 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by tomahock** [comment]
All done!
