### ISSUE TITLE
Open Web for Learning & Teaching Expertise Hub (formerly TELOWEH)

### ISSUE THREAD

**Issue by drdvo** [mozilla/global-sprint#251]
**[ Project Contact ]** @drdvo
**[ GitHub Repo ]** https://github.com/drdvo/OWLTEH
**[ Track ]** Web Literacy, Openness, Internet Privacy, 
**[ Location ]** Coventry, United Kingdom (UTC+1)
**[ Coach ]** Harry Smith

### Description
OWLTEH aims to gather resources and examples of inspiring practice related to the use of the Open Web for learning and teaching, building a hub of expertise so that more people can benefit from the potential of open online infrastructures for educational purposes. OWLTEH will be valuable to anyone interested in learning in a networked world and want to help individuals (educators, learners) and communities (schools, universities, etc.) to develop their own web literacies. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @drdvo 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by drdvo** [comment]
This is ready to be featured on Mozilla Pulse. Sorry about the delay!

**Comment by abbycabs** [comment]
Looks great! Left one issue: https://github.com/drdvo/OWLTEH/issues/6

But other than that, this is good to go!
Pulse: https://www.mozillapulse.org/entry/823 🎉

**Comment by iyketheintrovert** [comment]
Hello, I'm interested in contributing to the project
