### ISSUE TITLE
Open Science MOOC

### ISSUE THREAD

**Issue by Protohedgehog** [mozilla/global-sprint#253]
**[ Project Contact ]** @protohedgehog
**[ GitHub Repo ]** https://github.com/OpenScienceMOOC
**[ Track ]** Openness, 
**[ Location ]** Berlin, I think (possibly Vienna)
**[ Coach ]** @chadsansing

### Description
Global policies are emerging that include some aspect of ‘Open Science’, but our universities are not teaching us the knowledge and skills we need to do research effectively. This MOOC is designed to equip researchers with the skills they need to excel in a modern research environment. The content is distilled into 10 modules, each comprising a range of resources including videos, research articles, datasets and code.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by chadsansing** [comment]
Hello, [[@Protohedgehog]], please let me know when you are ready to be reviewed for Pulse. I am also happy to answer questions or lend other support as needed.

**Comment by Protohedgehog** [comment]
Ah right, hadn't even considered that yet! Gimme a couple of days to finish off the check boxes :)

**Comment by abbycabs** [comment]
Hey @Protohedgehog! Nice to see you at the sprint 🎉 

I've listed these repos for your project. Let me know if I'm missing anything:
https://api.github.com/repos/OpenScienceMOOC/M3_RR_data_analysis
https://api.github.com/repos/OpenScienceMOOC/Main
https://api.github.com/repos/OpenScienceMOOC/Module-1-Open-Principles
https://api.github.com/repos/OpenScienceMOOC/Module-10-Open-Advocacy
https://api.github.com/repos/OpenScienceMOOC/Module-2-Open-Collaboration
https://api.github.com/repos/OpenScienceMOOC/Module-3-Reproducible-Research-and-Data-Analysis
https://api.github.com/repos/OpenScienceMOOC/Module-4-Open-Research-Data
https://api.github.com/repos/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source
https://api.github.com/repos/OpenScienceMOOC/Module-6-Open-Access-to-Research-Papers
https://api.github.com/repos/OpenScienceMOOC/Module-7-Open-Evaluation
https://api.github.com/repos/OpenScienceMOOC/Module-8-Public-Engagement-with-Science
https://api.github.com/repos/OpenScienceMOOC/Module-9-Open-Educational-Resources
https://api.github.com/repos/OpenScienceMOOC/resources
https://api.github.com/repos/OpenScienceMOOC/site

**Comment by jcolomb** [comment]
Wouldn't it be better to change the linked repo to https://github.com/OpenScienceMOOC/Main,
Then what remains is the "submit your project to Mozilla Pulse." Do you want me to do it Jon?

**Comment by Protohedgehog** [comment]
@jcolomb That would be awesome - about to jump on a flight so a bit out of it for the next 24 hours or so..

**Comment by jcolomb** [comment]
This is ready to be featured on Mozilla Pulse.

**Comment by jcolomb** [comment]
maybe it would make sense to change the github repo to https://github.com/OpenScienceMOOC/main.

**Comment by dwhly** [comment]
Hi @Protohedgehog!  In the interest of creating a reinforcing, mutually linked group of Open Science related sprints, I'm tagging this project as related to the Joint Roadmap effort for Open Science Tools (https://github.com/mozilla/global-sprint/issues/285).  Glad so many friends are participating in this.  See you next week!

**Comment by Protohedgehog** [comment]
@dwhly This is fantastic, thank you! I've just been speaking with some folks about that, and the relationship between the MOOC, the Open Scholarship Strategy (both in prep), and the roadmap project (which is awesome btw). Let's chat/hack this soon :)

**Comment by chadsansing** [comment]
Hi, @Protohedgehog - are you using [https://github.com/OpenScienceMOOC/Main]( https://github.com/OpenScienceMOOC/Main) as you landing page? If so, I'm not sure CONTRIBUTING and README provide enough information yet on how to engage with the project - they each seem to refer contributors to the other document. 

Once those guidelines are clearer (and please let me know if I've missed them), you can submit to Pulse, and I will review your entry. You might also create some good first issues to help contributors navigate to other repos in the project.

**Comment by Protohedgehog** [comment]
Excellent points, thank you. I'll try and get these updated before the sprint :)
