### ISSUE TITLE
HPC416S

### ISSUE THREAD

**Issue by trustodia** [mozilla/global-sprint#257]
**[ Project Contact ]** @trustodia
**[ GitHub Repo ]** https://github.com/trustodia/HPC416S
**[ Track ]** Openness, 
**[ Location ]** Room 307, FISAN building, Stellenbosch University, Tygerberg Campus, Francie Van Zijl Dr, Beside Tygerberg Hospital, Cape Town, 7505
**[ Coach ]** @gilbertslade

### Description
This project is aimed at building a High Performance Computing resource (compute resource) for metagenomics data analysis.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by trustodia** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hi @trustodia - I'm having trouble finding your project in pulse. Did you follow all of the instructions here? https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/

**Comment by trustodia** [comment]
Hello Abigail,

I just submitted my project to Pulse, thanks for pointing this out. Totally
forget this!!👍

I hope this is what you wanted me to do 🤔

Regards.

Trust Odia,CCNA

@thereal_trust
<https://twitter.com/thereal_trust>

ORCID: 0000-0002-0113-0902


<https://twitter.com/thereal_trust>

**Comment by abbycabs** [comment]
Pulsed: https://www.mozillapulse.org/entry/707 🎉 
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
