### ISSUE TITLE
Common Voice

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/global-sprint#259]
**[ Project Contact ]** @mikehenrty
**[ GitHub Repo ]** https://github.com/mozilla/voice-web
**[ Track ]** Openness, Digital Inclusion, Decentralization, 
**[ Location ]** Berlin, Germany
**[ Coach ]** @meghanlazier

### Description
Voice recognition technology could revolutionize the way we interact with machines, but the currently available systems are expensive and proprietary. Common Voice is a project to make voice recognition technology easily accessible to everyone. People donate their voices to a massive database that will let anyone quickly and easily train voice-enabled apps. All voice data is released into the public domain (CC-0), so it may be used by anyone from the casual hobbyist to large corporations and governments.

Right now, Common Voice is in the process of going multi-lingual. Our website is currently available in 29 languages, and we are localizing into 13 more. As part of this, we need to collect (or write sentences) for people to read in all these new languages. Join us for the #mozsprint to help us gather these sentences in any languages you are interested in!
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by dkmerona** [comment]
i am up for contributing for the 2018 sprint

**Comment by unclenachoduh** [comment]
I'd like to contribute during the global sprint. What tasks can a new contributor take on?

**Comment by mikehenrty** [comment]
@unclenachoduh that's great to hear!

the biggest task will be collecting sentences for people to read in new languages. I'm building some documentation right now to support you, but it's not quite read yet. stay tuned!

in the meantime, you can see our announcement of multi-language to get some more context:
https://discourse.mozilla.org/t/multi-language-update-for-common-voice/27655

**Comment by mikehenrty** [comment]
@meghanlazier This is ready to be featured on Mozilla Pulse.

https://www.mozillapulse.org/entry/802

**Comment by abbycabs** [comment]
note for @meghanlazier: since @mikehenrty is staff his pulse entry goes live immediately and skips the moderation phase!

**Comment by chrissyseas** [comment]
Hey, I'd like to contribute for this upcoming sprint! is Indonesian language will be available on next monday?

**Comment by meghanlazier** [comment]
@mikehenrty Your article is live! https://www.mozillapulse.org/entry/802

**Comment by mikehenrty** [comment]
thank you so much @meghanlazier and @acabunoc !!

quick question: would it be possible to change the "Visit" link in our pulse entry to our Global Sprint microsite url: https://voice-sprint.mozilla.community/?

We would love to change it back to the main site url (http://voice.mozilla.org/) after the sprint is over. But if all that is too much trouble, we can leave it as is.

**Comment by mikehenrty** [comment]
@chrissyseas great! Indonesian is indeed one of the languages we would like help with:
https://voice.mozilla.org/id

Our goal during the sprint is to collect sentences in these new languages for people to read. Here's some guidance (work in progress) we will point to during the sprint:
https://voice-sprint.mozilla.community/faq/

**Comment by cmd16** [comment]
Which languages are you looking for?

**Comment by syilmaz** [comment]
I'd love to contribute @mikehenrty! But you know that ;)

**Comment by mikehenrty** [comment]
@cmd16 any language you speak :) We are not choosing languages, but letting the community decide which languages they wan to work on. So, that question is really up to you

**Comment by mikehenrty** [comment]
Hey all, for anyone coming late wanting to participate in this sprint, please go to:
http://voice-sprint.mozilla.community/
