### ISSUE TITLE
The Open Teach-R Project

### ISSUE THREAD

**Issue by marcosvital** [mozilla/global-sprint#26]
**[ Project Contact ]** @marcosvital
**[ GitHub Repo ]** https://github.com/marcosvital/teach-R-project
**[ Track ]** Open Innovation, Open Science
**[ Community ]** 
**[ Location ]** Brazil UTC-3
### Description
To create and gather organized courseware for anyone willing to offer a R based course for biological sciences students and researchers.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @marcosvital! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by zee-moz** [comment]
Hi @marcosvital, so glad you'll be Sprinting with us! I'm assigning this project to the Mozilla Science community, where you are already well-connected. Let me or @stephwright know if you have any questions about the project requirements! Yay! 😸

**Comment by marcosvital** [comment]
Thanks, @zee-moz ! :D 

I'm building the repo and almost completing the checklist. I'll let you and @stephwright know when its ready for Pulse. This is going to be a great experience!

**Comment by marcosvital** [comment]
Yay, we got a nice looking logo:

![teachr](https://cloud.githubusercontent.com/assets/13972235/25249144/44ed811a-25e7-11e7-8c80-fb80683c0008.png)

**Comment by marcosvital** [comment]
Ok! I believe that...

`This is ready for Mozilla Pulse`!

:D

**Comment by stephwright** [comment]
On it @marcosvital !!!!  Let's get this up there!

**Comment by stephwright** [comment]
It has now been pulsed! https://www.mozillapulse.org/entry/238

**Comment by marcosvital** [comment]
Great, @stephwright , thanks!

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
