### ISSUE TITLE
Reagents.io (tool and standards for open material, open science project)

### ISSUE THREAD

**Issue by jcolomb** [mozilla/global-sprint#260]
**[ Project Contact ]** @jcolomb
**[ GitHub Repo ]** https://github.com/jcolomb/reagentsio_website
**[ Track ]** Decentralization, 
**[ Location ]** UK, eLife innovation sprint
**[ Coach ]** @aj-ptw

### Description
Creating standards to describe and report lab reagents, and create application to merge different standards into one unique format. Also think about ways to make the information accessible and open
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by jcolomb** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by andrewjaykeller** [comment]
Alright! I will plan some time to go through your repo!

**Comment by andrewjaykeller** [comment]
There is some needed clean up with the readme, specifically the titles such as “The Problem(s)” needs a space after the two ##

**Comment by jcolomb** [comment]
hey, I updated the readme and hope it is of better quality now.
see https://github.com/jcolomb/reagentsio_website

Dr. Julien Colomb
#openscience #neuroscience
https://orcid.org/0000-0002-3127-5520
Trainer at access2perspectives.com
Founder of Drososhare.net

Schillerpromenade 4
12049 Berlin

**Comment by andrewjaykeller** [comment]
Okay! I set to approved on Mozilla pulse, good job and good luck!
