### ISSUE TITLE
Data Literacy Playground

### ISSUE THREAD

**Issue by quirksahern** [mozilla/global-sprint#262]
**[ Project Contact ]** Samantha Ahern
**[ GitHub Repo ]** https://github.com/quirksahern/DataLiteracyPlayground
**[ Track ]** Openness, 
**[ Location ]** UTC
**[ Coach ]** @anmechung 

### Description
How can young adults give informed consent about data collection and usage if they are not truly informed?  The data play ground ise an online learning space where young adults can use, interact with and understad the benefits and issues of using and sharing data so that they can make informed choices about data sharing (personal and research) and open data usage.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by quirksahern** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by quirksahern** [comment]
@acabunoc not quit sure what happened with the link for the issue but seem to be coaching my own project

**Comment by abbycabs** [comment]
I think that's fine :) @anmechung was assigned to this in the email -- are you sure this issue was created by clicking this link in your email? Either way, I'm fine with you coaching your own project!

**Comment by quirksahern** [comment]
I think I've broken the issue form :-( too long a day. Sorry. Giving up and going to bed. Either way its ready to be featured on Mozilla Post I think @anmechung @acabunoc

**Comment by quirksahern** [comment]
@acabunoc @anmechung I forgot to add the 2018 tag to the  pulse submission - is that ok?

**Comment by anmechung** [comment]
If you could add the tag?  Just resubmit with with tag.  Thx!

**Comment by quirksahern** [comment]
Re-submitted with 2018 tag added

**Comment by anmechung** [comment]
@quirksahern In my attempt to open up  https://www.data-playground.org.uk, it gives me the following message ... 

Your connection is not secure

The owner of www.data-playground.org.uk has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

I think the correct link was in the original submission?   https://github.com/quirksahern/DataLiteracyPlayground

**Comment by anmechung** [comment]
@acabunoc There were two submissions - I approved the one with the 2018 and mozspring tag, and declined the other.

**Comment by abbycabs** [comment]
Great to see this on the featured projects page! https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/ 🎉  nice work @anmechung & @quirksahern
