### ISSUE TITLE
Code is Science

### ISSUE THREAD

**Issue by yochannah** [mozilla/global-sprint#263]
**[ Project Contact ]** @yochannah 
**[ GitHub Repo ]** https://github.com/yochannah/code-is-science
**[ Track ]** Openness
**[ Location ]** UK, Cambridge, but attending the London sprint site where all the cool kids are
**[ Coach ]** @quirksahern & @fimakeswork

### Description
Increasing open source code in academia
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by yochannah** [comment]
@quirksahern & @fimakeswork - I don't think I need a coach for this, I just took too long to register <3 lol

**Comment by quirksahern** [comment]
Hi Yo,

Likewise lol!

Not even sure mine’s been assigned a coach :-/

If you complete the issue form, will authorise on Mozilla Pulse.

Dam

On 13 Apr 2018, at 12:53, Yo Yehudi <notifications@github.com<mailto:notifications@github.com>> wrote:


@quirksahern<https://github.com/quirksahern> & @fimakeswork<https://github.com/fimakeswork> - I don't think I need a coach for this, I just took too long to register <3 lol

**Comment by yochannah** [comment]
I've posted this on Mozilla Pulse before so don't think we need to repeat
it. Unless the policy is that is has to be new-ish on pulse and it's ok to
post more than once?

**Comment by quirksahern** [comment]
Hi @yochannah, have you submitted to Pulse?

**Comment by yochannah** [comment]
@quirksahern  Should I submit it again? I did last year and don't want to spam pulse :)

**Comment by quirksahern** [comment]
@yochannah yeah, I think so, but you need to add at 2018 tag

**Comment by yochannah** [comment]
oh, sorry! It'll be a day or two (I have other deadlines looming) but I'll ping you when it's up.

**Comment by yochannah** [comment]
@quirksahern This is ready to be featured on Mozilla Pulse

**Comment by quirksahern** [comment]
Hi! Just had a quick look at repo. In the read me you directly mention Hacktoberfest volunteers, might be worth updating to Global Sprint or mentioning that too.

**Comment by quirksahern** [comment]
Have just approced the project on Mozilla Pulse

**Comment by yochannah** [comment]
Thanks! I've also replaced hacktoberfest with global sprint, thanks for the
heads up.

**Comment by quirksahern** [comment]
Approved even :-/

**Comment by VasantJ3** [comment]
Hello,  I would like to contribute to this project. I am a class 12 student.  I have skills in designing(photoshop,premier pro),  presentation and anything which is given to me. I am sincere to my work.

**Comment by quirksahern** [comment]
Hi @VasantJ3 !

Take a look at the project description on Mozilla Pulse, it will let you know what type of help is needed.

Then, visiting project repository, pick an issue you’re comfortable  with trying and have a go.

Happy Sprinting!

**Comment by yochannah** [comment]
@VasantJ3 thanks for volunteering! if you're interested in design-related tasks, we have some here: https://github.com/codeisscience/logos/issues or pop by our gitter: https://gitter.im/codeisscience/Lobby <3
