### ISSUE TITLE
Paironauts

### ISSUE THREAD

**Issue by yakryder** [mozilla/global-sprint#265]
**[ Project Contact ]** @sherspock
**[ GitHub Repo ]** https://github.com/AgileVentures/Paironauts
**[ Track ]** Web Literacy, 
**[ Location ]** Indiana EST
**[ Coach ]** @jamjwait

### Description
An open platform for bringing together developers and aspiring developers looking to hone their skills in a collaborative environment.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by jamjwait** [comment]
Hi @SherSpock! I just wanted to check in to see how your project is coming along. Let us know if you have any questions!

**Comment by yakryder** [comment]
@jamjwait Thanks! We'll round out the checklist in the next few days.

**Comment by abbycabs** [comment]
Hey @SherSpock 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by yakryder** [comment]
@acabunoc Sounds very reasonable. By May 9th or by May 9th EOD?

**Comment by abbycabs** [comment]
@SherSpock before the global sprint starts at 9am May 10th in New Zealand (5pm ET May 9th)

**Comment by yakryder** [comment]
@acabunoc Thanks! Will do
