### ISSUE TITLE
Whose Data?

### ISSUE THREAD

**Issue by samanthaburton** [mozilla/global-sprint#266]
**[ Project Contact ]** @samanthaburton
**[ GitHub Repo ]** https://github.com/samanthaburton/whose_data
**[ Track ]** Web Literacy, Internet Privacy, Digital Inclusion, 
**[ Location ]** Toronto, Canada, EST
**[ Coach ]** @felipez3r0

### Description
Whose Data? aims to make it easier for Canadians to answer key questions about who owns -- and what options we have to control -- data collected about us via common online (eg. social media platforms) and offline (eg. health records) activities.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @samanthaburton 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by samanthaburton** [comment]
This is ready to be featured on Mozilla Pulse! @acabunoc @zee-moz @felipez3r0

**Comment by abbycabs** [comment]
Featured! https://www.mozillapulse.org/entry/811
