### ISSUE TITLE
BklynConnect

### ISSUE THREAD

**Issue by mayawagon** [mozilla/global-sprint#267]
**[ Project Contact ]** @mayawagon
**[ GitHub Repo ]** https://github.com/mayawagon/bklynConnect-curriculum
**[ Track ]** Web Literacy, Internet Privacy, Digital Inclusion, Decentralization, 
**[ Location ]** Brooklyn, NY, EST
**[ Coach ]** @schae234

### Description
An open digital literacy, privacy, and networking curriculum for a designing and constructing a community-driven wireless network with communities that need it most.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @mayawagon 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)
