### ISSUE TITLE
Catalogue

### ISSUE THREAD

**Issue by pierreozoux** [mozilla/global-sprint#268]
**[ Project Contact ]** @pierreozoux
**[ GitHub Repo ]** https://github.com/libresh/catalogue
**[ Track ]** Openness, Decentralization, 
**[ Location ]** Wiesbaden in  UTC+02:00
**[ Coach ]** @tpoisot

### Description
standardize user signup experience on web free software
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @pierreozoux 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)
