### ISSUE TITLE
TRANSPOSE - a user-editable database of scholarly journal practices

### ISSUE THREAD

**Issue by jpolka** [mozilla/global-sprint#269]
**[ Project Contact ]** @jpolka, @tonyR-H, @garymcdowell
**[ GitHub Repo ]**  https://github.com/transpose-publishing/policies-database
**[ Track ]** Openness, 
**[ Location ]** Boston, MA (GMT-4)
**[ Coach ]** @gilbertslade

### Description
We will build a user-editable database of journal practices relating to the openness of peer review, the recognition of early career researchers who contribute to peer review, and detailed policies on preprinting.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by dwhly** [comment]
Hi @jpolka!  Great to see you here. Just tagging this project as related to the Joint Roadmap effort for Open Science Tools (https://github.com/mozilla/global-sprint/issues/285).  Synergies!  (Perhaps ASAPbio might join as a member?  [jrost.org](jrost.org))  Thanks for putting this together, interested to see what comes out of it.

**Comment by Daniel-Mietchen** [comment]
@jpolka Curious to find out more about your plans for making that database user editable. Have you looked into wikis, and specifically [Wikibase](http://wikiba.se/)? Overview of current affairs is [here](https://addshore.com/2018/04/wikibase-of-wikibases/).

**Comment by jpolka** [comment]
Thanks @Daniel-Mietchen - Wikidata was one of the first things we talked about, but our data fields are not all very well-defined yet - lots of them would contain policy quotes, etc ([see discussion](https://github.com/transpose-publishing/policies-database/issues/1)). I didn't know about Wikibase! Our current plan, devised by @dhimmel (who might have thoughts on this?), is to create a YAML file for each journal in GitHub and use continuous integration to visualize them. cc @tonyR-H

Also thanks @dwhly - I've sent an email :)

**Comment by jpolka** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Nice work! Pulsed: https://www.mozillapulse.org/entry/809 🎉
