### ISSUE TITLE
Connect Chicago

### ISSUE THREAD

**Issue by deniselinn** [mozilla/global-sprint#27]
**[ Project Contact ]** @deniselinn
**[ GitHub Repo ]** https://github.com/deniselinn/connectchicago
**[ Track ]** Web Literacy, Digital Inclusion
**[ Community ]** Digital Inclusion advocates & workers in Chicago & globally 
**[ Location ]** Chicago, IL business hours CDT
### Description
I’m working with neighborhood advocates & institutions to empower Chicagoans to get involved in digital inclusion planning so that funders can support community-born ideas that are relevant to residents' priorities. 
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @deniselinn! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @chadsansing. We're here to help you through this process.

**Comment by chadsansing** [comment]
I love the focus on digital inclusion and relevancy. Please let me know how to help and send along a link to the repo once it's ready.

**Comment by deniselinn** [comment]
@chadsansing Thanks so, so much! Repo here: https://github.com/deniselinn/connectchicago < 1st issue created and more to come. Thanks!

**Comment by deniselinn** [comment]
![connect-chicago-logo](https://cloud.githubusercontent.com/assets/13007513/25446819/62995316-2a78-11e7-97c5-6ff38820dc2b.png)

**Comment by chadsansing** [comment]
This is looking great - let me know when you have a chance to customize the CONTRIBUTING.md file and we can post to Network Pulse.

**Comment by deniselinn** [comment]
This is ready for Mozilla Pulse @chadsansing

**Comment by chadsansing** [comment]
Pulsed!

https://www.mozillapulse.org/entry/344

@acabunoc, can you shift the image to vertical middle?

**Comment by abbycabs** [comment]
@chadsansing I cropped it so it less off-centered. Not sure it's better!

**Comment by chadsansing** [comment]
Thank you, @acabunoc!

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
