### ISSUE TITLE
Wikicours, the “Wikipedia of school lessons” 📝📚🏫

### ISSUE THREAD

**Issue by thomas-kuntz** [mozilla/global-sprint#270]
**[ Project Contact ]** @thomaskuntzz
**[ GitHub Repo ]** https://github.com/thomaskuntzz/wikicours
**[ Track ]** Web Literacy, Openness, 
**[ Location ]** France
**[ Coach ]** @anmechung

### Description

Wikicours is an online repository of school lessons that anyone can improve through a wiki ✏️📚

Help us build the “Wikipedia of school lessons”, change education and make it more open for the better! 🏫📝 🆓🎓

Anyone can help, check out [our GitHub repo](https://github.com/thomaskuntzz/wikicours) to see how! 👋

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @thomaskuntzz! I updated this issue to include your checklist for registration :)

**Comment by thomas-kuntz** [comment]
Thanks a lot, I'll complete that as soon as possible! 😊

**Comment by thomas-kuntz** [comment]
So, I’d like to get featured on Mozilla Pulse for the sprint, but it requires to create a CONTRIBUTING.md file. I put instructions about how to contribute on the README in a dedicated section, because creating a specific file is a little overkill for what I have to say. I'll do it in the future to explain precisely how to create a PR, fork, technically make changes to the site, but as of now this is not essential for the kind of contributions I would like to get.

So as it is now, is my project ready to be featured on Mozilla Pulse? 🙂

**Comment by abbycabs** [comment]
Hi @thomaskuntzz,

When you have a sparate CONTRIBUTINg.md file, github will prompt newcomers to your repo to read it & review. This is why we require featured projects to have a separate contributing file.

**Comment by thomas-kuntz** [comment]
Okay, thanks for the answer, got it, I'll write a CONTRIBUTING.md then... 😊

**Comment by thomas-kuntz** [comment]
I was about to submit Wikicours to Mozilla Pulse, but I got an error saying that the text inside “Why might this be interesting to other people in our network?” has to be less than 300 characters.

I'm wondering how my submission will look like once published on the site, and when I compare to the entries already published for other projects I can't really figure out which fields of the form will be in which part of the site (how do we even do line breaks in the form?).

**Comment by thomas-kuntz** [comment]
I see that some projects have two paragraphs under their image and "visit" button that, put together, largely exceed 300 characters. Are these the description and then the "why might be interested" paragraphs?

**Comment by anmechung** [comment]
@thomaskuntzz the purpose of the "why might this be interesting to other people in the network?" should focus on less of a description about the project, but an opportunity to add something in addition.  Don't feel as if you have to add anything either.  I often leave it blank.

**Comment by thomas-kuntz** [comment]
Okay, thanks!

**Comment by thomas-kuntz** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by anmechung** [comment]
Done!

**Comment by thomas-kuntz** [comment]
Cool, thanks a lot! 😊

Would it just be possible to change the title of the post form “Wikicours” to “Help us build Wikicours, the Wikipedia of school lessons! 📝📚” (when writing my entry, I thought “title” was the title of the project, not the title of the submission 😅)

**Comment by anmechung** [comment]
@thomaskuntzz it’s not so easy to change once it’s been approved on pulse.  I think it is good the way it is! However you could resubmit another one, and @acabunoc can delete the first one.

**Comment by thomas-kuntz** [comment]
Too bad... If it's impossible then I guess it'll stay as is... Thanks anyway! 🙃

**Comment by anmechung** [comment]
See revised note: you can submit another and the first one can be deleted!

**Comment by thomas-kuntz** [comment]
Oh, yeah, that's right, I forgot that. Thanks, I might do this then, now that I see know it looks like when published 😊

**Comment by anmechung** [comment]
Consider adding a photo if you decide to resubmit.

**Comment by thomas-kuntz** [comment]
Yes, I'll see if I can find something 🌄
