### ISSUE TITLE
PREreview: post, read, and engage with preprint reviews

### ISSUE THREAD

**Issue by SamanthaHindle** [mozilla/global-sprint#271]
**[ Project Contact ]** @SamanthaHindle
**[ GitHub Repo ]** https://github.com/SamanthaHindle/preprint_JournalClub
**[ Track ]** Openness, 
**[ Location ]** I will be in New York, but I will likely be sprinting later in the evening. Other members of the team will hopefully be sprinting from the UK and Canada
**[ Coach ]** @tpoisot

### Description
PREreview seeks to diversify peer review in academia by crowdsourcing pre-publication feedback to improve the quality of published scientific output. To enable this diversification, we aim to train early-career researchers in how to review others’ scientific work, and help them gain recognition and entry into the peer review process. We believe that empowering early-career researchers with these skills will facilitate a cultural shift towards a more open and constructive peer review process.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by SamanthaHindle** [comment]
@tpoisot and @acabunoc This is ready to be featured on Mozilla Pulse 🎉  ❤️

**Comment by tpoisot** [comment]
:white_check_mark: 

![screenshot from 2018-05-08 13-15-29](https://user-images.githubusercontent.com/579329/39772050-24d26f04-52c2-11e8-9689-db2916538881.png)

:tada:

**Comment by SamanthaHindle** [comment]
Thanks @tpoisot You're a superstar! ⭐️

**Comment by npscience** [comment]
@dasaderi this issue has been the one tagged with eLifeSprint — did you want to add the info from your eLife Sprint GDoc and all the outputs? That would be really helpful. Thank you!
