### ISSUE TITLE
OpenReflectometry project

### ISSUE THREAD

**Issue by daguiam** [mozilla/global-sprint#273]
**[ Project Contact ]** @daguiam
**[ GitHub Repo ]** https://github.com/OpenReflectometry/scikit-reflectometry
**[ Track ]** Openness, 
**[ Location ]** Lisbon, Portugal, GMT

### Description
Reflectometry researchers must understand plasma physics, microwave propagation, RF electronics and data processing; taking months to years browsing publications and dissertations, before becoming productive. The Open Reflectometry Project aims i) to facilitate the knowledge transfer and collaboration between reflectometry researchers; ii) to educate plasma physicists and engineers that use reflectometry data; iii) and to improve the transparency and reliability of reflectometry diagnostic data.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by aariops** [comment]
Hey @daguiam 

Will you be at Lisbon's event Globa Sprint? It'd be great to have you on board! :) 

https://ti.to/Mozilla/global-sprint-lisboa18

**Comment by daguiam** [comment]
@aariops We're planning to be there!

**Comment by abbycabs** [comment]
Hey @daguiam 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by daguiam** [comment]
The GitHub repository is at https://github.com/OpenReflectometry/scikit-reflectometry/

**Comment by daguiam** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Looks great, just left one issue: https://github.com/OpenReflectometry/scikit-reflectometry/issues/5

Other than that, we're good to go!
Pulse: https://www.mozillapulse.org/entry/817
