### ISSUE TITLE
Code Sleep Python

### ISSUE THREAD

**Issue by prateekiiest** [mozilla/global-sprint#277]
**[ Project Contact ]** @prateekiiest
**[ GitHub Repo ]** https://github.com/prateekiiest/Code-Sleep-Python
**[ Track ]** Web Literacy, Openness, Digital Inclusion, 
**[ Location ]** India, UTC + 05:30
**[ Coach ]** @meghanlazier

### Description
The project presents a curated list of desktop applications, games and machine learning application using python. We are currently into making more desktop applications using python which can be ported in cross-platforms and used by many. We are also focusing on integrating machine learning applications into this desktop applications to solve particular problems and make it more convenient
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by prateekiiest** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by meghanlazier** [comment]
Hi @prateekiiest - your project is now live on Pulse! https://www.mozillapulse.org/entry/763

**Comment by accakks** [comment]
Interested!

**Comment by cmd16** [comment]
Interested!

**Comment by prateekiiest** [comment]
Great!!

**Comment by yayimadinosaur** [comment]
interested!

**Comment by prateekiiest** [comment]
Join Slack [here](https://join.slack.com/t/code-sleep-python/shared_invite/enQtMzE0NTIwNzY0MTM1LWFhNGY0NWQ0MDIxNjZmMzgyMzlhOTk3YTY4YjQwNjJmOGIyMTZiNzA4MzkwZWE0ZjgyOWQ2MmMzMWJlMDExMjY)

**Comment by Abwas** [comment]
Hi I'm Abwas and interested in this project.

**Comment by prateekiiest** [comment]
head over to the project and slack :congratulations:

**Comment by Abwas** [comment]
Okay thanks!

**Comment by prateekiiest** [comment]
Hey all, if you want to promote the project, feel free to post it on twitter or a blog on medium
