### ISSUE TITLE
Application Frame

### ISSUE THREAD

**Issue by TitanNano** [mozilla/global-sprint#278]
**[ Project Contact ]** @TitanNano
**[ GitHub Repo ]** https://github.com/TitanNanoDE/ApplicationFrame/
**[ Track ]** Openness, Decentralization, 
**[ Location ]** Berlin
**[ Coach ]** @SamanthaHindle & @aariops

### Description
Application Frame is an open and light weight Programming Library for the Web. It's simple architecture lets the Library seamlessly argument the core features of different ECMAScript runtimes. Application Frame an it's modules allows developers to develop at the heart of the Web while enjoying enhanced comfort.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by aariops** [comment]
Hey @TitanNano ,

Welcome to MozSprint :smiley: Let us know if you need any help.

**Comment by TitanNano** [comment]
Hi @aariops. 
Thank you 😄! I will definitely get in touch once questions come up.

**Comment by SamanthaHindle** [comment]
Hi @TitanNano 

How's the README.md file coming along? Let us know if you need any help.  😃

**Comment by abbycabs** [comment]
Hey @TitanNano 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by TitanNano** [comment]
@aariops @SamanthaHindle @acabunoc is it possible to use a mozsprint IRC channel on the Mozilla IRC network? I'm currently writing down the means of communication during the sprint and wondering if that would be a possibility beside the issue tracker.

**Comment by TitanNano** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by aariops** [comment]
Hallo @TitanNano 

the project is now live on Mozilla Pulse: https://www.mozillapulse.org/entry/813 :smile: 

I am not sure about the IRC channel, @acabunoc will know better (but she is in a different time zone so it might take a while until she gets back to us). However, there is a Global Sprint room on [Gitter](https://gitter.im/), which should help with more immediate communication. It's `mozilla/global-sprint`

Hope this helps!
