### ISSUE TITLE
Localweb

### ISSUE THREAD

**Issue by ghost** [mozilla/global-sprint#279]
**[ Project Contact ]** @drashti4
**[ GitHub Repo ]** https://github.com/drashti4/localisationofschool
**[ Track ]** Web Literacy, Digital Inclusion, 
**[ Location ]** UTC+5:30
**[ Coach ]** @erindcole

### Description
We are building a platform (Website) that we can load our localized web literacy video series. By delivering Video series to schools in localized language and make teacher understand how to use it. In a way we provide resources and make sure it is available whenever needed.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by erindorothy** [comment]
Hi @drashti4 ! My name is Erin. As @acabunoc mentioned, I am here to help you with any questions that may come up as you complete your check boxes. After looking through your repo, my initial ideas for improvement are for you to add some more issues for further reach. Never hurts to have more insights on how people can interact with your repo 😁

**Comment by abbycabs** [comment]
Hey @drashti4 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by ghost** [comment]
This is ready to be featured on Mozilla Pulse.

**Comment by abbycabs** [comment]
Hey @drashti4 - I couldn't find your submission on Pulse

**Comment by ghost** [comment]
I submitted. May be I'm still in last OLT round processes :P

**Comment by zee-moz** [comment]
This project is on Pulse! https://www.mozillapulse.org/entry/825
