### ISSUE TITLE
Media Choreographies

### ISSUE THREAD

**Issue by JoBCB** [mozilla/global-sprint#280]
**[ Project Contact ]** @JoBCB
**[ GitHub Repo ]** https://github.com/JoBCB/choreo-graphic_code-assemblage-1-
**[ Track ]** Web Literacy, Digital Inclusion, 
**[ License ]** CC-BY
**[ Location ]** Marocco (GMT+1)  - Thursday May 10th from 8 to 11 am
**[ Location ]** The Netherlands (GMT+2)   - Friday May 11th from 8 to 11 pm
**[ Coach ]** @Wiroll & @psubhashish 

### Description
A transdisciplinary project which interweaves web languages & environments with choreographic practices. Questioning how may creative coding practices interfere deeper with interface design, information displays & accessibility when considering new vocabularies, embodiment and new movement perception possibilities. The goal is to create alternative circuits in the technological sphere of the web and the possible encounters with the sensory-motor structures that regulate our bodies & movements. 
***

## Want to contribute to this project during #mozsprint?

Would be great to hear any comments on the project, either on potential forms of application; code improvement or conceptual input! I created an etherpad for this purpose: https://public.etherpad-mozilla.org/p/Media_Choreographies ; otherwise feel free add your comment to this github page below!

Some further information on the research and examples of its implementation may be found here: https://jobcb.github.io/ and the code here: https://github.com/JoBCB

So far I have been engaging in live coding events, exploring different formats from improvised algorithmic performances to collaborative/ multi-location coding sessions, often involving critical discussions on open software practices, inclusion and gender balanced communities.

Looking forward to hearing from you ~

**Comment by abbycabs** [comment]
Hi @JoBCB! I've listed these repos for your project
https://github.com/repos/JoBCB/-rehearsal-series-at-Aarhus-University
https://github.com/repos/JoBCB/Choreo-Graphic-Coding_MediaLab
https://github.com/repos/JoBCB/choreo-graphic_code-assemblage-1-
https://github.com/repos/JoBCB/circulo-meio
https://github.com/repos/JoBCB/Integrated_Digital_Media_NYU
https://github.com/repos/JoBCB/jobcb.github.io
https://github.com/repos/JoBCB/Kinect-Shadow-Dance
https://github.com/repos/JoBCB/TheBody_RehearsalSeries
https://github.com/repos/JoBCB/Ways_Of_Moving_Butoh
https://github.com/repos/JoBCB/Ways_Of_Moving_Tango
https://github.com/repos/JoBCB/workshop_choreo_Wdka

 Let me know if I'm missing anything!

**Comment by psubhashish** [comment]
Hi @JoBCB any updates on the info that Abby shared earlier?

**Comment by abbycabs** [comment]
Hey @JoBCB 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by abbycabs** [comment]
Hi @JoBCB 

Since you haven't completed your registration and the Global Sprint has started, I'll be closing this issue. You're welcome to re-open this and join the Sprint if you find time to complete registration!

**Comment by JoBCB** [comment]
Hi @acabunoc  @psubhashish! I am registered to the Global Sprint and will be online in the next few hours, how can I re open the issue?

**Comment by abbycabs** [comment]
@JoBCB please provide a repository you'll be working on & complete the tasks above
