### ISSUE TITLE
Blask

### ISSUE THREAD

**Issue by zerasul** [mozilla/global-sprint#281]
**[ Contacto del Proyecto ]** @zerasul
**[ Repositorio de GitHub ]** https://github.com/zerasul/blask
**[ Categoría ]** ALFABETIZACIÓN WEB, 
**[ Ubicación ]** Tenerife (UTC+2)
**[ Coaches ]** @mattdark y @lasr21

### Descripción
Blask es un motor para blog basado en Blask y escrito en python que permite crear un blog usando solo Markdown.
***

## ¿Quieres contribuir a este proyecto durante el #mozsprint?
Únete a nosotros en el Global Sprint, Mayo 10-11. ¡Deja un comentario abajo si te interesa contribuir a este proyecto durante el #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @zerasul 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by zerasul** [comment]
Hi @acabunoc 

I think the project is ready for show on Mozilla Pulse. Only one thing the form has been succesfuly sended but i think i forgot to add the ```mozspring``` and ```2018``` tags. The project is now on moderation so i can't modify it right now. But i think that all the points are made.

**Comment by abbycabs** [comment]
This looks good! I left one issue in your repo: https://github.com/zerasul/blask/issues/37

Other than that, this is good to go!
Pulse: https://www.mozillapulse.org/entry/812 🎉 
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
