### ISSUE TITLE
Open Transport

### ISSUE THREAD

**Issue by ghost** [mozilla/global-sprint#282]
**[ Project Contact ]** [Oliver Brammer <oliver at octo dot im>](https://tuxspace.net/@octobyte)
**[ GitHub Repo ]** https://gitlab.com/opentransport/directory
**[ Track ]** Web Literacy, Openness, Decentralization, 
**[ Location ]** Manchester, United Kingdom (BST) | Attending London event
**[ Coach ]** @Wiroll & @psubhashish

### Description
Aggregating & transforming public transport data across multiple countries and cities; with the end goal of producing a one-for-all API. The API can be deployed to your own server, with the ability to bring your own data. At present, the project is very much a prototype. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by psubhashish** [comment]
Hi @ojbr, quick reminder for the points that Abby shared earlier.

**Comment by abbycabs** [comment]
Hey @ojbr 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by ghost** [comment]
@acabunoc I'd rather not be featured, since it's still early stages for the project
