### ISSUE TITLE
Moz Code Paste

### ISSUE THREAD

**Issue by amitsin6h** [mozilla/global-sprint#283]
**[ Project Contact ]** @amitsin6h
**[ GitHub Repo ]** https://github.com/amitsin6h/mozcodepaste
**[ Track ]** Web Literacy, Openness, 
**[ Location ]** Ranchi, Jharkhand and GMT+0530 (IST)
**[ Coach ]** @jamjwait

### Description
Moz Code Paste will be mozilla code paste website where user can paste their code and get review of their code.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by amitsin6h** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by jamjwait** [comment]
Thanks, @amitsin6h! Could you go back to Pulse and add the mozsprint and 2018 tags to your post?

**Comment by amitsin6h** [comment]
@jamjwait I dont see my post in my mozillapulse account how can I edit? Please help.

**Comment by amitsin6h** [comment]
@acabunoc could you please help me. I don't see my post on Pulse then how could I add tags to my post as asked by @jamjwait

**Comment by jamjwait** [comment]
Hi @amitsin6h! We're adding the tags for you and will approve the post.

**Comment by amitsin6h** [comment]
@jamjwait thanks for it :tada:

**Comment by amitsin6h** [comment]
@jamjwait let me know once you approve the post.

**Comment by jamjwait** [comment]
@amitsin6h done! https://www.mozillapulse.org/entry/781
