### ISSUE TITLE
Pro -Descriptor

### ISSUE THREAD

**Issue by Jayapreethi** [mozilla/global-sprint#284]
**[ Project Contact ]** Jaya Preethi Mohan
**[ GitHub Repo ]**  https://github.com/Jayapreethi/Pro_Descriptor
**[ Track ]** Openness, Digital Inclusion
**[ Location ]** Dr.M.G.R. Educational and Research Institute , Chennai , India.
**[ Coach ]** @quirksahern & @fimakeswork

### Description
Our Pro- Descriptor is to create a social platform for project description where users can display their project descriptions in detail and receive suggestion, queries from all genres of people and organisations. May it be a beginner or professional of any field , they can attach their project description and tag whoever they required in order to display in news feed. User can also view the statistics and reach their project description post.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by quirksahern** [comment]
Hi! Let me know if you need any assistance?

**Comment by abbycabs** [comment]
Hey @Jayapreethi 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by quirksahern** [comment]
Hi @Jayapreethi , not long now! 

Are you ready to be featured on Mozilla Pulse?
Is there anything you need help with?

**Comment by Jayapreethi** [comment]
Hello @quirksahern 
we are ready with our project files but unable to host our application . Is it okay if we upload only the files into the repository?

**Comment by quirksahern** [comment]
@acabunoc ?

**Comment by quirksahern** [comment]
@Jayapreethi I am checking with Abby, but in the meantime can you please complete the checklist. Thanks

**Comment by Jayapreethi** [comment]
@quirksahern @acabunoc I have uploaded my project . Since its my first issue I couldn't add label in to it.

**Comment by quirksahern** [comment]
What is the link to the repo?

**Comment by abbycabs** [comment]
Hi @Jayapreethi 

Since you haven't completed your registration and the Global Sprint has started, I'll be closing this issue. You're welcome to re-open this and join the Sprint if you find time to complete registration!

**Comment by Jayapreethi** [comment]
https://github.com/Jayapreethi/Pro_Descriptor
please check out this url @quirksahern

**Comment by quirksahern** [comment]
Hi,

Did you complete the online course Open Leaders 101? It contains lots of guidance on setting-up a project.

I’ve taken a look at the repository.
The information that is currently in README.md should be in CONTRIBUTING.md

The aim of the read me file is to explain what your project is about and what it hopes to achieve - then link to how to contribute.

Do you have a roadmap for the project? This will help identify specifics items you would like help with during the sprint - you can then create these as issues?

I am a conference today so will only be able to check emails sporadically.


Quirksahern


On 10 May 2018, at 05:16, Jayapreethi(JP) <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/Jayapreethi/Pro_Descriptor
please check out this url

**Comment by abbycabs** [comment]
Re-opening this at @Jayapreethi's request! Thank you for providing a repository, please complete the other tasks properly to be included in the Sprint.

**Comment by quirksahern** [comment]
@jayapreethi can you please complete the registration form and let me know when you are ready to be featured on Mozilla pulse

**Comment by quirksahern** [comment]
Also, you’ve emailed me a list of things.
Are these issues? If so, can you add them to your repo with the mozsprint label.

Thanks

**Comment by Jayapreethi** [comment]
@quirksahern 
I have already registered my project in the registration form via @acabunoc 's mail . 
https://github.com/Jayapreethi/Pro_Descriptor/issues/1
I have listed my issues for my repo https://github.com/Jayapreethi/Pro_Descriptor/issues/1 and created a label for it . Please check and let me know if anything left out

**Comment by quirksahern** [comment]
You should have multiple issues - 1 for each item.
Can you please complete the template above?

**Comment by Jayapreethi** [comment]
I have created multiple issues separately and also completed all the steps to use the template .Let me know if any pending still.

**Comment by quirksahern** [comment]
That’s great, it will make it easier for collaborators to work with you.

Unfortunately it is too late to get your project featured on Mozilla Pulse for the Sprint but this issue will remain open.

You have a really nice description of the project in this template. I think it would help anyone viewing your repo as a potential collaborator if this was included at the top of your read me file.

**Comment by Jayapreethi** [comment]
@quiksahern
Thank you !
Please feature our project in to pulse . I have been trying this for last 2
days .

**Comment by quirksahern** [comment]
@jayapreethi thank you for the hard work on your project.

Unfortunately it is too late for the project to be included on pulse, but please promo your project on social media using the #globalsprint tag

**Comment by abbycabs** [comment]
correction: #mozsprint is the hashtag!
