### ISSUE TITLE
Newbook Digital Texts

### ISSUE THREAD

**Issue by ketchley** [mozilla/global-sprint#288]
**[ Project Contact ]** @ketchley
**[ GitHub Repo ]** https://github.com/eba-diary/intern-training-documents
**[ Track ]** Web Literacy, Openness, 
**[ Location ]** Seattle, Wa
**[ Coach ]** Brianna Marshall

### Description
Testing open source project documentation created to support undergraduate student interns working to transcribe and encode 19th century Nile travel journals.  #mozsprint participants will follow the instructions to work on transcription tasks and check instructions for clarity and accuracy, and read some fascinating historical travel writing!
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @ketchley 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)
