### ISSUE TITLE
 The Field Guide to Security Training in the Newsroom

### ISSUE THREAD

**Issue by kogormanAtTGAM** [mozilla/global-sprint#289]
**[ Project Contact ]** @zenmonkeykstop
**[ GitHub Repo ]** https://github.com/OpenNewsLabs/field-guide-security-training-newsroom
**[ Track ]** Web Literacy, Internet Privacy, 
**[ Location ]** Toronto, EST
**[ Coach ]** @veerskyfire

### Description
This resource collects the advice and experience of journalists, newsroom developers, and security experts, organized into a set of lessons and training materials available for newsroom staff who find themselves leading security trainings.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by Veerskyfire** [comment]
Hello @zenmonkeykstop  @kogormanAtTGAM,
First of all i didn't understand who is the author of this project. please read all details about participation in mozsprint and go through requirements page and project template then please complete and check off the above following list for confirm registration.

**Comment by kogormanAtTGAM** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by zenmonkeykstop** [comment]
Hi @Veerskyfire - sorry, I messed up and used my work a/c for the issue creation. Authors are @zenmonkeykstop (myself) @ryanpitts and @amandabee.

**Comment by zenmonkeykstop** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by zenmonkeykstop** [comment]
Hi @Veerskyfire - need anything else?

**Comment by abbycabs** [comment]
Pulsed! https://www.mozillapulse.org/entry/796 🎉 🎉 
And on the featured projects page: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

**Comment by ryanpitts** [comment]
🎉 🎉
