### ISSUE TITLE
Your Personal Data and You

### ISSUE THREAD

**Issue by anmechung** [mozilla/global-sprint#290]
**[ Project Contact ]** @anmechung, @daviserinanderson
**[ GitHub Repo ]** https://github.com/mozilla/web-lit-core, https://github.com/mozilla/web-lit-core/issues/26
**[ Location ]** CDT, EDT
**[ Coach ]** @jamjwait

### Description
As part of the Mozilla's web literacy core curriculum, we'd like to create an activity that helps people understand what their personal data is online, where this data lives, and how best to protect their personal online data.  Rather than reinvent the wheel, what are existing activities/projects/curriculum that you have used, think is good, and would be useful to include in a "Your Personal Data and You" open source activity?  
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by smcnally** [comment]
I've got relevant interactive and text content we could shape into activities to help people understand their personal data online. 

I'll check out [web-lit-core](https://github.com/mozilla/web-lit-core). Please let me know if you have guidance upfront for me. 
![ff_lightbeam_cookies_private-mode_snippet](https://user-images.githubusercontent.com/850878/39794545-d9bb9674-5318-11e8-9c81-3073c6426308.gif)

![ff_fb_container-snippet](https://user-images.githubusercontent.com/850878/39794552-e08b3cc0-5318-11e8-9e5d-e99222711d79.gif)

[![image](https://user-images.githubusercontent.com/850878/39794699-a213cb0a-5319-11e8-92f4-e1e09a3efea3.png)](https://www.forbes.com/sites/smcnally/2011/06/30/your-digital-wake/)

**Comment by anmechung** [comment]
@smcnally Thank you! This is great. Will be in touch.

**Comment by DiegoPino** [comment]
Hi, this project from Prof. Tim Berners-Lee (That Tim Berners-Lee) has a refreshing approach on personal data ownership, portability, authentication, and WebSem.

https://solid.mit.edu

They even have a working implementation of a server and I had the luck and fun to test it 
https://github.com/solid/node-solid-server

**Comment by VasantJ3** [comment]
Hello @anmechung  , I am Vasant Joseph. I am a class 12 student. I have skills in designing(Photoshop, premiere pro), presentation, and anything which is given to me, which I can do. I am sincere to my work. If there is anything which I can do to help, please inform me. This is my first time at Mozilla global sprint.
I have experience by participating in a variety of hackathons

**Comment by codefusser** [comment]
Perhaps, there could be subscription plans on these online platforms that would restrict their systems from making use of their subscribers data in any unauthorized manner.

**Comment by passcarlean** [comment]
interested

**Comment by codefusser** [comment]
basically, data is used for financial gain so if you feel inconvenienced having your data used by third parties for financial gain, then you might have to pay a compensation for not using your data.

**Comment by smcnally** [comment]
Here's [a Personal Data intro activity prototype](https://games.gamepath.io/2018/05/11/mozilla-your-personal-data-and-you/) you can play, @anmechung.

It promotes related Personal Data resources on eff.org, mozilla.org, others. We can update the copy, links, colors you see. I'll follow up with examples embedding this within relevant articles and activities. Please let me know if you have feedback or if I can answer any questions. 
[![image](https://user-images.githubusercontent.com/850878/39951606-6e59c8a4-5559-11e8-9dff-7795a7c1fbe6.png)](https://games.gamepath.io/2018/05/11/mozilla-your-personal-data-and-you/)

**Comment by juliaem** [comment]
I like Tactical Tech's work on data and privacy for activists: https://ourdataourselves.tacticaltech.org/posts/20_intro_activism/

**Comment by ElephantNinja** [comment]
> Here's [a Personal Data intro activity prototype](https://games.gamepath.io/2018/05/11/mozilla-your-personal-data-and-you/) you can play, @anmechung.
> 

@smcnally Please update link to "Personal Data intro activity prototype". The animated gifs look great.
