### ISSUE TITLE
PREreview: post, read, and engage with preprint reviews

### ISSUE THREAD

**Issue by SamanthaHindle** [mozilla/global-sprint#291]
**[ Project Contact ]** @SamanthaHindle
**[ GitHub Repo ]** https://github.com/SamanthaHindle/preprint_JournalClub
**[ Track ]** Openness, 
**[ Location ]** I will be in New York, but I will likely be sprinting later in the evening. Other members of the team will hopefully be sprinting from the UK and Canada
**[ Coach ]** @tpoisot

### Description
PREreview seeks to diversify peer review in academia by crowdsourcing pre-publication feedback to improve the quality of published scientific output. To enable this diversification, we aim to train early-career researchers in how to review others’ scientific work, and help them gain recognition and entry into the peer review process. We believe that empowering early-career researchers with these skills will facilitate a cultural shift towards a more open and constructive peer review process.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, @SamanthaHindle! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
- [x] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [x] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/).

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or [write your own code of conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/).
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] [Follow these instructions](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) to submit your project to Mozilla Pulse.

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready to be featured on Mozilla Pulse`. Your Project Coach  will review this issue and approve your project if everything looks good :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @tpoisot. We're here to help you through this process.

**Comment by SamanthaHindle** [comment]
Hi @acabunoc Can you please delete this issue as I accidentally submitted twice. Issue 271 should be kept instead. Thanks, and sorry for the extra work! 💐 💝

**Comment by abbycabs** [comment]
haha, no worries @SamanthaHindle !
