### ISSUE TITLE
Extending and Testing a Toolbox for Longitudinal NeuroImaging data

### ISSUE THREAD

**Issue by TomMaullin** [mozilla/global-sprint#292]
**[ Project Contact ]** @TomMaullin
**[ GitHub Repo ]** https://github.com/tommaullin/SwE-toolbox
**[ Track ]** Openness, 
**[ Location ]** I am based in Oxford University in the UK and am therefore able to attend the sprint held at Mozilla London, Metal Box Factory, Suite 441, 4th Floor, 30 Great Guildford St, London SE1 0HS.
**[ Coach ]** @tpoisot

### Description
The SwE toolbox is a statistical tool for modelling longitudinal and repeated measures neuroimaging data that currently lacks any testing framework. The project consists of developing an exhaustive unit testing suite in order to validate the correctness of the current release of the toolbox, as well as using this testing suite to ensure further additions to the toolbox do not affect the results produced by the original code.

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @TomMaullin 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)
