### ISSUE TITLE
Connect: An Open Platform to Bridge Research and Citizens with Neurodevelopmental Disabilities

### ISSUE THREAD

**Issue by abbycabs** [mozilla/global-sprint#294]
**[ Project Contact ]** @r03ert0
**[ GitHub Repo ]** https://github.com/ConnectProject/100DayStarterKit
**[ Track ]** Web Literacy, Openness, Digital Inclusion, 
**[ Location ]** Paris, FR - GMT+1

### Description
We will develop an open platform allowing persons with neuro disabilities – patients, etc – to better understand their condition and to find the best strategies to help. We will build a citizen platform around neuro disabilities issues . This platform should: Provide a protocol to connect individuals; Conservation of the data, its accessibility, security, and transparency; Help participants understand data, analysis and hypothesis testing; helping with issues of neurodevelopmental disabilities.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by Aaronengelberg** [comment]
https://github.com/ConnectProject/100DayStarterKit

Hello! As a part of project, we are translating a 100-day starter kit for parents who's child has just recieved a diagnosis of autism. This whole kit has been translated page-by-page by Google Translate but we need it verified by you! If you speak French and love languages- this project is perfect for you! And with each page translated, you'll be helping us bring resources to families in need! Thank you!

**Comment by abbycabs** [comment]
added @r03ert0 as the project lead here since he'll be present during the sprint! -- thanks @Aaronengelberg

**Comment by abbycabs** [comment]
@r03ert0 & @Aaronengelberg! You're almost done registering for the sprint! Just need to add the `mozsprint` label to some issues.

If you complete the rest of the items on the list before the sprint starts, we'll get this featured :)

**Comment by Aaronengelberg** [comment]
Hi- it’s all there. Thanks!!

Aaron
