### ISSUE TITLE
WebXR for Learning

### ISSUE THREAD

**Issue by poshaughnessy** [mozilla/global-sprint#295]
**[ Project Contact ]** @poshaughnessy
**[ GitHub Repo ]** https://github.com/poshaughnessy/webxr-for-learning/
**[ Track ]** Openness, Digital Inclusion, 
**[ Location ]** London, UK
**[ Coach ]** @cbaba20

### Description
A free, open repository of Augmented Reality and Virtual Reality content / learning experiences, aimed at educators and students.

For further details, please see the Project Readme: https://github.com/poshaughnessy/webxr-for-learning/blob/master/README.md
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by cbaba20** [comment]
Hi  @poshaughnessy,
Hope You have completed all necessary steps to make it into mozilla pulse. If not then read [Guide for Project Lead](https://mozilla.github.io/global-sprint/project-lead-guide/).

Let me know if you stuck at any point.

**Comment by asela-wijesinghe** [comment]
hi im interested in your title.so what is basically trying to achieve on AR or VR? i mean business usecase

**Comment by poshaughnessy** [comment]
Hi @asela-wijesinghe, thanks for your interest in the project! Did you see the project readme yet? https://github.com/poshaughnessy/webxr-for-learning/blob/master/README.md Hopefully that answers most of it. 

In terms of the business case, that's a little bit secondary as the intention is a free and open resource. However, if it was to get taken forwards into a "real thing" then I would guess that it would most likely be funded by sponsorship or donations, or perhaps some kind of premium tier or support services.

**Comment by ghost** [comment]
Hi there, I wanna work with this project. I have a hands-on experience with Mozilla's WebVR framework "Aframe". Could I know, how should I get started? Thanks.

**Comment by poshaughnessy** [comment]
Hi @Soundharyaam, thanks for your interest in the project!

I think the best way to get started would be to get set up running the project on your computer. There are some brief instructions in the Readme here under 'Development': https://github.com/poshaughnessy/webxr-for-learning/blob/master/README.md Just let me know if you have any issues though.

It's cool that you have experience with A-Frame. A good next step might be to try out [aframe-xr](https://github.com/mozilla/aframe-xr), which is the experimental new version of A-Frame designed to cater for Augmented Reality, as well as Virtual Reality.

The website is brand new this Sprint, so it is only just starting to take shape, but if you take a look at what's there at the moment and have some ideas for what to add or improve (e.g. more AR/VR scenes, fixes, visual improvements etc), then please feel free to make a Pull Request!

I will update the Issues list in just a moment too.

**Comment by ghost** [comment]
@poshaughnessy I have got the local set-up ready at my end. Would try out aframe-xr soon!

**Comment by ghost** [comment]
@poshaughnessy I can add XR demos. Could you please help me to get started?

**Comment by poshaughnessy** [comment]
Thanks @Soundharyaam! Sorry for the delay, I got your email, I'll follow up with a reply!
