### ISSUE TITLE
¡Vuela! - open science with drones - ciencia abierta con drones

### ISSUE THREAD

**Issue by vuelaendron** [mozilla/global-sprint#296]
**[ Project Contact ]** @vuelaendron
**[ GitHub Repo ]** https://github.com/vuelaendron/vuela
**[ Track ]** Openness, Digital Inclusion, Decentralization, 
**[ Location ]** Santiago, Chile y Balcarce, Argentina, GMT-3
**[ Coach ]** @cbaba20

### Description
We will prototype a drone toolkit, integrating open source hardware and software, useful for research purposes in different fields. This project is possible thanks to a Mozilla Science 2018 mini-grant. The prototype will be developed through 7 workshops in Chile and Argentina, thus helping promote the adoption of open science tools. The workshops will aim at engaging a diverse group of partners in different target groups: community organizers, farmers, scientists, researchers, students, etc.

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by vuelaendron** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by vuelaendron** [comment]
@cbaba20, this is ready to be featured on Mozilla Pulse :)

**Comment by cbaba20** [comment]
Hello @vuelaendron ,
I suggest please update two things inside your repo:
1)tag 2018 with mozsprint 
2)use label like help-required or "good first bug" and few more.

Also I may not able to find answer for this question : Why might this be interesting to other people in our network(project)? can you answer this or add to repo, if haven't added already.

rest is perfect :)

**Comment by abbycabs** [comment]
Great work!

Pulsed: https://www.mozillapulse.org/entry/810 🎉 
Featured projects: https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/
