### ISSUE TITLE
[Example Project] Dino Park 🦎 

### ISSUE THREAD

**Issue by abbycabs** [mozilla/global-sprint#297]
**[ Project Contact ]** @acabunoc & @zee-moz 
**[ GitHub Repo ]** https://github.com/acabunoc/dino-park
**[ Track ]** Openness, Web Literacy
**[ Location ]** Toronto & Gainsville

### Description
Hello! Welcome to the Dino Park Project, **a **fake** open project to help new Mozsprint participants learn how to contribute using collaboration tools.** 

This project aims to design and build the world's first open dinosaur park. There are not enough (or any) dinosaur parks in the world today featuring live dinosuars, and we hope to change that, with your help!

We are looking for feedback on the early stages of park planning. Anyone who likes dinosaurs, parks, or picnics can help-- check out our [Issues](https://github.com/acabunoc/dino-park/issues) tab for tasks to work on. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi! I'm interested in working on this project! 🦎

**Comment by zee-moz** [comment]
Hey Abby, that's great news! check out our contributor guidelines and  the listing of issues to get started. 👍

**Comment by acabunoc** [comment]
HI! I want to help!

**Comment by unclenachoduh** [comment]
🦕

**Comment by thomas-kuntz** [comment]
Love lizards! Yay! 🦎🎉🤪
