### ISSUE TITLE
Pro -Descriptor

### ISSUE THREAD

**Issue by Jayapreethi** [mozilla/global-sprint#298]
**[ Project Contact ]** Jaya Preethi Mohan
**[ GitHub Repo ]** 
**[ Track ]** Openness, 
**[ Location ]** On 10th May we are available from 10am to 2pm in our campus. On 11th May we can make it from IST 2pm-5pm in our campus.
**[ Coach ]** @quirksahern & @fimakeswork

### Description
Our Pro- Descriptor is to create a social platform for project description where users can display their project descriptions in detail and receive suggestion, queries from all genres of people and organisations. May it be a beginner or professional of any field , they can attach their project description and tag whoever they required in order to display in news feed. User can also view the statistics and reach their project description post.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, Jaya Preethi Mohan! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [ ] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [ ] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
  - new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead-guide/templates/)
- [ ] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/).

* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or [write your own code of conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/).
* [ ] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] [Follow these instructions](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) to submit your project to Mozilla Pulse.

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready to be featured on Mozilla Pulse`. Your Project Coach  will review this issue and approve your project if everything looks good :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @quirksahern & @fimakeswork. We're here to help you through this process.

**Comment by zee-moz** [comment]
Hi @Jayapreethi -- looks like this project was already registered-- see #284 ; I'm closing this issue to avoid confusion. Ping us in the [Gitter Chat](https://gitter.im/mozilla/global-sprint) with any questions. cc @acabunoc
