### ISSUE TITLE
Open Education Cooperative

### ISSUE THREAD

**Issue by OlaCzetwertynska** [mozilla/global-sprint#301]
**[ Project Contact ]** Aleksandra Czetwertyńska
**[ GitHub Repo ]** https://github.com/OlaCzetwertynska/Open-Education-Cooperative
**[ Track ]** Web Literacy, Openness, 
**[ Location ]** Warsaw, Poland UTC+01
**[ Coach ]** @chadsansing

### Description
The main goal is to bring back the spirit of cooperation and openness to the school. We want teachers to rediscover the value of creating and learning together. We invited a group of math teachers who, with the support of specialists from various fields create high-quality OER. They start by naming needs, then look for the right tools, and finally create the materials. On the basis of that work, an internet course will be created for teachers interested in open educational resources. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by chadsansing** [comment]
Hello, Aleksandra - please let me know how to help. Please also alert me here if you'd like me to review a Pulse entry when you get to it in the checklist :)

**Comment by abbycabs** [comment]
Hey @OlaCzetwertynska 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉
