### ISSUE TITLE
pump.io

### ISSUE THREAD

**Issue by evanp** [mozilla/global-sprint#304]
**[ Project Contact ]** @evanp
**[ GitHub Repo ]** https://github.com/pump-io/pump.io/
**[ Track ]** Openness, Internet Privacy, Decentralization, 
**[ Location ]** Montreal, Quebec, Canada (EDT)
**[ Coach ]** @veerskyfire

### Description
Open Source social networking server
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by Veerskyfire** [comment]
@evanp  Please read all details about participation in mozsprint and go through requirements page and project template then please complete and check off the above following list for confirm registration.

**Comment by abbycabs** [comment]
Hey @evanp please add the `mozsprint` label to some of your issues. The Sprint has started!
