### ISSUE TITLE
Artificial Intelligence on Your Screen

### ISSUE THREAD

**Issue by ashwanidv100** [mozilla/global-sprint#305]
**[ Project Contact ]** @ashwanidv100
**[ GitHub Repo ]**[ Artificial-Intelligence-on-Your-Screen ](https://github.com/wykeepace/Artificial-Intelligence-on-Your-Screen)
**[ Track ]** Openness, 
**[ Location ]** 
**[ Coach ]** Your OL5 Mentor

### Description
I want to build the Artificial Intelligence system that can easily interact face to face with anyone on display screen and it felts like it is talking to the user as a person.
***
### People
Ashwani Kumar
## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by VasantJ3** [comment]
Hello, Yes I am interested in contributing to this project. I am a class12 student, I don't know how much help I will be. But if given a work, I will sincerely do it. I have skills- Designing(Photoshop, premier pro), presentation, and anything which is given to me.

**Comment by ashwanidv100** [comment]
Thank you @VasantJ3 for showing your interest, I will appreciate it but Currently, we are looking for experienced peoples having skill sets on Machine Learning, Artificial Intelligence and Bot frameworks etc with Advance level programming Skills. Hope you can understand and I wish you luck to find the better project that matches your skill sets.

**Comment by ashwanidv100** [comment]
Hi @acabunoc, Please add the Label to our Project Issue.

**Comment by rolarblaze** [comment]
Hi Good afternoon am Roland Joseph from Lagos Nigeria

**Comment by rolarblaze** [comment]
Am interested in contributing to this project

**Comment by codefusser** [comment]
That project would require facial recognition software. data science and visual interpretation tools. but for what purpose would you want to implement such project? facial recognition software are primary for security purpose

**Comment by ashwanidv100** [comment]
Hi @rolarblaze  & @codefusser, Thanks for showing your interest, You can visit our Project repo and start working on Issues. @codefusser I think we don't require facial recognition software, We really want to take the Interaction between chatbots with Us to a new level and that not ends there-there is the whole lot more things to build with it.

**Comment by sayodumade** [comment]
I don't know how much help I will be. But if given a work, I really want to contribute my quota but i dont know where to start from . I have skills in  Designing(Photoshop, premier pro), presentation. this is really going to be the future of technology

**Comment by codefusser** [comment]
You didn't state the solution as though you wanted a text-only bot system, face to face interaction sounds as though you meant facial recognition with the user. So that if someone else faces the system the solution would recognise that. Anyways thumbs up👍

**Comment by ashwanidv100** [comment]
Hi @sayodumade, Thank you for showing interest, And Yes presently we don't require those skills but you can check it out our Project repo and Issues may you can find something interesting to do or maybe in future.

**Comment by ashwanidv100** [comment]
@codefusser, I think you didn't get our point of direction what we trying to do, I am hoping you visited our project repo and go through [README.md](https://github.com/wykeepace/Artificial-Intelligence-on-Your-Screen/blob/master/README.md) completely. We are trying to build face to face interaction chatbot which mainly uses device speaker and camera, Speaker that required for direct Input/output conversation and the camera required for face recognition for a user, but only for the one purpose and i.e our AI chatbot can check it out what kind of expression user been making so it can change its own expressions in its own way. We are going to use Unity 3D to build any random face (any graphical charters we used to see in games). So it can interact in the same way that you feel like you are really talking to someone. I am Hoping now you can understand what we are trying to build but it a long way to go. We are looking forward to the contributors to help.

**Comment by codefusser** [comment]
That was the exact picture I had in mind.
