### ISSUE TITLE
Infosec Bytes

### ISSUE THREAD

**Issue by juanluispassarelli** [mozilla/global-sprint#306]
**[ Project Contact ]** Infosec Bytes
**[ GitHub Repo ]** 
**[ Track ]** Web Literacy, Internet Privacy, 
**[ Location ]** London
**[ Coach ]** @veerskyfire

### Description
Online course for journalists to help them secure their data and communications
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, Infosec Bytes! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [ ] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [ ] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
  - new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead-guide/templates/)
- [ ] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your coach, @Veerskyfire. We're here to help you through this process.

**Comment by Veerskyfire** [comment]
@juanluispassarelli Please read all details about participation in mozsprint and go through requirements page and project template then please complete and check off the above following list for confirm registration. Please add your project repo here so people can contribute to it.

**Comment by abbycabs** [comment]
Hi @juanluispassarelli 

Since you haven't completed your registration and the Global Sprint has started, I'll be closing this issue. You're welcome to re-open this and join the Sprint if you find time to complete registration!
