### ISSUE TITLE
iSpooge Live

### ISSUE THREAD

**Issue by harlanji** [mozilla/global-sprint#307]
**[ Project Contact ]** @harlanji
**[ GitHub Repo ]** https://github.com/harlanji/ispooge
**[ Track ]** Internet Privacy, Decentralization, 
**[ Location ]** San Francisco, CA -- Pacific
**[ Coach ]** @princiya

### Description

iSpooge Live is a boilerplate for sovereign video websites including live streaming. It allows syndication via RSS and social features are optional.

In other words, one can create a YouTube or Twitch-equivalent website out of the box and customize it from as little as a RasPi or small cloud instance using Docker. It can be offline and private or support going viral by adding a simple CDN to the read path; taking advantage of the read and write path separation baked into the system.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi @harlanji - please add the `mozsprint` label to some of your issues. The Sprint has started!
