### ISSUE TITLE
facebook.tracking.exposed

### ISSUE THREAD

**Issue by vecna** [mozilla/global-sprint#308]
**[ Project Contact ]** @vecna
**[ GitHub Repo ]** https://github.com/tracking-exposed/facebook and https://github.com/tracking-exposed/web-extension
**[ Track ]** Web Literacy, Openness, Internet Privacy, 
**[ Location ]** Berlin, GMT+2
**[ Coach ]** Your OL5 Mentor

### Description
facebook.tracking.exposed is a tool for user and researchers. Permits to assess how facebook algorithm personalizes your experience, it memorize the posts and enable comparison; it coult help to understand the discourses on the network, but we have to figure out the privacy-preserving way to do the query on the database. Has been used recently for this research by the WebFoundation https://webfoundation.org/research/the-invisible-curation-of-content-facebooks-news-feed-and-our-information-diets/
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hey @vecna! Please add the `mozsprint` label to some of your issues. The Sprint has started!
