### ISSUE TITLE
friends

### ISSUE THREAD

**Issue by JacobEvelyn** [mozilla/global-sprint#310]
**[ Project Contact ]** @JacobEvelyn
**[ GitHub Repo ]** https://github.com/JacobEvelyn/friends
**[ Track ]** Openness, 
**[ Location ]** Atlanta, GA, Eastern Time
**[ Coach ]** @quirksahern & @fimakeswork

### Description
a command-line program that helps you to keep track of your relationships with the people you care about
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by codefusser** [comment]
how does that work and for which platform?

**Comment by JacobEvelyn** [comment]
Good question, @codefusser! More details are in the README, but it's a command-line program that should work on any platform as long as you have Ruby installed (Ruby comes installed on Windows, Mac, and Linux machines). You should be able to install it with either `gem install friends` or `sudo gem install friends` in your terminal or shell.

Let me know if you run into any issues or have any questions!

**Comment by codefusser** [comment]
I've viewed the repo but there were too many code lines to grasp. In which database will the contact details be stored and could the program be used for other social media platforms, like facebook?

**Comment by JacobEvelyn** [comment]
Good questions, @codefusser! The program doesn't "plug in" to any social media platforms; it's more like a journal where you can type into your terminal:

```
friends add activity "I went out to lunch in _London_ with my friends **Samantha** and **Tyrone**."
```

And that will be recorded in a file on your computer called `friends.md` which stores the date and time of the activity, as well as a list of all of your friends and the locations of your activities. Everything is stored in that one file (not in a database), and you can open it in a text editor and read it yourself.

There are lots of other features but that's a bit about how to get started! More details are in the [command reference section of the README](https://github.com/JacobEvelyn/friends#command-reference)!

**Comment by sayodumade** [comment]
i think that should be user friendly stuff without having to use a command line so as to be generally accepted

**Comment by JacobEvelyn** [comment]
@sayodumade I'm not sure I totally follow your suggestion. Could you elaborate on what you're thinking?
