### ISSUE TITLE
Ciberseguras

### ISSUE THREAD

**Issue by libertnat** [mozilla/global-sprint#311]
**[ Contacto del Proyecto ]** Indira Cornelio
**[ Repositorio de GitHub ]** https://ciberseguras.org
**[ Categoría ]** PRIVACIDAD Y SEGURIDAD, 
**[ Ubicación ]** Ciudad de México GTM -5
**[ Coaches ]** @mattdark y @lasr21

### Descripción
Es una plataforma en línea que recupera recursos sobre género, feminismo, autocuidado y autodefensa digital y tecnología. También coordinamos aquelarres ciberfeministas donde nos juntamos con otras mujeres para compartir aprendizajes. Ciberseguras somos Clandestina (Brasil) , Ciberfeministas GT (Guatemala), Derechos Digitales (Chile-México), Dominemos la tecnología - APC, Luchadoras (México), Nodo Común (Bolivia), SocialTIC (México). 

***

## ¿Quieres contribuir a este proyecto durante el #mozsprint?
Únete a nosotros en el Global Sprint, Mayo 10-11. ¡Deja un comentario abajo si te interesa contribuir a este proyecto durante el #mozsprint 2018!

***

## Nota para el Líder de Proyecto :tada:
¡Felicidades, Indira Cornelio! Este es el listado oficial de tu proyecto para el Mozilla Global Sprint 2018. Para confirmar tu registro, por favor completa y marca lo siguiente:

- [ ] Completa el curso [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Proporciona en un comentario un repositorio de GitHub para trabajo y discusión sobre tu proyecto 
- [ ] Crea un archivo README en el repositorio de tu proyecto. Este archivo ayudará a los recién llegados a entender cuál es tu proyecto, porque es importante, y la ayuda que estás buscando.
- [ ] [Crea el archivo: LICENSE] (http://choosealicense.com/) para asignar a tu proyecto una licencia abierta, permitiendo que pueda compartirse y remezclarse.
- [ ] Activa el [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) y crea al menos tres issues para describir cada tarea en la que necesitas ayuda y cómo un contribuidor puede empezar con esa tarea.
- [ ] [Crea una etiqueta](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) llamada `mozsprint` y asígnala a tus issues.

#### Lista de verificación para Proyectos DESTACADOS :clipboard:
Para tener tu proyecto DESTACADO en [Mozilla Pulse](http://mozillapulse.org/), completa la siguiente documentación. En los Sprints pasados, los proyectos bien documentados tienen 5 veces más contribuciones que otros proyectos. Detalles de cada item y más información sobre como crearlos puedes encontrarla [en nuestra Página de Requerimientos](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/).

* [ ] En tu archivo README, pon un link a las [Guias de participación en la comunidad de Mozilla](https://www.mozilla.org/es-ES/about/governance/policies/participation/) o escribe un código de conducta propio.
* [ ] Crea el archivo: CONTRIBUTING.md así los demas podrán saber como participar. Si lo deseas puedes [remezclar este template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING_es.md)
* [ ] [Llena esta forma](https://www.mozillapulse.org/add) para agregar tu proyecto a Mozilla Pulse. Agrega las etiquetas  `mozsprint` y `2018`.

Una vez que todo lo anterior este completo,
- [ ] Deja un comentario con el texto ‘Listo para aparecer en Mozilla Pulse’. El encargado revisará el issue y aprobará tu proyecto si no hay ningún problema. balloon:

Si te atoras en algún punto, no dudes en consultar la [página de requerimientos] (https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) y la [plantilla de proyectos](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) o contacta a uno te los coaches de proyectos @mattdark y @lasr21 . ¡Estamos aquí para ayudarte en el proceso!

**Comment by abbycabs** [comment]
Hi @libertnat 

Since you haven't completed your registration and the Global Sprint has started, I'll be closing this issue. You're welcome to re-open this and join the Sprint if you find time to complete registration!
