### ISSUE TITLE
Exokit

### ISSUE THREAD

**Issue by avaer** [mozilla/global-sprint#314]
**[ Project Contact ]** @modulesio
**[ GitHub Repo ]** https://github.com/webmixedreality/exokit
**[ Track ]** Openness, Decentralization, 
**[ Location ]** Kitchener ON, Canada, EST
**[ Coach ]** @aj-ptw

### Description
AR/VR browser for the post-screen age.

Exokit is a new browser written in Javascript, which runs as a node module. It can't do HTML rendering, but it can do Magic Leap, Leap Motion, WebGL, WebVR, gamepads, and more.

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by abbycabs** [comment]
Hi @modulesio! Make you add the mozsprint label to a few issues :) Sprint has started already!

**Comment by avaer** [comment]
Thanks for the heads up!

**Comment by avaer** [comment]
https://github.com/webmixedreality/exokit/issues?q=is%3Aissue+is%3Aopen+label%3Amozsprint

**Comment by ghost** [comment]
Hi there, I wanna work with this project. I have a hands-on experience with Mozilla's WebVR framework "Aframe". Could I know, how should I get started? Thanks.

**Comment by avaer** [comment]
Hi @Soundharyaam! We use [Slack](https://exokit.slack.com) for coordinating -- I sent an invite.

We definitely support Aframe and we could use the help!

**Comment by avaer** [comment]
There is also a [Slack auto-inviter here](https://exoslack.now.sh/).

**Comment by ghost** [comment]
Thanks. I have joined the slack group. Will collaborate over there!
