### ISSUE TITLE
Media Choreographies: API

### ISSUE THREAD

**Issue by JoBCB** [mozilla/global-sprint#315]
So far the _"Media Choreographies"_ research project has been mainly applied to live coding practices / coding on the fly. I have been publishing the scripts that server as basis for the performances: https://jobcb.github.io + https://github.com/JoBCB

An early version of: "  — A two dimensional syntax or a glossary of language for movement" can be found at: http://pzwart1.wdka.hro.nl/~jo/notebook/series/glossary.html

The next challenge would be to build an **API** which would overlay a choreographic vocabulary on existing online environments. A way to merge the frontstage (visual apperance) and backstage (code) of web platforms. Different users would be able to live code using the web console and create their own web choreographies.

The aim of the _"choreographic vocabulary"_ is to open up multiple interpretations and politics behind online interfaces. To question language standards, default movement patterns and hierarchies of information displays, and allow for other/ plural voices and understandings to be heard. I see the potential of this tool as political endeavor as much as a pedagogical artifact to engage with.

Any tips, advice, ideas on how to move forward are very welcome! Either use the comment section below or the etherpad link: https://public.etherpad-mozilla.org/p/Media_Choreographies
Thank you!!!

**Comment by abbycabs** [comment]
Hi @JoBCB - did you mean to make this in your repo? https://github.com/JoBCB/jobcb.github.io/issues

Closing this since you already have a project listing in #280! Please use that issue as your project listing.
