### ISSUE TITLE
Compatibility between Jupyter Notebooks / Binder and DAR / Texture / Stencila

### ISSUE THREAD

**Issue by nuest** [mozilla/global-sprint#317]
**[ Project Contact ]** @minrk, @nuest
**[ GitHub Repo ]** https://github.com/minrk/jupyter-dar
**[ Track ]** Openness, 
**[ Location ]** Cambridge UK, BST
**[ Coach ]** @chadsansing

### Description
Binder is an online service for running Jupyter Notebooks and other environments. Texture/Stencila are editors for reproducible research documents. We want to connect them so that users can edit reproducible documents (DAR files) as part of a binder project.

Objectives:
Understanding DAR
Launching Stencila Editor on Binder (potentially not launching anything else, i.e. w/o the Jupyter Notebook start page)
repo2docker support for DAR files

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, @minrk, nuest! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
- [x] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @chadsansing. We're here to help you through this process.

**Comment by nuest** [comment]
:tada: First demo works!

[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/minrk/jupyter-dar/master?urlpath=%2Fstencila%2F)

**Comment by nuest** [comment]
The project had some world-wide contribution. "Over night" the Stencila devs (@nokome) worked on running Jupyter contexts and contributed some code: https://github.com/minrk/jupyter-dar/pull/5

Read more at the Stencila Community: https://community.stenci.la/t/stencila-in-binder/142

And here is the direct link to a working example: https://mybinder.org/v2/gh/nokome/jupyter-dar/add-stencila-host?urlpath=%2Fstencila%2F

**Comment by nuest** [comment]
Since @stencila people are now helping out, chat about the project takes place at https://gitter.im/stencila/stencila

**Comment by nuest** [comment]
I am currently trying to get the R context working... found a mismatch in confguration file paths (see https://github.com/stencila/r/pull/22) and the RContext is listed in Stencila

![image](https://user-images.githubusercontent.com/1325054/39920920-3ad8ae04-5519-11e8-9997-6e1ecc6cff1c.png)

and errors are gone, but the code is not evaluated yet...

The error is 

```
[E 10:39:53.361 NotebookApp] 500 POST /stencila-host/RContext (172.17.0.1) 6.96ms referer=http://localhost:8888/stencila/?archive=r-markdown
```

**Comment by nuest** [comment]
**Status report**

- We have stopped working on getting R to work - see https://github.com/minrk/jupyter-dar/issues/9 (but did find a bug too: https://github.com/stencila/r/pull/22); we need help from the Stencila experts for that, but there's other stuff to do...
- @nuest works on packaging the proxy as a proper Python module, which will make installation and maintenance easier down the road (base on https://github.com/jupyterhub/nbrsessionproxy)
- @minrk works on getting https://github.com/jupyter/repo2docker ready to handle repos with Dar archives - the Docker image generation will be like magix :unicorn:

**Comment by nuest** [comment]
The Python module for the proxy also allows us to extend the Jupyter landing page with a nice button (https://github.com/minrk/jupyter-dar/issues/1): 

![image](https://user-images.githubusercontent.com/1325054/39926641-0f77f708-5530-11e8-9301-9159d3080641.png)

**Comment by nuest** [comment]
Demo works (on an inofficial binder website) :tada: :100: 

Try it at **http://binder.minrk.net/v2/gh/minrk/jupyter-dar/master?urlpath=%2Fstencila%2F**

![jupyter-dar-01](https://user-images.githubusercontent.com/1325054/39930706-b52ea9c0-553b-11e8-874e-29a909636185.gif)

**Comment by npscience** [comment]
@nuest many thanks for documenting your progress here, it's fab to have this record and all the links :100:

**Comment by nuest** [comment]
The software is ready for this to work on mybinder.org, we're working on some examples and a wrap-up blog post, see https://github.com/minrk/nbstencilaproxy/issues/12

**Comment by nuest** [comment]
@chadsansing If you're still "coaching" this, feedback on a wrap-up blog post is very welcome: https://github.com/minrk/nbstencilaproxy/issues/12#issuecomment-435974747

**Comment by nuest** [comment]
The wrap-up blog post is now online at

**https://elifesciences.org/labs/d42fe2b9/integrating-binder-and-stencila-the-building-blocks-to-increased-open-communication-and-transparency**

Some cross-posts will happen during the coming days, see https://github.com/minrk/nbstencilaproxy/issues/12 for links.

**Comment by npscience** [comment]
Fantastic read, I learnt so much about what actually happened with this project and what each of you did (although not all technical details absorbed, but that's ok for me 😄). Thank you!! :100:

**Comment by PreetiSharmaCareerGuide** [comment]
Very nice article! I'm Preeti, I write for educational blogs. I make a collection of wonderful educational blogs from where I could take inspiration for writing. This article really inspires me though it is a little different from my domain but nonetheless it is a good writing. I sometime write for a education site blogs www.clearexam.ac.in Let me know your thoughts if I could contribute to your blog too.

**Comment by nitijain123** [comment]
This is a wonderful article. I can see that you have done a lot of research and your subject knowledge is good and impressive.
This is Nitin, I also like to write for an education blog www.cleariitmedical.com - This is an online blog for students who want to prepare for India's most difficult entrance exams - IIT JEE and NEET This is a free blog and provide free study material, quiz and notes to those who can't afford to pay hefty fees of coaching institutes. I write free of cost for the good cause. I know you must be busy with your work but if you could take out some time from your busy schedule and have a look at it. I saw a good collection of articles. If you only write a few words about this blog then it can help a lot of students out there. Thanks!

**Comment by Meghabms** [comment]
Wow! Such an articulative post it is! I am a fan of your writing. Being a new writer, it's always good to see inspiring posts like this. I am a management graduate and write for 12th pass students for various career options. I write for a good blog: www.clearlawentrance.com I want to write about a lot of things out there, please guide me on how I can become a good blogger.

**Comment by Smritiwalia1** [comment]
Hey, it's Smriti. Your article is a good one. I must say not everybody knows how to write blogs and make them look professional. Being a law student I always look for data points like charts, analysis in articles. Yours seems to give justice to the topic. My personal style includes a lot of graphs, numbers and informative videos. I write on
www.successmantra.com for law related exams.

**Comment by gofacademy** [comment]
Thank you for the valuable information. I am very much impressed with this one. for more information visit - https://www.gofacademy.in/iit-jee-coaching | https://www.gofacademy.in/iit-coaching-in-kalu-sarai
