### ISSUE TITLE
Journal-independent credentialing (JIC-JACs)

### ISSUE THREAD

**Issue by Vinnl** [mozilla/global-sprint#319]
**[ Project Contact ]** @vinnl
**[ GitHub Repo ]** https://github.com/Vinnl/jic-jac
**[ Track ]** Openness, 
**[ Location ]** Cambridge UK, BST
**[ Coach ]** @gilbertslade

### Description
As a researcher I want my research to be judged fairly regardless of where it’s made public. 
Creating an alternative way to evaluate research objects and people.
Addressing obsession with prestige journals.

People: 
Vincent Tunru
Alf Eaton
Mark Patterson
Sara Bosshart
Matthias Bjornmalm

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by simonengelke** [comment]
Hi @Vinnl , very interested in this project! How could I help?

**Comment by yochannah** [comment]
@Vinnl Love your project! you might also be interested in https://github.com/yochannah/code-is-science and more specifically our [manifesto](https://codeisscience.github.io/manifesto/manifesto) (asserting code is an essential part of science that needs to be peer reviewed and credited) - feel free to share your thoughts about it (or sign up once it goes live in June <3)

**Comment by Vinnl** [comment]
Hi @simonengelke, we're currently figuring out how best to make that work, so bear with us a bit :) We're part of the [eLife innovation sprint](https://elifesciences.org/events/c40798c3/elife-innovation-sprint-2018), so we're in-person together in Cambridge, and at this point not everything we've thought of is digital. I think a good first start would be to look at our [project overview document)[https://docs.google.com/document/d/15JWB_2aqq9SVwQwMzi9agBsShoGzrKDWUPpFDZ6vwzE/edit?usp=sharing], and if you share your email address, we could add you to the Slack channel - I think? (/cc @npscience)

@yochannah Will take a look, thanks for sharing!

**Comment by simonengelke** [comment]
@Vinnl , sounds good! Thanks for the document, will keep my eye on it! I am currently at the Global Sprint in London. Feel free to also write to my username @gmail.com.

**Comment by Vinnl** [comment]
Repository here: https://github.com/Vinnl/jic-jac

**Comment by RaoOfPhysics** [comment]
@Vinnl: Can you edit the OP at the top to add the link to the second line?

**Comment by Vinnl** [comment]
Sorry, missed that - done!
