### ISSUE TITLE
Teen-driven inquiry and working in the open

### ISSUE THREAD

**Issue by dbild** [mozilla/global-sprint#32]
**[ Project Contact ]** @dbild
**[ GitHub Repo ]** https://github.com/dbild/teen-open-leadership
**[ Track ]** Web Literacy, Open Innovation, Digital Inclusion
**[ Community ]** Curriculum on the Web - wrangler: @chadsansing 
**[ Location ]** Chicago (CST)
### Description
This project is focused on adapting and modifying Mozilla's Open Leadership Training Series for a teen audience, specifically so that teens will be better equipped to launch and carry out collaborative inquiry projects and work in the open. 
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @dbild! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by dbild** [comment]
@stephwright @acabunoc I wasn't sure if this belonged in Mozilla Science. The teens I work with and my programs focus on science (urban ecology and env sci). But **this** project isn't strictly about science just like OLT isn't just for science.

**Comment by zee-moz** [comment]
@dbild this sounds like it might be more of a Learning project... we'll think a bit about where it might best fit and let you know 😸

**Comment by katemills** [comment]
I'm interested in contributing to this project!

**Comment by dbild** [comment]
@katemills I'm really happy to hear that you're interested in contributing to this project!  I'm still working on the project road map and other aspects leading up to the global sprint. I'll keep you updated as I get things posted!

**Comment by stephwright** [comment]
I LOVE this @dbild !!! Very similar to a project I want to work on involving teaching open science skills / methods to kids in elementary.

**Comment by zee-moz** [comment]
@dbild hi! This project idea sounds great-- we may have some collaborators who could help. I'm not seeing much in your GitHub repo but the boilerplate template language that you forked. I'd like to send people your way, but don't want to do so until there's a better documentation and a few more issues-- let me know if you are planning to update this. Thanks! 😸

**Comment by priyankanag** [comment]
Hey @zee-moz ,

Thank you so much for willing to help with this project. @dbild might be a little busy and thus couldn't get back to you on this. I am trying to reach-out to him and make sure we have some documentation done soon :smile:

**Comment by dbild** [comment]
@zee-moz yes I am planning to update the documentation (and thank you for keeping an eye out for potential collaborators). @priyankanag is right that I have been a little busy the past couple weeks. I'm on my way to the Citizen Science Assoc conference in the morning (so wrapping up those presentations), but hoping to get better documentation and few issues up by Monday. Apologies for the delay!

**Comment by dbild** [comment]
@chadsansing @acabunoc @zee-moz is there an easy way to get the current text for OLT into a google doc(s) for editing and commenting (other than copy-paste)?  I'm seeing this on github https://github.com/mozilla/open-leadership-training-series/tree/gh-pages/_articles  but not sure how to work with it

**Comment by dbild** [comment]
@zee-moz I've updated the documentation and created more issues.  I'm still working on some things but I think it's more or less ready to go

**Comment by dbild** [comment]
![img_20150708_110923](https://cloud.githubusercontent.com/assets/10856385/26530138/7cf7093a-4394-11e7-8e6c-de26a8f91c45.jpg)

**Comment by dbild** [comment]
This is ready for Mozilla Pulse

**Comment by chadsansing** [comment]
Pulsed!

https://www.mozillapulse.org/entry/317

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
