### ISSUE TITLE
Octopus

### ISSUE THREAD

**Issue by freeal** [mozilla/global-sprint#321]
**[ Project Contact ]** Alex Freeman
**[ GitHub Repo ]** https://github.com/octopus-hypothesis/octopus-website, https://github.com/octopus-hypothesis/octopus, https://github.com/octopus-hypothesis/Octopus-docs
**[ Track ]** Openness, 
**[ Location ]** Cambridge UK, BST
**[ Coach ]** @tpoisot

### Description
A system that breaks the traditional paper format into its component pieces, vertically and horizontally linked. Commenting, flagging and rating as a replacement for peer review. Automatic language translation and all saving to a distributed database.
 
Alessandro Dillenburg
Delwen Franzen
Simon Hazelwood-Smith
Rosario Villajos
Melissa Harrison
Kai Degrud
Hannah Drury
Ian Bruno
Emanuil Tolev

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, Alex Freeman! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
  - new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead-guide/templates/)
- [x] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @tpoisot. We're here to help you through this process.

**Comment by simonengelke** [comment]
Hey @freeal , cool project! Sounds like this other Sprint project could be of interest? https://github.com/mozilla/global-sprint/issues/271

**Comment by freeal** [comment]
Thanks - yes, we shall talk to them!

**Comment by jcmolloy** [comment]
Here are the links to the Octopus repos:

- [Octopus Organisation on github](https://github.com/octopus-hypothesis)
- [Feature list wiki](https://github.com/octopus-hypothesis/octopus/wiki/Feature-list)
- [Documentation](https://github.com/octopus-hypothesis/Octopus-docs)
- [Website Repo](https://github.com/octopus-hypothesis/octopus-website)

The team have been doing a great job!

This morning they mocked-up page designs, and Emanuil Tolev worked with Kai Segrud’s code to make some functional areas. They are excited about Amazon Translate as a tool to be completely language agnostic throughout (i.e. I as a user can type in any language and it is instantly translated - displayed to readers in language of their choice).

They now have a working version of the reviewing page and part of the team are adding automatic translation, whilst the rest work on mock-ups.

<img width="698" alt="capture" src="https://user-images.githubusercontent.com/883789/39924794-203e607c-5521-11e8-8d1c-0ded9e44095c.PNG">
