### ISSUE TITLE
WikiCiteVis

### ISSUE THREAD

**Issue by Samwalton9** [mozilla/global-sprint#322]
**[ Project Contact ]** @Samwalton9, @seanwiseman, @Davidcmoulton
**[ GitHub Repo ]** https://github.com/Samwalton9/WikiCiteVis
**[ Track ]** Openness, 
**[ Location ]** Cambridge UK BST
**[ Coach ]** @SamanthaHindle & @aariops

### Description
A tool to search and visualise Wikipedia’s citations with identifiers dataset. The tool should be able to search DOIs and DOI patterns and return both a list of DOIs cited across all language Wikipedias alongside visualisations of the data within, incorporating other relevant datasets (e.g. Unpaywall, Crossref).

Members:
Sam Walton
David Moulton
Sean Wiseman

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, @Samwalton9, seanwiseman, Davidcmoulton! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
- [ ] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [X] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @SamanthaHindle & @aariops. We're here to help you through this process.

**Comment by aariops** [comment]
Hey @Samwalton9 

Welcome to Mozilla's Global Sprint! :smile:  Let me or @SamanthaHindle know if you need any help with setting up your project

**Comment by simonengelke** [comment]
Hey @Samwalton9 , fascinating project! Let us know what could be done to help. Wondering if one could use how often documents (DOIs) are used as a reference as a metric of their helpfulness/importance (type of impact factor)?

**Comment by Daniel-Mietchen** [comment]
This looks like a great project!
Here is a similar one that @dartar was leading some years back - it's broken now but perhaps some of the ideas or code in there may be useful to you: https://github.com/wpoa/Wikipedia-Cite-o-Meter . You can see it in action, for instance, in a [talk](https://en.wikipedia.org/wiki/User:Daniel_Mietchen/Talks/Academic_Publishing_in_Europe_2012) that has been recorded, [about 26 min into the video](https://www.youtube.com/watch?v=kYKIGnF7-DM#t=26m).

**Comment by Samwalton9** [comment]
@simonengelke Certainly, and it's already being done. Altmetrics are increasingly using Wikipedia citations as a measure of impact: https://help.altmetric.com/support/solutions/articles/6000060980-how-does-altmetric-track-mentions-on-wikipedia-

@Daniel-Mietchen Thanks for the link, that's really useful!

**Comment by Samwalton9** [comment]
Updates:

We now have the tool returning results from via an API, the search designed and being implemented, and the visualisations discussed and prioritised. You can follow progress on the Project board: https://github.com/Samwalton9/WikiCiteVis/projects/1

**Comment by Daniel-Mietchen** [comment]
@Samwalton9 Where can we see it in action?

**Comment by Samwalton9** [comment]
Nowhere yet, unfortunately. Working on it!
