### ISSUE TITLE
Qualitative Data Analysis with Zotero

### ISSUE THREAD

**Issue by Bubblbu** [mozilla/global-sprint#324]
**[ Project Contact ]** @Bubblbu
**[ GitHub Repo ]** https://github.com/Bubblbu/zotero-insights
**[ Track ]** Openness, 
**[ Location ]** Cambridge, UK BST
**[ Coach ]** @tpoisot

### Description

FOSS alternative to commercial QDA software (Atlas.ti/NVivo) to provide point & click text analysis based on Zotero. In addition to quantitative text analysis, it should be possible to include user created annotations in the analysis. During the Sprint we are aiming to evaluate different technical solutions and create a simple working example.

### People

Asura Enkhbayar
Achintya Rao
Richard Smith-Unna

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, @Bubblbu! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
  - new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead-guide/templates/)
- [ ] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @tpoisot. We're here to help you through this process.

**Comment by Derek-Jones** [comment]
Hi @Bubblbu,

Were you in London for the sprint today?  If so, it's a shame we did not get to talk.

pdf-2-csv is something I have been working on:
https://github.com/mozilla/global-sprint/issues/293
