### ISSUE TITLE
Appstract: The Publication Annotation Sensation!

### ISSUE THREAD

**Issue by akeshavan** [mozilla/global-sprint#325]
**[ Project Contact ]** @akeshavan
**[ GitHub Repo ]** https://akeshavan.github.io/brainspell-neo-frontend/#/game 
**[ Track ]** Openness, Digital Inclusion, 
**[ Location ]** Cambridge UK, BST
**[ Coach ]** @cbaba20

### Description
A tap game to submit sample size for badge rewards. It’s going to be a mobile game, fun & easy. Aim is to have a working prototype for Friday’s demo.
Members:
Anisha Keshavan
Sam G
Nuno
Charlotte Whicher
Peter Murray-Rust
Jennifer Spencer 
Andreea Hrincu

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, @akeshavan! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
- [ ] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @cbaba20. We're here to help you through this process.

**Comment by jcmolloy** [comment]
Great progress from the TapdaNce/Appstract team today! Really nice looking screen shot, domain registered and help documents on the way!

<img width="1256" alt="screen shot 2018-05-11 at 09 46 53" src="https://user-images.githubusercontent.com/883789/39922977-ab914f7a-5519-11e8-84df-e286ff7aa151.png">

**Comment by jcmolloy** [comment]
And now a working demo!

![](https://media.giphy.com/media/fxR1CmdpkHMVVarKlp/giphy.gif)

**Comment by akeshavan** [comment]
The working demo is at https://appstract.pub !
