### ISSUE TITLE
Hack the Water Crisis

### ISSUE THREAD

**Issue by GienSRG** [mozilla/global-sprint#328]
**[ Project Contact ]** @GienSRG
**[ GitHub Repo ]** https://github.com/oscedays/hackthewatercrisis
**[ Track ]** Openness, Digital Inclusion, Decentralization, 
**[ Location ]** Cape Town
**[ Coach ]** @drashtipandya1

### Description
Developing a global design commons for the global water crisis
***
There is an increasing number of water stressed cities in the world. This [OSCEdays](https://oscedays.org) seeks to mobilize open source circular design innovators around the globe to help contribute to a global water design commons to help communities mitigate water crisis and make them more resilient.

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018, or talk to us on our [Gitter channel](https://gitter.im/oscedays-community). If you are living in a water stressed city, join other innovators at OSCEdays to co-design water innovation. We can also help you to organize a local water crisis hackathon, learning from [our hackathon](http://www.hackthewatercrisis.org/)  experience during the Cape Town water crisis. All designs are under creative commons license, stored in a common global knowledge commons at OSCEdays that anyone in the world can access. 

***

## Note to the Project Lead :tada:
Congrats, @GienSRG! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
- [x] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [x] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your OL5 Mentor. We're here to help you through this process.

**Comment by GienSRG** [comment]
Hi Abby, can you pulse?

**Comment by abbycabs** [comment]
HI @GienSRG, you had to start registration before April 30 to be eligible to be featured on Pulse. It wouldn't be fair to feature you at this point. Thanks for submitting your project!

**Comment by GienSRG** [comment]
No problem. I understand.
