### ISSUE TITLE
Open Stories

### ISSUE THREAD

**Issue by chealsye** [mozilla/global-sprint#329]
**[ Project Contact ]** @chealsye
**[ GitHub Repo ]** https://github.com/OpenStories/
**[ Track ]** Openness, 
**[ Location ]** Colorado, USA - US Mountain Time
**[ Coach ]** Your OL5 Mentor

### Description
Open Stories aims to gather success stories of Open advocates and practitioners to show that a successful Open career is possible. By collecting Open success stories and making them discoverable by storyteller location, discipline, career level, and language, we can better represent the success stories of open practitioners and encourage other researchers to go Open. During #mozsprint, we will be focusing on creating [website prototype](https://github.com/OpenStories/website/issues/1) and [recording guide](https://github.com/OpenStories/docs/issues/1).
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018! Reading [the welcome document](http://bit.ly/OpenStoriesMozSprint) is a great first step to introduce yourself to the project.

**Comment by chealsye** [comment]
`This is ready to be featured on Mozilla Pulse`. @acabunoc - I assume it is too late, but wanted to follow the full checklist!

**Comment by Genesisz** [comment]
hey guys. i am Genesis from the Nigeria sprint center. 
is this group still opened?
