### ISSUE TITLE
Reproducible Paper Template for Computational Research Using Popper

### ISSUE THREAD

**Issue by ivotron** [mozilla/global-sprint#331]
**[ Project Contact ]** @ivotron , @felix11h
**[ GitHub Repo ]** https://github.com/ivotron/open-comp-rsc-poppper
**[ Track ]** Openness, 
**[ Location ]** eLife Sprint (Cambridge)
**[ Coach ]** @SamanthaHindle & @aariops

### Description
Create a case study that showcases how to generate reproducible papers in computational science using Popper
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, @ivotron! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
- [x] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [ ] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.:

**Comment by aariops** [comment]
Welcome to the sprint, @ivotron :tada:
