### ISSUE TITLE
Project submission timeline?

### ISSUE THREAD

**Issue by JJ** [mozilla/global-sprint#335]
I have looked through the site, and it is not clear to me what's the timeline for project leaders. I was thinking about presenting a project in the next edition, when is the call for projects usually open? Which channels should I follow to get alerted when this happens?

**Comment by abbycabs** [comment]
Hey @JJ! Thanks for stopping by 🐱 

[Mozilla's Global Sprint](http://mzl.la/global-sprint) is an annual event. The next one will be sometime in 2019. You can subscribe to our ["Work Open, Lead Open" newsletter](https://tinyletter.com/MozOpenLeaders) for updates.
