### ISSUE TITLE
JobTalk

### ISSUE THREAD

**Issue by aromartins** [mozilla/global-sprint#34]
**[ Project Contact ]** @aromartins & @clancykelly  
**[ GitHub Repo ]** ( https://github.com/voxverus/GlassCeiling )
**[ Track ]** Privacy + Security, our project will aim to keep user data secure, while allowing online safe collaboration by all users
**[ Community ]** Mozilla Open Leadership Training
**[ Location ]** Basel, Switzerland (CET timezone) 
### Description
A professional development platform for academics, focused on workplace reviews and network building. 

***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @_aromartins & @clancykelly ! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @chadsansing. We're here to help you through this process.

**Comment by chadsansing** [comment]
Let me know how to help, @_aromartins.

Would you also please provide a full link to your repo?

**Comment by aromartins** [comment]
Hi Chad - thanks for your note. Yep have provided the link and will def reach out if needed! Thanks!

**Comment by WW-Web-Infra** [comment]
@aromartins  is this project available?

**Comment by chadsansing** [comment]
@AnamikaD - I think you can comment on the issues here to get involved:

https://github.com/voxverus/GlassCeiling

**Comment by WW-Web-Infra** [comment]
@chadsansing Thank you!!

**Comment by WW-Web-Infra** [comment]
@chadsansing can we feature this on mozilla pulse?

**Comment by chadsansing** [comment]
@AnamikaD, once @aromartins provides and image and indicates the project is ready, I will add it to Pulse.

**Comment by WW-Web-Infra** [comment]
Thanks!

**Comment by clancykelly** [comment]
![jobtalk2](https://cloud.githubusercontent.com/assets/9351375/25471745/bc045d64-2b28-11e7-885b-40338dff4a78.jpg)

**Comment by clancykelly** [comment]
This is ready for Mozilla Pulse. Thank you!!

**Comment by clancykelly** [comment]
![jobtalk](https://cloud.githubusercontent.com/assets/9351375/25472318/22f36e00-2b2b-11e7-9af7-17882a56ca37.jpg)

**Comment by chadsansing** [comment]
Pulsed!

https://www.mozillapulse.org/entry/248

**Comment by AnkitMArtin** [comment]
I want to contribute something .pls let me know .how can i help

**Comment by aromartins** [comment]
Hi Ankit  thanks for stopping by ! Visit here https://github.com/voxverus/JobTalk/blob/master/README.md for background and join our slack for some discussion https://jobtalk-self-sign-in.herokuapp.com/ !

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
