### ISSUE TITLE
Extending Library Carpentry

### ISSUE THREAD

**Issue by weaverbel** [mozilla/global-sprint#35]
**[ Project Contact ]** @weaverbel
**[ GitHub Repo ]** https://github.com/LibraryCarpentry/librarycarpentry.github.io
**[ Track ]** Web Literacy
**[ Community ]** Curriculum on the Web - wrangler @chadsansing 
**[ Location ]** Brisbane Australia, UTC +10
### Description
We are going to work on incubator lessons: https://github.com/jezcope/library-spreadsheets; https://github.com/timtomch/library-webscraping, and the python lesson; bring together various SQL lesson threads; refresh/revise http://librarycarpentry.github.io/; develop a proper workflow for monitoring upcoming workshops and publishing our list of events in a public place - more here: https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/23. Sign up for our sprint here:
http://pad.software-carpentry.org/lc2017
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @weaverbel! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @chadsansing. We're here to help you through this process.

**Comment by chadsansing** [comment]
Looking forward to following this project. Let me know how to help, @weaverbel.

**Comment by weaverbel** [comment]
Here is our project logo
![lc](https://cloud.githubusercontent.com/assets/2783128/25511830/ca7d05fa-2c0c-11e7-91a9-275fdbd350e3.png)

**Comment by weaverbel** [comment]
Hi @chadsansing 
The repo we are using to wrangle work for our sprint is here: https://github.com/data-lessons/librarycarpentry

Much of the work will take place in the repos listed in the README or CONTRIBUTING files within that repo. The repo I have listed is just our jumping off point - we plan to work on six or seven different repos under the Library Carpentry banner. Licensing and code of conduct (we follow Software Carpetry's CoC) will be in those files as well. I have uploaded our logo and think we are ready to go. 

Can you please review and see if there is anything you still need. If so, please let me know.
Thanks Belinda

**Comment by chadsansing** [comment]
The repo is looking great, @weaverbel. My only suggestion at this point would be to close any old issues and create new ones that explain what you need and where you need each thing. I might also create labels for the 2017 issues (and a #mozsprint label) so contributors can tell at a glance which issues belong to this sprint and which are from past/other work.

I will share this on Pulse.

**Comment by chadsansing** [comment]
Pulsed!

https://www.mozillapulse.org/entry/253

**Comment by weaverbel** [comment]
Hi @chadsansing It might be tricky for us to close all our issues as some of them are ongoing. What I can do is label the sprint issues clearly, and mark the others in another way so people are sure to give them a swerve!

**Comment by chadsansing** [comment]
Thanks, @weaverbel - that sounds perfect.

**Comment by jezcope** [comment]
@chadsansing Thanks for this! Just spotted a typo in the Pulse entry: the title says "Caprentry" instead of "Carpentry". Could be worse though... :wink:

**Comment by chadsansing** [comment]
We'll get it fixed!

**Comment by weaverbel** [comment]
Thanks @chadsansing - we can't afford to look illiterate in front of a lot of librarians ;-)

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
