### ISSUE TITLE
Mozilla North American Campus Clubs

### ISSUE THREAD

**Issue by semirahd** [mozilla/global-sprint#38]
**[ Project Contact ]** @semirahd
**[ GitHub Repo ]** https://github.com/semirahd/Mozilla-NorthAmerican-CampusClub
**[ Track ]** Open Innovation
**[ Community ]** Mozilla Clubs - wrangler: @jvallera @Carotejada
**[ Location ]** BOSTON, MA USA EST
### Description
Mozilla Campus Clubs are a unique and personal way to Teach the Web in universities. They are made up of technologists, thinkers and builders working together to keep the Internet alive and accessible, so people worldwide can be informed contributors and creators of digital world.
Mozilla Campus Clubs is an effort to make contributing to open source, easier, for Campus students. It provides various activities, teaching kits and learning materials for the campus students.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @semirahd! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [ ] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @jvallera. We're here to help you through this process.

**Comment by semirahd** [comment]
@jvallera Thank you guys for making this process seamless and user friendly! I will work on my action items to have this ready for the sprint! 

Best, Semirah

**Comment by jvallera** [comment]
Hi Semirah, happy to have you join us! Do you plan to make the project featured (described above). If not, no worries. If so, just let me know when all the materials are ready.

**Comment by jvallera** [comment]
Hi @semirahd 

Your readme file is looking good. I suggest proceeding with these next steps asap, so you can start sharing the project:

1. Add issues - specific things people can start to work on
2. Add a license 
3. Complete the check list above so I can share the project on Pulse
4. Publicize the project

Let me know what you think.

**Comment by auremoser** [comment]
Hey @semirahd ! My name is Aure, and I'm working with the sprint team to check in on projects. This looks great. You might think about adding a few more easy issues to your issues queue, we're trying for at least 5 `#mozsprint` issues per project, just so people know how to help out. It could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in.

Every project also needs a License, to be featured in the sprint, so if you could add one that would be lovely!

Thanks!

**Comment by jvallera** [comment]
Hi @semirahd How are things going? We are excited for the sprint next week! I would love to get this project featured asap. We still need you to:

-  Add issues - specific things people can start to work on
-  Add a license
-  Complete the check list above so I can share the project on Pulse
-   Publicize the project

Let us know if you have q's

**Comment by abbycabs** [comment]
Hey @semirahd! We need you to complete the first 5 items to participate in the sprint.

I'd love to see this project in the sprint! Can you complete those steps before tomorrow?

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
