### ISSUE TITLE
NeuroTechEDU

### ISSUE THREAD

**Issue by syswsi** [mozilla/global-sprint#39]
**[ Project Contact ]** @syswsi
**[ GitHub Repo ]** http://learn.neurotechedu.com/
**[ Track ]** Open Innovation, Decentralization, Open Education and accessibility to emerging tech
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** Montreal, EST
### Description
NeuroTechEDU is an open education platform to help and train people around accessible Neurotechnology. Our goal is to allow beginners to the field and provide them a "learning by teaching peer-to-peer" framework where they get to build open content as well as get advice from experts in the field who will mentor them through the process.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @syswsi! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [X] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [X] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [X] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [X] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [X] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [X] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [X] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [X] Comment with an image to use on Mozilla Pulse for this project listing
![image](https://cloud.githubusercontent.com/assets/1899422/25160648/3d843bac-2485-11e7-9a56-915fc696aa66.png)

Once all of the above is complete,
- [X] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

This is ready for Mozilla Pulse

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by stephwright** [comment]
Apologies @syswsi !  I forgot to notify you that this was Pulsed! https://www.mozillapulse.org/entry/239
Congrats on being a featured project! 🎊

**Comment by auremoser** [comment]
Hey @syswsi ! I'm working with the sprint team to check in on projects. This looks great! You might think about adding a few more easy [issues](https://github.com/NeuroTechX/learn.neurotechedu.com/issues) to your issues queue, we're trying for at least 5 `#mozsprint` issues per project.

Issues could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in. Thanks!

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
