### ISSUE TITLE
Why not Open Science?

### ISSUE THREAD

**Issue by amiefairs** [mozilla/global-sprint#40]
**[ Project Contact ]** @amiefairs
**[ GitHub Repo ]** https://github.com/dasaderi/WhyNotOpenScience
**[ Track ]** Open Innovation
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** Tilburg, Netherlands - GMT +1 on 1st June

### Description
Despite knowing that scientific research is beneficial for science and society, many researchers haven't started being more open in their everyday scientific work. Why is this? In this project, we want to find out why, so we are designing a survey to ask! We will focus on what things researchers are doing so far to make their work more open, what they aren't doing, and why they are (and aren't) doing it.

***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @amiefairs! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by stephwright** [comment]
Hi @amiefairs ! Looks like you're REALLY close to being a featured project!  I just need a link to your repo up at the top so folks can find your project and an image!  Can you believe the sprint is only 3 weeks away?! Let's get this featured!

**Comment by auremoser** [comment]
Hey @amiefairs ! I'm working with the sprint team to check in on projects. This looks great. We'd love to link to a repo and pass this to pulse. Try to make sure that your project has a few issues with the `mozsprint` tag so people know how to contribute.

Issues could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in. Thanks!

**Comment by amiefairs** [comment]
Image for listing: 
![wordcloud_repo](https://cloud.githubusercontent.com/assets/26547786/26193946/1378f5de-3bb7-11e7-8132-e0499448ef01.png)

**Comment by amiefairs** [comment]
This is ready for Mozilla Pulse!

**Comment by dasaderi** [comment]
Hi all. I'm glad our project is almost ready to be featured. Thanks everyone!

**Comment by dasaderi** [comment]
Oh, @stephwright I'll be working on the project from Portland OR. Is it possible to have that info also show up? Thank you.

**Comment by stephwright** [comment]
Hey @dasaderi ... you mean have that info in the Pulse notice?  Sure.  @amiefairs will you be working out of that office too for the Global Sprint?

**Comment by dasaderi** [comment]
@stephwright sorry I did not mention this before ( I was not aware of this thread). I will be working both days in Portland, but @amiefairs will be working from The Netherlands only on June 1st as she has a conflict on June 2nd (Amie, please correct me if I have this wrong). I just want to make sure we can coordinate well with potential collaborators. Thank you.

**Comment by dasaderi** [comment]
Also is it too late to revise the language for the project? I did not have a chance to see it before today. If it's too late, that's okay. Thanks again and sorry for the trouble.

**Comment by stephwright** [comment]
@dasaderi Not too late at all... go for it!  If you have specific text you want to see in Pulse, lemme know and I'll make it happen.  You can even send me an email w/ text if you want.

**Comment by dasaderi** [comment]
[ Project Contact ] @amiefairs @dasaderi
[ GitHub Repo ] https://github.com/dasaderi/WhyNotOpenScience
[ Track ] Open Innovation
[ Community ] Mozilla Science - wrangler: @stephwright
[ Location ] Tilburg, Netherlands - GMT +1 on 1st June
[Location] Portland, Oregon, USA - GMT -8 on June 1,2

Description
We want open science practices to be part of every researcher's workflow. 
The _Why Not Open Science?_ project aims to develop a survey to help assess researchers' attitudes towards open science and learn about the barriers preventing widespread adoption of open science practices. Our goal is to distribute the survey among scholars around the globe and then use the results to inform educational curricula and institutional policy. 
Want to help? We will have a pilot survey ready for you to take and give us feedback on as well as numerous other tasks. Check out our GitHub repository and join us for the #mozfest on June 1-2. Thank you!

@amiefairs what do you think? If you like what you wrote better, I'm okay with that. Thanks!

**Comment by amiefairs** [comment]
Hi all! Sorry for my lack of responding - different time zone :) (plus
weekend!)

Steph, I am going to be in the Netherlands and Daniela will be in the US.
I've updated the info in the text below with UTC times to reflect where we
will be. I've also updated the info that Daniela wrote, just to make the
text a little but simpler (but it has much more info than what I wrote so
it's much better!) Thank you!

[ Project Contact ] @amiefairs <https://github.com/amiefairs> @dasaderi
<https://github.com/dasaderi>
[ GitHub Repo ] https://github.com/dasaderi/WhyNotOpenScience
[ Track ] Open Innovation
[ Community ] Mozilla Science - wrangler: @stephwright
<https://github.com/stephwright>
[ Location ] Tilburg, Netherlands - UTC +2 on June 1st
[Location] Portland, Oregon, USA - UTC -7 on June 1st & 2nd

Description
Open science refers to the entire scientific process, from developing an
idea to publishing findings, being openly available for anyone to see. We
want open science practices to be part of every researcher's workflow.
The *Why Not Open Science?* project aims to develop a survey to help us
find out about researchers' attitudes towards open science and learn about
the barriers preventing them from carrying it out. Our goal is to
distribute the survey to researchers all around the globe and then use the
results to inform current open science training materials and institutional
policies.
Want to help? We will have a pilot survey ready for you to take and give us
feedback on, as well as numerous other tasks. Check out our GitHub
repository and join us for the #mozfest on June 1-2. Thank you!


Thanks Steph!

**Comment by stephwright** [comment]
Thanks @amiefairs & @dasaderi .  There are character limits in Pulse but I'll try to do the best I can to fit this all in.  Would you two mind linking your CONTRIBUTING to your README, just so folks who aren't familiar with GitHub & CONTRIBUTING docs can easily figure out where to go for contributions.  I'll post here when this is on Pulse

**Comment by stephwright** [comment]
You've been pulsed!  https://www.mozillapulse.org/entry/293
There wasn't a good place to put the location info for the Global Sprint for you two in Pulse.  How about adding it to your README?

**Comment by amiefairs** [comment]
Thanks Steph, you are awesome! :) I've linked the contributing file into
our readme, and added a Sprint section to the readme too, so that hopefully
enough info will be there for people :)

**Comment by dasaderi** [comment]
Thank you so much Steph and Amie! That's awesome! Let's start Tweeting it out. :)

**Comment by stephwright** [comment]
You two are ON IT!  👏 🌟

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
