### ISSUE TITLE
Reproducible Research in R for Ocean Biosciences: Open-science Training Seminar (RRROBOTS)

### ISSUE THREAD

**Issue by ha0ye** [mozilla/global-sprint#43]
**[ Project Contact ]** @ha0ye
**[ GitHub Repo ]** https://github.com/Open-Data-Science-at-SIO/RRROBOTS
**[ Track ]** Open Science: project supports training of scientists to produce research that is reproducible, re-usable, re-mixable in as open a manner as possible.
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** San Diego CA (will be available June 1, 9-5pm PST)
### Description
This seminar course is aimed at graduate students who have completed introductory classes in statistics and programming and are thinking about data analyses for their thesis projects. The goal is for students to develop technical skills (e.g. literate programming, version control), while also reproducing statistical analyses from the literature to gain first-hand experience with the data analysis workflow for scientific research.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @ha0ye! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by stephwright** [comment]
Hey there @ha0ye ... get a :framed_picture: for me and I'll get this up on Pulse for you!

**Comment by ha0ye** [comment]
@stephwright  I have delegated that task to my graphics person, future Hao, but he hasn't responded yet. :)

**Comment by stephwright** [comment]
Ha! Those darn future beings... such slackers ;) 😴

**Comment by ha0ye** [comment]
I asked him for homework help once, and he gave me some lame excuse about "ontological paradoxes" and "the patronus was inside you all along".

**Comment by stephwright** [comment]
Harry Potter reference FTW!  :deer:  ⚡️

**Comment by ha0ye** [comment]
This is ready for Mozilla Pulse
![rrrobots-logo](https://cloud.githubusercontent.com/assets/5835366/25574641/1756337a-2e05-11e7-9b10-efaae16dee30.png)

[I should probably have pinged @stephwright about this...]

**Comment by stephwright** [comment]
You've been Pulsed! https://www.mozillapulse.org/entry/262

**Comment by auremoser** [comment]
Hey @ha0ye ! I'm working with the sprint team to check in on projects. This looks great! You might think about adding a label for easy issues to your issues queue, we're trying for at least 5 `#mozsprint` issues per project.

It could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in. Thanks! 💯

**Comment by ha0ye** [comment]
Thanks @auremoser!

I am planning to do some issue-wrangling tonight, and plan on helping class attendees put up some of their own issues during class tomorrow, so hopefully we'll be set for the global sprint, and @acabunoc will have some issues to link to in her interview thing.

EDIT: [link](https://github.com/Open-Data-Science-at-SIO/RRROBOTS/issues?q=is%3Aissue+is%3Aopen+label%3Amozsprint) to mozsprint tagged issues.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
