### ISSUE TITLE
The Data Neuroscientist

### ISSUE THREAD

**Issue by GrantRVD** [mozilla/global-sprint#44]
**[ Project Contact ]** @GrantRVD
**[ GitHub Repo ]** https://github.com/GrantRVD/data-neuroscience
**[ Track ]** OPEN DATA-DRIVEN NEUROSCIENCE EDUCATION
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** California (Pacific Standard Time)
### Description
An open collection of web and software resources attempting to answer one question: what would neuroscience education look like today if it were built from scratch today?
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @GrantRVD! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by stephwright** [comment]
Hi @GrantRVD ... just checking in on prep for the Global Sprint.  It's only 3 weeks away! Woohoo!  Looks like you're close to being a featured project.  There need to be some link fixes in your README (to your CONTRIBUTING, CODE_OF_CONDUCT, and contributors), and a link to our participation guidelines, then it's just a matter of giving us an image to post with your project and you'll be featured on Pulse: https://www.mozillapulse.org/latest
If you don't want an image, that's fine, you can still be featured. 
I'll also recommend that you think about some more concrete actions to put in your issue tracker for folks to work on.  You had some great suggestions in the CONTRIBUTING doc: suggest omitted resources, improve presentation materials.  I would suggest making those into issues, as well as any other areas of work.
Looking forward to seeing this project at the Sprint!

**Comment by auremoser** [comment]
Hey @GrantRVD ! I'm working with the sprint team to check in on projects. This looks great! You might think about adding a few more easy issues to your issues queue, we're trying for at least 5 `#mozsprint` issues per project. It could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in. 

We'd also love to get it up on Pulse, to @stephwright 's point above, so if you could pass along an image that would be stellar. Thanks!

**Comment by GrantRVD** [comment]
Thanks @stephwright & @auremoser! I apologize I didn't reply sooner - I didn't realize my notifications for github were turned off. I've already added one `#mozsprint` issue to my repo and will be adding others based on my previous chats with Alissa, Abby, and Kirstie. I'll be pushing fixes to the README as well, though the broken links have already been fixed thanks to a pull request from Kirstie.

I think I've got a suitable CC-BY-NC image to use for pulse, which I'll leave here, but I'll add a `This is ready for Mozilla Pulse` reply when everything's finalized. Thank you both for checking in! Everything should be up and ready in T-48 hours so it can enjoy a good week on Mozilla Pulse in the lead up to the Global Sprint.

[preliminary image](https://www.flickr.com/photos/nihgov/27507499486/in/photolist-pHL7j-yRRDS-kpQ5pk-a7WnGC-fhRPNk-9ks2E7-8xapWL-fzT4do-pE8pq2-nGNmSe-8Him9f-cKsCHw-2xdo6Y-5GzgKf-7DrArf-7MrGg-ewoS5D-acyV5r-fzCJv8-8osD3b-4xic8X-7vmtKz-5Agsh-4vAdHk-HUK8fw-5qRnC-fTfGnw-pmKFJ5-dGExo7-5qS7z-5Agsi-5qS7B-dGEzgb-9pqRJL-a9cBYi-5qRnz-9pqRHW-5qS7E-5qS7D-5qS7y-5qRnD-5qRny-DtfqZ6-EojiGs-EfbUr7-DtfqZB-rXCyEq-bTBZ2R-5qRnA-5qRnB)

**Comment by GrantRVD** [comment]
This is ready for Mozilla Pulse

**Comment by abbycabs** [comment]
Pulsed! https://www.mozillapulse.org/entry/374

Sorry for the delay

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
