### ISSUE TITLE
GirlScript

### ISSUE THREAD

**Issue by GirlScript** [mozilla/global-sprint#45]
**[ Project Contact ]** @anubhamane
**[ GitHub Repo ]** https://github.com/girlscript/contribute-girlscript
**[ Track ]** Web Literacy, Digital Inclusion
**[ Community ]** Women & Web Literacy - wrangler: @amirad
**[ Location ]** Nagpur, India
### Description
In India, the international non- profit brands such as women who code, django girls etc. are out of reach from the women of tier-two or tier-three cities. Their events not only demand organiser to have a strong background but also the process of establishing a new chapter is too long! Through ‘GirlScript’ , I want to make a whole new community of women in technology where they will be learning about various technologies specially in computer science, IT and security.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @anubhamane! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @amirad. We're here to help you through this process.

**Comment by amirad** [comment]
Hey @anubhamane I'm your wrangler for the global sprint. Thanks for submitting a project. I would love to touch base and learn more about GirlScript. Will email you know!

**Comment by auremoser** [comment]
Hey @anubhame! Is there anything we can do to help support your project for the sprint. I'm working with the sprint team to check in on projects. This looks great, but we're trying to make sure that every project has a repository and an easy way for people to get involved (including a contributor.md and issues queue). Let us know if you need help!

**Comment by GirlScript** [comment]
![gs bhopal](https://cloud.githubusercontent.com/assets/27850350/26229615/c5d56f42-3c60-11e7-9c54-4fea6edac90b.jpg)

**Comment by GirlScript** [comment]
> This is ready for Mozilla Pulse

**Comment by amirad** [comment]
confirming this was pulsed: https://www.mozillapulse.org/entry/331

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
