### ISSUE TITLE
GIBBON: The Geometry and Image-Based Bioengineering add-On

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [mozilla/global-sprint#46]
**[ Project Contact ]** @Kevin-Mattheus-Moerman
**[ GitHub Repo ]** https://github.com/gibbonCode/GIBBON
**[ Track ]** Open Innovation, Open source code for biomedical engineering
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** Boston, USA. Eastern time zone, UTC-05:00
### Description
GIBBON is an open-source MATLAB* toolbox and includes an array of image and geometry visualization and processing tools. GIBBON includes tools for tetrahedral meshing and finite element analysis and thereby provides a highly flexible image-based modeling environment (e.g. for patient-specific medical device design and advanced inverse finite element analysis).
*The project is slowly migrating away from MATLAB to the Julia language.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @Kevin-Mattheus-Moerman! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by stephwright** [comment]
Hey there @Kevin-Mattheus-Moerman !  Checking in w/ folks on progress toward Global Sprint.  Looks like you are SOOOO close to having this ready to be featured on Pulse: https://www.mozillapulse.org/latest
Just need a link to our participation guidelines on your README and I think you already have an image... if you want me to use the image in your README let me know.

**Comment by stephwright** [comment]
OOOPS... sorry... meant to just comment, not close & comment

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @stephwright 

Here is a link to the code of conduct, is that sufficient? 
https://github.com/Kevin-Mattheus-Moerman/GIBBON/blob/master/CODE_OF_CONDUCT.md

Here is an image
https://github.com/Kevin-Mattheus-Moerman/GIBBON/blob/master/doc/html/GIBBON_overview.jpg

**Comment by stephwright** [comment]
That'll work!  You've been Pulsed! https://www.mozillapulse.org/entry/275

**Comment by auremoser** [comment]
Hey @Kevin-Mattheus-Moerman  ! I'm working with the sprint team to check in on projects. This looks great! You might think about adding a few more easy issues to your issues queue, we're trying for at least 5 `#mozsprint` issues per project.

It could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @auremoser. I'm going to do the following: 
1. Update help/documentation (today/tomorrow)
2. Create a paper and submit GIBBON to JOSS
3. Create issues for the #mozsprint e.g. I have to think about the particular issues some more. Reviewing documentation is one, and I can also add website design and some more technical issues. One issue I thought would be cool is to "get GIBBON reviewed in JOSS", so people would start to implement/use GIBBON and officially review for JOSS. 

thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
I forked GIBBON into an organization called gibbonCode [https://github.com/gibbonCode/GIBBON](https://github.com/gibbonCode/GIBBON) where main development will take place from now on. I updated the comment at the top here to reflect the "migration". 

Also I built a new project website using GitHub pages [https://gibboncode.github.io/GIBBON/](https://gibboncode.github.io/GIBBON/) 

Is there any way you could update the repository on pulse? [https://www.mozillapulse.org/entry/275](https://www.mozillapulse.org/entry/275)

**Comment by auremoser** [comment]
Hey @Kevin-Mattheus-Moerman ! Only admins can update pulse and I am not one but @acabunoc and she'll get you sorted as soon as she can.

**Comment by abbycabs** [comment]
Updated! https://www.mozillapulse.org/entry/275 🎉

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
