### ISSUE TITLE
Altruism in Tech

### ISSUE THREAD

**Issue by ipsha21** [mozilla/global-sprint#47]
**[ Project Contact ]** @ipsha21
**[ GitHub Repo ]** https://github.com/ipsha21/altruism-in-tech
**[ Track ]** Web Literacy, Digital Inclusion
**[ Community ]** Women & Web Literacy - wrangler: @amirad
**[ Location ]** India, IST (UTC +5:30)
### Description
The project is designed to help and guide people in tech who have lost their way, or find it difficult to start in the first place. The idea is to make the tech industry more inclusive and welcoming for a diverse set of people, by connecting them to a mentor, over internet for a call. The aim is to create a portal where interested Mozilla employees can volunteer by making themselves available for a one-on-one meeting, with a newcomer seeking help in their area of expertise.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @ipsha21! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @amirad. We're here to help you through this process.

**Comment by ipsha21** [comment]
![altruism](https://cloud.githubusercontent.com/assets/17200516/25436761/f157a4ca-2ab1-11e7-8545-752d49d9ec74.jpg)

**Comment by ipsha21** [comment]
`This is ready for Mozilla Pulse`

**Comment by amirad** [comment]
Hey @ipsha21 I'm excited to be your wrangler for the global sprint. Thanks for submitting a project. I would love to chat through your project with you and see how we can engage others to contribute. Can you email me at amira@mozillafoundation.org and we can set up a time. Thanks!

**Comment by amirad** [comment]
Never mind, just emailed you!

**Comment by auremoser** [comment]
Hey @ipsha21! I'm working with the sprint team to check in on projects. This looks great. You might think about adding a few more easy issues to your issues queue, we're trying for at least 5 `#mozsprint` issues per project, so if you could add that label to a few of your issues that would be lovely.

It could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in. I'll leave the rest to @amirad.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
