### ISSUE TITLE
Improve participation & collaboration on Mozilla Clubs Discourse

### ISSUE THREAD

**Issue by dunebuggie** [mozilla/global-sprint#49]
**[ Project Contact ]** Shreyas Narayanan Kutty
**[ GitHub Repo ]** https://github.com/dunebuggie/participation-collaboration-mozillaclubs
**[ Track ]** Web Literacy, Open Innovation
**[ Community ]** Mozilla Clubs - wrangler: @jvallera
**[ Location ]** Bangalore, India (Indian Standard Time)
### Description
Work with community members of the Mozilla Learning Discourse forum to improve participation so that we can get feedback from others, thereby improving openness.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, Shreyas Narayanan Kutty! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @jvallera. We're here to help you through this process.

**Comment by jvallera** [comment]
Hi Shreyas, would you like this project to be added to Network Pulse? If so, be sure to complete the checklist above and let me know when its done. Pro tip: be sure your read me file and contribution page is very well thought out. It should be absolutely clear how you want people to contribute, what you need from them and why their contributions are important. Also good to include who this project is designed for. Great work so far!

**Comment by dunebuggie** [comment]
Hi @jvallera , I've added more information to the Contribution page. Let me know if something is unclear and I'll work on that. But otherwise, I think we're set to get this live on Network Pulse. Regarding the picture- I'm not really sure what to include. 😅

**Comment by jvallera** [comment]
Thanks @dunebuggie it is looking great. I think it may be good to add a couple more things to your contribution page....
1. A link to a google form that people can fill out - with prompts that will help your research.
2. A way to volunteer for an in person interview with you (we talked about this being an option for the final report you create)
3. Create some issues and point people to those via the contribution page

Also, please add a picture (I love your pictures! can't wait to see which one you pick) here and be sure to check the boxes and leave a comment that it is ready (see directions above). 

Excited to get this up!

**Comment by dunebuggie** [comment]
![kidzilla](https://cloud.githubusercontent.com/assets/5449109/25782679/10bd6840-336d-11e7-864c-a0cc8229d317.jpeg)
@jvallera added an image and updated the contribution page with all the necessary information. Is this ready for Network Pulse now?

**Comment by dunebuggie** [comment]
This is ready for Mozilla Pulse.

**Comment by dunebuggie** [comment]
This is ready for Mozilla Pulse.

**Comment by jvallera** [comment]
Excellent! The project posting on Pulse is here: https://www.mozillapulse.org/entry/264

**Comment by jvallera** [comment]
@dunebuggie try to complete the check list above asap. The project still needs a license and you need to apply "mozsprint" label to each of your issues. Let me know if you need assistance. The project is coming along nicely.

**Comment by dunebuggie** [comment]
@jvallera Done. Can you check and let me know if we're missing anything else?

**Comment by jvallera** [comment]
@dunebuggie looks like you still need to choose and apply a license. Many sprint projects use the Mozilla public license like the one in this project: https://github.com/mozilla-neutrino/neutrino-dev/blob/master/LICENSE 

If you edit your "License file" you should see the option to assign a license in the upper right hand corner of the page. Let me know if you don't see it.

**Comment by auremoser** [comment]
Hey @dunebuggie ! I'm working with the sprint team to check in on projects. This looks great. You might think about adding a few more easy issues to your issues queue, we're trying for at least 5 `#mozsprint` issues per project.

It could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in. Thanks!

**Comment by dunebuggie** [comment]
Hi @auremoser , I've added some more questions. Hope this works for now. Will spend some time over the weekend and get more issues up.

**Comment by auremoser** [comment]
Thank you @dunebuggie !

**Comment by jgmac1106** [comment]
Hey @dun3buggi3 I know the lack of activity on Discourse has been an issue and you people have been trying for years to get folks off Telegram since it organically replaced irc. 

Reasons stated being:
Lack of discoverability
Reasked questions 
No archive 

Yet you have a group of users happy with chat and ignoring forums. That is very clear data. Users do not want what you want to offer. 

Chat is the future. Forums are the past. 

So maybe it is an AND issue and not an OR issue. 

My other thinking is let's transition to Gitter over a Telegram. 
-provide bridge to GitHub. 
- FOSS (though that doesn't matter as much anymore) 
- You create a guide during Global Sprint on using Gitter. 
- We also make a Club Template page in Thimble and run a master class in Gittee on taking the files from Thimble and uploading to GitHub pages. 
- For sticky questions use the wiki associated with Clubs Repo. 

Could look at Mattermost as well. MoFo is using that internally though I like Gitter s GitHub integration m

**Comment by jgmac1106** [comment]
If you do want to make Discourse more active you need to:

- Set a calendar of events (ex every Fridaybis plus Delta) 
- Redesign categories 
- Do a drip email campaign with clubs and hope for a 10-15% conversion rate. 
- Say hello to each person that joins
- Integrate Discourse in how Clubs tell their story.

**Comment by dunebuggie** [comment]
Thanks so much for the detailed inputs, @jgmac1106.
> So maybe it is an AND issue and not an OR issue.
Yup. That's the idea. Atleast for me, Telegram is where all the spontaneous chat stuff happens and discourse is where I'd like to post discussions and participate in them. Maybe because I'm usually on my laptop while the world is moving to mobile :)

> My other thinking is let's transition to Gitter over a Telegram.
TBH, this is the first time I've used Gitter. I'd still need to play around for quite some time before getting to know Gitter in depth. 

I love all your suggestions, as well. I'm particularly interested in this one-

> Integrate Discourse in how Clubs tell their story.

Do you have some ideas on how we can get this going? Monthly contributor interviews? This might improve the chances of those individuals sharing the thread in their networks, which would increase the visibility of our community. 
Sorry, I'm just thinking out loud. 😅

**Comment by jgmac1106** [comment]
Never apologize for thinking out loud.

First step is set your overall goal for the campaign. % of clubs using Discourse, % increase in posts etc.

Then we can design backwards from there.

I am thinking a set of monthly challenges and contests plus a schedule of check in either bi-weekly or weekly. Some groups I am in do a Friday Best/Worst or Monthly Plus/Deltas.

You also can't create a community without content. What kind of resources and training are you offering to captains to get them log in and check?

Right now I think Network Pulse stories are collected in Google Forms. Fork that over to Discourse for clubs. 

Do AMAs with famous people, developers, etc.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
