### ISSUE TITLE
Bionode.io - Modular and universal bioinformatics

### ISSUE THREAD

**Issue by bmpvieira** [mozilla/global-sprint#52]
**[ Project Contact ]** @bmpvieira
**[ GitHub Repo ]** http://github.com/bionode/bionode
**[ Track ]** Open Innovation
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** Lisbon or London / BST
### Description
Bionode is an Open Source community that aims at building highly reusable code and tools for bioinformatics by leveraging the Node.JS ecosystem. We use Node.JS Streams to process big genomic data. We look for all kinds of contributions, from JavaScript developers to biologists.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @bmpvieira! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by bmpvieira** [comment]
## README, CONTRIBUTING, CODE_OF_CONDUCT (Contributor Covenant, version 1.4.0) and LICENSE (MIT)
https://github.com/bionode/bionode/blob/master/README.md
https://github.com/bionode/bionode/blob/master/CONTRIBUTING.md
https://github.com/bionode/bionode/blob/master/CODE_OF_CONDUCT.md
https://github.com/bionode/bionode/blob/master/LICENSE

## GitHub repository for work and discussion
> *For faster iteration, @Bionode uses another org for hackathons, @bionode-hack, with more relaxed GitHub permissions and less quality checks*.

https://github.com/bionode-hack/mozsprint16

## Turn on your Issue Tracker and create issues
Done! Also check our project wide issues board at http://project.bionode.io

**Comment by bmpvieira** [comment]
## Comment with an image to use on Mozilla Pulse for this project listing
![mozpulse](https://raw.githubusercontent.com/bionode/bionode.github.io/dev/images/mozpulse.png)

**Comment by bmpvieira** [comment]
This is ready for Mozilla Pulse

**Comment by stephwright** [comment]
This project has been pulsed!!! 💓 https://www.mozillapulse.org/entry/241

**Comment by trustodia** [comment]
Hi @bmpvieira my name is Trust Odia and I am interested in contributing to this project during #mozsprint 2017! . How can I help?

**Comment by bmpvieira** [comment]
Hey @trustodia ! Thank you for your interest!! 🎉 

You can check the links [in my comment above](https://github.com/mozilla/global-sprint/issues/52#issuecomment-296640879), specifically our [Code of Conduct](https://github.com/bionode/bionode/blob/master/CODE_OF_CONDUCT.md) and [Contributing](https://github.com/bionode/bionode/blob/master/CONTRIBUTING.md) guidelines. Then you can check the issues we have in our [project board](http://project.bionode.io) and pick one you would like to help us solve. As we approach the date of the global sprint, we will try to have more specific and targeted goals to achieve in those two days.
Please come present yourself and talk to us on our [Gitter channel](http://gitter.im/bionode/bionode), and we can discuss in more detail there how you can contribute.

Cheers

**Comment by auremoser** [comment]
Hey @bmpvieira ! I'm working with the sprint team to check in on projects. This looks great, loads of issues. You might think about adding a few more easy issues to your issues queue, in one particular repo, we're trying for at least 5 `#mozsprint` issues per project; so if you could add the tag to a few, that would be jelly.

It could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in; trying to make it super easy for people to parse projects and contribute. Thanks!

**Comment by bmpvieira** [comment]
Hey @auremoser! :) Thank you for the suggestions, we are working on it. We will have an issue of `#mozsprint` issues to point people to, with a mix of easy and challenging stuff.

**Comment by bmpvieira** [comment]
Our `#mozsprint` issue of issues (work in progress): http://github.com/bionode/bionode/issues/44

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
