### ISSUE TITLE
Semantic Modeling of Researcher Networks: Applying Linked Open Data for Discovery

### ISSUE THREAD

**Issue by jasonclark** [mozilla/global-sprint#53]
**[ Project Contact ]** @jasonclark
**[ GitHub Repo ]** https://github.com/jasonclark/linked-people-bioscience
**[ Track ]** Web Literacy
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** Eastern Daylight Time
### Description
A prototype software project that allows one to visualize research and networks of expertise based on researcher interests and research collaborations. In this phase of the project, we are working with the Montana State University (MSU) - Center For Biofilm Engineering (CBE) to describe/visualize Bioscience data. This work applies a methodology for describing researcher interests and research collaborations through the application of linked open data (LOD) which has an impact on the visibility of these researchers in search engines.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @jasonclark! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by stephwright** [comment]
Hey there @jasonclark !  With 3 weeks to go til Global Sprint, I'm just checking in on progress.  Looks like you're REALLY close to being able to make this a featured project.  Just need to flesh out your README, add some issues and give me an image (or you don't need that last one if you don't want to).

**Comment by jasonclark** [comment]
Hey, @stephwright ! I think this is ready for Mozilla Pulse.
<img width="671" alt="network visualization" src="https://cloud.githubusercontent.com/assets/494421/26007472/9cba22a8-370e-11e7-93b2-c6a4242e908b.png">

**Comment by stephwright** [comment]
You've been Pulsed, @jasonclark ! https://www.mozillapulse.org/entry/281

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
