### ISSUE TITLE
Author Carpentry

### ISSUE THREAD

**Issue by tmorrell** [mozilla/global-sprint#54]
**[ Project Contact ]** @tmorrell
**[ GitHub Repo ]** https://github.com/AuthorCarpentry
**[ Track ]** Web Literacy, Open Innovation
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** Pasadena CA, PST
### Description
AuthorCarpentry is a set of open lessons designed to enhance scientific authorship and publishing in the digital age. Its aim is to promote and support best practices in open science and research communication. AuthorCarpentry lessons cover tools, workflows, practices, and skills that help researchers prepare, submit, and publish contributions that add value to an open scholarly record and invite others to adapt and build upon their work.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

Find out more about our lessons at https://authorcarpentry.github.io

Get started with our list of big picture issues and ways to help at: https://github.com/AuthorCarpentry/planning/issues

We have repositories for each individual lessons, and more detailed ways to help can be found at each of the lesson repositories.

Chat with us!  https://gitter.im/AuthorCarpentry/Lobby#

***

## Note to the Project Lead :tada:
Congrats, @tmorrell! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by tmorrell** [comment]
![aclogo](https://cloud.githubusercontent.com/assets/10798874/25909455/108bc3d4-3562-11e7-9af7-ac2fbc211716.jpg)

**Comment by tmorrell** [comment]
This is ready for Mozilla Pulse

**Comment by stephwright** [comment]
This has been Pulsed! https://www.mozillapulse.org/entry/271 🎉

**Comment by auremoser** [comment]
Hey @tmorrell  ! I'm working with the sprint team to check in on projects. This looks great, lots of repos though. You might think about adding a few more easy issues to your issues queue, in one particular repo, we're trying for at least 5 `#mozsprint` issues per project.

It could be as simple as reviewing project documentation, or responding to some discussion idea, low pressure, but just wanted to check in; trying to make it super easy for people to parse projects and contribute. Thanks!

**Comment by tmorrell** [comment]
Thanks @auremoser - we're going to be adding more #mozsprint issues to https://github.com/AuthorCarpentry/planning/issues soon.  We're currently working on getting more of the lesson content up for sprint participants to look at.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
