### ISSUE TITLE
Offline Games Challenge

### ISSUE THREAD

**Issue by chadsansing** [mozilla/global-sprint#61]
**[ Project Contact ]** @chadsansing
**[ GitHub Repo ]** https://github.com/MozillaFoundation/mpa-offline-games-challenge/
**[ Track ]** Privacy + Security, Digital Inclusion
**[ Community ]** Fun & Games - wrangler: @chadsansing
**[ Location ]** Waynesboro, VA, USA, Eastern Time Zone
### Description
Invent offline games that anyone can use anywhere in the world to teach strong online safety and inclusion habits!
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @chadsansing! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @chadsansing. We're here to help you through this process.

**Comment by chadsansing** [comment]
![tag-tag-1](https://cloud.githubusercontent.com/assets/4128600/25434958/5ff031c8-2a5c-11e7-836a-bbddfc7299af.jpeg)

**Comment by chadsansing** [comment]
This is ready for Mozilla Pulse.

**Comment by chadsansing** [comment]
![offline-2](https://cloud.githubusercontent.com/assets/4128600/25481986/be79a230-2b1d-11e7-9b32-2b40e4025f6c.png)

**Comment by chadsansing** [comment]
Pulsed!

**Comment by RohitRamamoorthy** [comment]
This sounds interesting. How can I contribute to your project?

**Comment by r01si14** [comment]
Hey, I'd like to contribute to this project. How do I join? :)

**Comment by stephness36** [comment]
Hey, I'd like to contribute to this project. How do I join? :) (ignore the previous comment, I had to make a different account)

**Comment by chadsansing** [comment]
Hi, @RohitRamamoorthy! Check out the issues here, say hello in the first issue, and then pick one that seems like fun to you.

https://github.com/MozillaFoundation/mpa-offline-games-challenge/issues

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
