### ISSUE TITLE
Chamaconekt open source software project

### ISSUE THREAD

**Issue by wondenge** [mozilla/global-sprint#66]
**[ Project Contact ]** @wondenge
**[ GitHub Repo ]** https://github.com/chamaconekt
**[ Track ]** Financial Inclusion
**[ Community ]** 
**[ Location ]** Kisumu , Kenya
### Description
Chamaconekt open source software project  provides a cost-effective financial management platform to help small financial institutions to operate efficiently and effectively in delivering financial services to the poor in Africa.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @wondenge! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [ ] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [ ] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @acabunoc. We're here to help you through this process.

**Comment by zee-moz** [comment]
@wondenge hello! the Global Sprint is about 2 weeks away, and you've got a few more boxes to check on this project. I see you've linked to a GitHub organization, but not a specific project repo. For this project to be ready for the Sprint, you'll need to have a repo, issues and more project documentation. It's especially helpful to make clear what kinds of contributions you are looking for.  

We've found Sprint projects are most successful when they have chunks of work set out in the issues, tasks that people can jump in on and complete in 2 to 4 hours. Keep that in mind as you set up your issues. Things like reviewing documentation, simple debugging, writing a function or two, an invitation to discuss a topic, request for user feedback on possible features, or QA testing of a new feature all make great Sprint issues. Your project wrangler @acabunoc should be able to answer questions, and I'm also here to help.  Thanks!

Zannah, Global Sprint Coordinator

**Comment by abbycabs** [comment]
Hey @wondenge! We need you to complete the first 5 items to participate in the sprint.

I'd love to see this project in the sprint! Can you complete those steps before tomorrow?

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
