### ISSUE TITLE
Pi Reel

### ISSUE THREAD

**Issue by ghost** [mozilla/global-sprint#68]
**[ Project Contact ]** @kip
**[ GitHub Repo ]** https://github.com/PiReel/PiReel-Core
**[ Track ]** Open Innovation, Digital Inclusion
**[ Community ]** Mozilla Clubs - wrangler: @jvallera
**[ Location ]** Omaha, NE Central Time
### Description
Pi Reel is an easy to use animation tool, made for engineers, makers, and scientists of all skill levels. Pi r can create everything from animations,  entrepreneurial videos, animated structures and gizmos.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @kip! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @jvallera. We're here to help you through this process.

**Comment by ghost** [comment]
![pireel](https://cloud.githubusercontent.com/assets/11668353/25568166/f40f1bda-2dc2-11e7-8a8f-296d8f5168b3.png)

What do you think @jvallera

**Comment by jvallera** [comment]
Hi @KipOmaha! Glad to have you involved in the Global Sprint. This project looks cool. Everything in the repo is coming along nicely. The contribution file needs more work. Try to be very specific about what you need help on and how people can help with it. Perhaps create options for contribution? like different ways for different skill sets (i.e. coders, designers, educators, activists, etc.) I love that you are pulling social impact into the mission of the project. Definitely continue to articulate that as you work on it.

**Comment by PikioopSo** [comment]
Will do, I'm also migrating everything to a Pi Reel Account. Here is the new git repo address: https://github.com/PiReel. I'll update the info here too.

Link to the website repo: https://github.com/PiReel/PiReel-Website
Link to the webapp repo: https://github.com/PiReel/PiReel-Core
Link to the contributing repo: https://github.com/PiReel/PiReel-Contributing

**Comment by jvallera** [comment]
ok, thanks for the updates. Let me know when the contribute file is complete.

**Comment by karthisiva66** [comment]
Hello there! @kip this is karthik from India. And I would like to contribute to this project. Can you mail me further steps. Thankyou!.

**Comment by PikioopSo** [comment]
@karthisiva66  
Thanks for the interest. What type of skills do you have? 

Also, if you want to know more keep checking up on the Pi Reel Repo, because it's going to be updated quite often until Pi Reel gets up and running for the MozSprint.

**Comment by PikioopSo** [comment]
@jvallera,

I updated the Contributing file and the contributing web page.  Still need to work on the home page, which will feature blog articles.

I also updated the issues tracker on the repo.

Edit: 
  Also, I am waiting to see if @helios will help out on the logo. When do I need to have everything completed to be Pulsed?

Here is a link to the contributing page: https://pireel.github.io/PiReel-Contributing/

**Comment by jvallera** [comment]
Great @KipOmaha 
@acabunoc when is the deadline to get the projects on Pulse?

**Comment by jvallera** [comment]
I just noticed that the links in the "what you'll need" section on the contribute.md file are not working.

**Comment by PikioopSo** [comment]
@jvallera, Their should be an issue to get all the links up to date.  If not I'll put one up.

**Comment by PikioopSo** [comment]
@jvallera, I have one more commit to make than I will be ready for pulse

**Comment by PikioopSo** [comment]
![pireel-02](https://cloud.githubusercontent.com/assets/28272745/26320714/82fbabce-3ee9-11e7-8439-2b7a22e71029.png)


This is ready for Mozilla Pulse, @wrangler @jvallera :)

**Comment by stephwright** [comment]
No deadline @jvallera ... if projects are ready and we have time to get them up before the Sprint, they go up :)

**Comment by stephwright** [comment]
Hi @KipOmaha ... before we feature this, can you clarify which of the repositories you want folks to contribute to for the Sprint?  From the link above there are three repositories.  The "Contributions" repo doesn't have any issues and has some account requirements that aren't currently available to contributors (PiReel account).  The "Website" repo has some issues (yay!) but the CONTRIBUTING.md still isn't linked to the README.  If you could make that more easily findable through the README, that'd make life easier for folks who want to contribute to that repo.

**Comment by ghost** [comment]
LOL...Sorry @stephwright, Pi Reel is out of hand.  The link above is supposed to point to PiReel-Core ---> https://github.com/PiReel/PiReel-Core  

The Pi Reel account requirement is for the future. I'll put annotations on it for now indicating that.  After the project is finished being built I plan to use it to store an archive of "animation schematics". People who will want to contribute to those will need an account.  

Also, the web application will be served off of the Google Cloud infrastructure, so the only builds they will be able to see are on the dev server (c9.io) or to clone it locally and run it off a local host.

**Comment by ghost** [comment]
This is ready to be pulsed!

I think.

**Comment by jvallera** [comment]
Is there a website for the project? If not, what link is best for the project site? 

I updated the repo link at the top of this page. @KipOmaha It is a little confusing for people to navigate the various repo's. Many people will go straight to the contribute file and issues for simple ways to get involved so be sure they are clear and straight forward.

**Comment by ghost** [comment]
@jvallera, I think your right...I should change the description to under construction until it gets done.

How does that sound?

**Comment by ghost** [comment]
@jvallera, the website will be the **"main head quarters for Pi Reel"**  
Information regarding the application, "PISEA" or "Pi Reel Science and Engineering Animator"  
will go there.   

I'm currently setting Pi Reels Website up for blogging and viewing peoples projects.  So its a work in progress. But I will have a GitHub page that will give out updates and links to the development servers ***shareable*** links.   

The P.I.S.E.A. application repo is basically going to be set the same way except it will be on its own virtual environment on the host cloud.  

For the sprint I just thought it would be easiest for "me" at least to organize peoples issues, ideas, and other content onto the "Main website"   

Sorry for being long winded but I just wanted to clarify.

### Edit...
Hope that's a good explanation.

**Comment by jvallera** [comment]
all of this sounds fine. It can definitely be a work in progress and you can organize content as needed. For the sake of getting in on Pulse do you prefer I link to [this](https://github.com/PiReel/PiReel-Core) Github page as the main project URL?

**Comment by ghost** [comment]
Yeah that would be fine. thanks @jvallera!

**Comment by jvallera** [comment]
project posted on Pulse: https://www.mozillapulse.org/entry/305
Now you can fine tune your repo and issues so people can easily engage during the sprint. Imagine you don't know anything about the project or programming - use language and explanations in the issues that are straight forward and simple. Here is a good example: https://github.com/dunebuggie/participation-collaboration-mozillaclubs/issues

**Comment by ghost** [comment]
@jvallera,

thanks a bunch

**Comment by himankpathak** [comment]
Hey @KipOmaha, I'm Himank. I have skills in web designing, graphic designing, writing and i would love to help you out with this project.
