### ISSUE TITLE
openSNP

### ISSUE THREAD

**Issue by philippbayer** [mozilla/global-sprint#7]
**[ Project Contact ]** @philippbayer & @gedankenstuecke
**[ GitHub Repo ]** https://github.com/opensnp/snpr
**[ Track ]** Open Innovation
**[ Community ]** Mozilla Science - wrangler @stephwright 
**[ Location ]** Philipp: Perth, Western Australian Time Bastian will be available in Frankfurt, central European time zone
### Description
openSNP is a web project for customers of genotyping data such as 23andMe to share their genetic data with the public
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @philippbayer! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by philippbayer** [comment]
<img src='https://avatars0.githubusercontent.com/u/17121300?v=3&s=200'>

**Comment by philippbayer** [comment]
This is ready for Mozilla Pulse.

**Comment by gedankenstuecke** [comment]
Well done, thanks @philippbayer! 💖

**Comment by stephwright** [comment]
And it's been "pulsed": https://www.mozillapulse.org/entry/210
Thanks, all!  :1st_place_medal:

**Comment by gedankenstuecke** [comment]
Awesome, thanks @stephwright! 🍾

**Comment by Abdelazeem-Elhabyan** [comment]
Is it closed or still there work for June sprint . I am medical student at 5th year with interest in Genomics .genetics and python

**Comment by gedankenstuecke** [comment]
@Abdelazeem-Elhabyan thanks so much for the interest! 🎉 💓  

This one is still open! We actually [have a lot of issues that are marked for being tackled during the sprint](https://github.com/openSNP/snpr/issues?q=is%3Aissue+is%3Aopen+label%3Amozsprint)! openSNP is mostly written in Ruby (on Rails), but there are also issues that don't require any Ruby knowledge, like [testing our documentation to get things up and running](https://github.com/openSNP/snpr/issues/360). 

If you want to chat about where to start you can usually find @philippbayer and me in the [openSNP Gitter channel](https://gitter.im/openSNP/snpr)!

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by gedankenstuecke** [comment]
Thanks, we'll consider it! 👍
