### ISSUE TITLE
Baraza: Online Conflict Resolution

### ISSUE THREAD

**Issue by Obadha** [mozilla/global-sprint#70]
**[ Project Contact ]** @Obadha
**[ GitHub Repo ]** https://github.com/Obadha/baraza
**[ Track ]** Justice Innovation
**[ Community ]** Mozilla Clubs - wrangler: @jvallera
**[ Location ]** Kenya, UTC +3
### Description
Baraza is a social justice innovation that aims to facilitate conflict resolution at the domestic level and among community members. Baraza, presented as an android application, will allow community members seek an audience with their area chief or local administration from within the application for disputes or issues they want resolved. Additionally, they should be able to seek professional legal council from within the application.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @Obadha! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @jvallera. We're here to help you through this process.

**Comment by HarshVardhanKumar** [comment]
I am an undergrad in Computer Science Engineering (5th Semester) and have working knowledge on data structures and programming.

I do not know the development on android platform very well, but I can learn it in short time.  I like your project idea as it is real life oriented. 
Wondering how can I help you.

**Comment by Obadha** [comment]
Hello @HarshVardhanKumar , thank you for showing interest in contributing to this project. 

Over the next couple of days, I will update the [ReadMe](https://github.com/Obadha/baraza) with a comprehensive description and different ways in which  people can contribute. 

 I will share the update when available.

Thanks again! :)

**Comment by jvallera** [comment]
Very excited for this project! sounds interesting and looking forward to reading more.

**Comment by jvallera** [comment]
Hi @Obadha

Your readme file is off to a good start. I recommend adding some more info under "getting started" and "current status". In addition I suggest proceeding with these next steps asap, so you can start sharing the project:

    1. Update your contribute.md file with a broad overview of how people can get involved
    2. Add issues - specific things people can start to work on
    3. Complete the check list above so I can share the project on Pulse
    4. Publicize the project

Let me know what you think.

**Comment by Obadha** [comment]
Thanks for checking up @jvallera :) 

Yes, the repo is far from finished. I have been chipping away at it bit by bit. I'll work on it faster to complete it in good time.

I should be adding tasks as issues and updating the Contribute.md file as appropriate next.

Here's a question I have for you, though. Given the information you have seen so far on the project, is Mozilla Clubs the appropriate category for this? Please advise.

**Comment by jvallera** [comment]
Great! Glad to hear it. Mozilla Clubs is the community associated when you submitted the project, not necessarily the project theme or category. We can add different labels as well that are more appropriate.  I added open innovation for example, but let me know if something else makes more sense or if you prefer to remove the clubs label.

**Comment by Obadha** [comment]
@jvallera almost everything is ready. All that's left is an image. =( Is it absolutely necessary?

**Comment by Obadha** [comment]
![logo](https://cloud.githubusercontent.com/assets/8981774/26097322/dfc35f12-3a2c-11e7-8b94-c48b10ffc94c.PNG)

This is the image to be used for Mozilla Pulse for this project listing. :)

**Comment by Obadha** [comment]
This is ready for Mozilla Pulse.

**Comment by zee-moz** [comment]
hi @Obadha the project looks great. I noticed the link to the code of conduct on the Contributing.md page is broken. maybe fix this link, or just link to Participation Guidelines? :Smile cc: @jvallera  
thanks! Zannah, Sprint Coordinator

**Comment by Obadha** [comment]
Sorry I missed that.
Fixed, @zee-moz

**Comment by Obadha** [comment]
I adapted from the Contributor Covenant, I hope that's okay. :)

**Comment by jvallera** [comment]
Here is your project on Mozilla Pulse: https://www.mozillapulse.org/entry/286 Thanks for getting all the info updated on time!

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
