### ISSUE TITLE
Decentralization Camp

### ISSUE THREAD

**Issue by pransh15** [mozilla/global-sprint#71]
**[ Project Contact ]** @pransh15
**[ GitHub Repo ]** https://github.com/pransh15/decentralization-camp
**[ Track ]** Decentralization
**[ Community ]** Mozilla Clubs - wrangler: @jvallera
**[ Location ]** India +5:30
### Description
With the advancement in technology we have found more and more innovative firms and companies who have done some remarkable work and achieved some incredible heights but what then? We've thought of it as the new age of technology but from the consumers we've turned into the product, but not everyone knows it!

We need to decentralize the web before it gets out of control and this project is a way to collect those resources and spread awareness and save people around the world and save open web!
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @pransh15! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @jvallera. We're here to help you through this process.

**Comment by jvallera** [comment]
Excited to see your project here @pransh15
Once you have the project repository set up be sure to add it at the top of this issue so people can read more.

**Comment by jvallera** [comment]
Hi @pransh15 

Your readme file looks good. Here are some next steps:

1. Update your contribute.md file with a broad overview of how people can get involved
2. Add issues - specific things people can start to work on
3. Complete the check list above so I can share the project on Pulse
4. Publicize the project

Let me know what you think.

**Comment by zee-moz** [comment]
@pransh15 I'm excited that you are joining us for the Sprint. The event is just 2 weeks away-- for this project to be included, you'll need to add some documentation to your repo. I see you have not yet edited the participation guidelines/code of conduct, or the contributing file-- there's just the placeholder wording there. Please update these and add issues as @jvallera suggested above. 😸  Thanks! Zannah, Sprint Coordinator

**Comment by pransh15** [comment]
I'm sorry, I've just been away due to a few too many reasons but now, I'm on it!

Excited! 💃

**Comment by pransh15** [comment]
![mozpulse](https://cloud.githubusercontent.com/assets/18158596/26371348/11aa8028-4018-11e7-9b8a-fc643bcba752.jpg)

**Comment by pransh15** [comment]
`This project is ready for Mozilla Pulse.`

**Comment by pransh15** [comment]
`This project is ready for Mozilla Pulse.`

**Comment by jvallera** [comment]
Excellent! here is the post on Pulse: https://www.mozillapulse.org/entry/306

Next step is to get more issues prepared for the sprint next week. [Here](https://github.com/dunebuggie/participation-collaboration-mozillaclubs/issues) is a good example of a project that has clear, simple ways to contribute on small pieces of the project.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
