### ISSUE TITLE
HyperTools

### ISSUE THREAD

**Issue by andrewheusser** [mozilla/global-sprint#74]
**[ Project Contact ]** @andyh616
**[ GitHub Repo ]** https://github.com/ContextLab/hypertools
**[ Track ]** Scientific tool
**[ Community ]** 
**[ Location ]** Hanover, NH
### Description
A python toolbox for visualizing and manipulating high-dimensional data
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @andyh616! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by zee-moz** [comment]
@andrewheusser this looks amazing! If you thrown in a CONTRIBUTING.MD file, spend a teeny bit of time with Open Leadership 101, and send us an image, we'll feature Hypertools on Mozilla Pulse-- great exposure for the project 😸

**Comment by andrewheusser** [comment]
@zee-moz sounds great!  I'll do it today :)

**Comment by stephwright** [comment]
👍

**Comment by andrewheusser** [comment]
if gifs work...

![hypertools](https://cloud.githubusercontent.com/assets/6596567/25955427/3e384656-3637-11e7-8991-0dac207d1810.gif)

otherwise:

![image](https://cloud.githubusercontent.com/assets/6596567/25955466/607781be-3637-11e7-8caf-7a2b407ed7ed.png)

**Comment by andrewheusser** [comment]
This is ready for Mozilla Pulse.

**Comment by stephwright** [comment]
Hi @andrewheusser !  Would you mind adding a link to your CONTRIBUTING file in your README? I also didn't see the link to our Participation Guidelines on your README but may have just missed it.  And NICE use of labels in your issues!

**Comment by andrewheusser** [comment]
@stephwright oops! I missed the participation guidelines, thanks!  Also, i've linked to the contributing file in the readme.  :)

**Comment by stephwright** [comment]
Great @andrewheusser !  I just submitted a pull request to update the link to the Participation Guidelines in your CONTRIBUTING, too.  I'll put this up on Pulse tonight!

**Comment by stephwright** [comment]
It would let me accept gifs but file size was over 2MB so had to go w/ static 😞 but you've been Pulsed!

**Comment by andrewheusser** [comment]
@stephwright Cool thank you!  Is there any chance you could edit the "by" to say "Contextual Dynamics Lab"?  The project is a group effort :)

**Comment by stephwright** [comment]
I've let our peeps behind Pulse know so they can make the change!

**Comment by andrewheusser** [comment]
👍 thank you!

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
