### ISSUE TITLE
JILINDE

### ISSUE THREAD

**Issue by pomochieng** [mozilla/global-sprint#76]
**[ Project Contact ]** @pomochieng
**[ GitHub Repo ]** https://github.com/pomochieng/Jilinde-App
**[ Track ]** Web Literacy, Open Innovation, Digital Inclusion, Decentralization
**[ Community ]** Women & Web Literacy - @amirad 
**[ Location ]** KISUMU EAT (EAST AFRICAN TIME)
### Description
Develop an application that will report cases of Gender Based Violence to relevant authorities for adults and children, to be able to seek help and immediate medical attention.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @pomochieng! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @vanessarhinesmith. We're here to help you through this process.

**Comment by pomochieng** [comment]
This is ready for Mozilla Pulse.

**Comment by zee-moz** [comment]
hi @pomochieng, I've assinged @amirad, who runs our women in tech work, to help wrangle this project to report and address gender based-violence. the project looks good, but to be really ready for the Sprint, you'll need small chunks of work listed in your issues tab that people can jump in on to help out. Please add these! Thanks 😸

**Comment by zee-moz** [comment]
hi @pomochieng, the Sprint is just 2 weeks away, and in order for your project to be registered, you'll need to have an open license and some issues in your issue tracker! please complete these tasks-- you can ask @amirad or myself if you have any questions. 😄

**Comment by pomochieng** [comment]
Hi,
Am sorry for the delayed response. You sending me a second mail means I
never understood the initial mail sent.

I was expecting issue to be for me, am not a programmer but learning to
programmer the term blew me off guard. If am to create issue kindly help me
on how am to come up with them. For example what is to be done to come up
with the issues for the contributors.

I am going to use Ionic to create this Application and I just got resources
on the same, know little rails as I was being instructed and have taken a
while from the machine.

Am humbly requesting for guidance.

Kind Regards,

*PETER OMONDI OCHIENG*
*KISUMU.*
*Tel: +254729030736, +254772673064*

**Comment by zee-moz** [comment]
@acabunoc want to give @pomochieng some suggestions on creating issues? or regroup together with his mentor for more specific advice? really love this project, looking forward to seeing it in the Sprint 😸

**Comment by pomochieng** [comment]
Noted, seeking clarification from my Mentors ASAP.

Thanks.

*PETER OMONDI OCHIENG*
*KISUMU.*
*Tel: +254729030736, +254772673064*

**Comment by pomochieng** [comment]
1.  Meet Stakeholders (Clinical Officer, Nurse, Police, Counsellor , Lawyer, Human Rights Defender, survivor.)

2. Identify a developer and designer.

3. Collect learning resources.

4. Draw flow Chart of Occurrence.

5. Design a Paper Prototype.

6. Determine Language and Framework to develop the App.

7. Develop a Minimum Viable Product.

**Comment by zee-moz** [comment]
@pomochieng these look like good steps, might be appropriate for a Roadmap! @acabunoc what do you think? this project still needs an active issue tracker and a few small issues (maybe something like a survey stakeholders can fill out? or a discussion about some key project concepts?) in order to be ready for the sprint.

**Comment by pomochieng** [comment]
@zee-moz your suggestion on taking a survey is really brilliant, i would need assistance on the type of questions that would really be asked and I have some in mind.

**Comment by zee-moz** [comment]
@pomochieng glad you're excited about this survey idea! did you get a chance to check in with your mentors about some of these ideas? cc'ing @acabunoc maybe she can send some help in your direction!

**Comment by pomochieng** [comment]
Still working on the Survey idea. My mentors have slotted a meeting with abby today.

**Comment by pomochieng** [comment]
![gender based violence](https://cloud.githubusercontent.com/assets/17782504/26639526/b7f4a402-462d-11e7-9c9f-378aed2a3bd9.jpg)

**Comment by pomochieng** [comment]
This is ready for Mozilla Pulse

**Comment by pomochieng** [comment]
@zee-moz

**Comment by amirad** [comment]
Karibu Sana @pomochieng - I've added this to Mozilla Pulse: https://www.mozillapulse.org/entry/332

Let's collaborate over the next couple days and start developing your app!

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by pomochieng** [comment]
Hi,
Thank you Abby for the mail, Am sorry this year I won't be having a project
for Mozsprint due to work commitment, but will be available to assist
anyone in our area on their projects during that period.

Kind Regards,

*PETER OMONDI OCHIENG*
*KISUMU.*
*Tel: +254729030736, +254772673064*

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
