### ISSUE TITLE
Mozilla Italia l10n Guide

### ISSUE THREAD

**Issue by kitsunenosaraT** [mozilla/global-sprint#8]
**[ Project Contact ]** @kitsunenosarat
**[ GitHub Repo ]** https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide
**[ Track ]** Digital Inclusion, Web Literacy
**[ Community ]** Curriculum on the Web - wrangler @chadsansing 
**[ Location ]** Sanremo, Italy
### Description
A l10n guide made by volunteer localizers for volunteer localizers
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @kitsunenosarat! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @chadsansing. We're here to help you through this process.

**Comment by chadsansing** [comment]
Hi, @kitsunenosaraT! Do you know the Italian Mozilla Rep and Club Captain communities?

**Comment by kitsunenosaraT** [comment]
Hi! [Edoardo Viola](https://github.com/edovio), Mozilla Rep *and* Club Captain, happens to be my mentor for this project.
I don't have much interaction with the communities, though I hope to get the Italian localization team more involved in the activities of other Mozilla volunteers in the future.

**Comment by chadsansing** [comment]
Wonderful, @kitsunenosaraT. We will look for other ways to help, as well.

**Comment by kitsunenosaraT** [comment]
We'd like to use the following image, logo of our organization [Mozilla Italia](https://www.mozillaitalia.org/), for  the Plulse project listing.

![mozilla-italia](https://cloud.githubusercontent.com/assets/14000019/25130181/9cc14dd8-2441-11e7-95d5-aff727dabad4.png)

**Comment by chadsansing** [comment]
Okay. Let me know when you're ready for Pulse. Are you planning to add your own items to the code of conduct beneath the Mozilla Participation Guidelines?

**Comment by kitsunenosaraT** [comment]
Exactly, we subscribed to the Mozilla Participations guidelines, but would like to add our own localization-specific code of conduct if there's time enough.
I'll write back here once everything is ready. The deadline is next week, I believe?

**Comment by chadsansing** [comment]
I think so - just making sure you have everything you want :)

**Comment by kitsunenosaraT** [comment]
Thank you, I really appreciate you looking out for us and making sure everything is in order for the Sprint😃

**Comment by kitsunenosaraT** [comment]
This is ready for Mozilla Pulse

(Thank you for your patience @chadsansing , we're ready to go live 🎊 )

**Comment by chadsansing** [comment]
Pulsed!

https://www.mozillapulse.org/entry/246

**Comment by kitsunenosaraT** [comment]
@chadsansing Sorry for reopening the issue after a month 🙇 
I know it was made clear that after closing the bug there was no changing one's mind, and if my request is a problem, please just say ‘nope’, it's really not that important.
But I was just doing some experimenting, using [GitPages](https://pages.github.com/) to have a nicer landing page for not GitHub-savvy contributors.

[My Gitpage](https://kitsunenosarat.github.io/) would just host the README.md, every link (issues, chapters, resources etc.) would still point to the old repository.
My question is… could my entry at the Global Sprint redirect to the above landing page, instead of the repo, or is it too late at this stage?

Again, if that's too troublesome to do, it's no big deal!

**Comment by chadsansing** [comment]
For the sake of tracking work on the Sprint from our end, it would be good to maintain the original repo and to file issues there, but I think you could also make whatever front page you'd like. Is that right, @zee-moz & @acabunoc?

**Comment by kitsunenosaraT** [comment]
@chadsansing Thank you for always watching out for me! 😀 
I asked directly to @acabunoc, she said no problem in having a dedicated project page.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
