### ISSUE TITLE
Research Bazaar Arizona

### ISSUE THREAD

**Issue by hclent** [mozilla/global-sprint#81]
**[ Project Contact ]** @resbazaz
**[ GitHub Repo ]** https://github.com/resbazaz/studyGroup
**[ Track ]** Open Innovation
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** Tucson, Arizona, USA -- MST 
### Description
ResBazAZ is a community of researchers from all fields and all levels of skill who want to use technology (e.g. programming) to further our data analysis and inquiry. Our goal is to make a collaborative space for researchers from different fields to collaborate and allow incredible research breakthroughs happen! Everyone has something valuable to contribute, and we all have things to learn. ResBazAZ is more than a help desk, its a community of enthusiastic researchers.

For the Mozilla Global Sprint, ResBazAZ is teaming up with CyVerse and University of Arizona Libraries!
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @resbazaz! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by zee-moz** [comment]
@hclent welcome to the Sprint! We're happy to have you. Can you explain (in your description, and in your documentation in the project repo) more clearly exactly what kinds of contributions people might make to the project, during the Sprint-- are you working on curriculum, setting up an online platform for sharing  resources, or organizing an event? Outlining discrete chunks of work (something that could be done in an hour or two or three) will allow people participate successfully. Thanks! cc: @stephwright

**Comment by hclent** [comment]
@zee-moz @stephwright We have updated our README with information about the Global Sprint and the projects that we'll work on June 1st and June 2nd. Unless you think it needs more work, we will add a License and CONTRIBUTING.md next! Thank you for your help!

**Comment by hclent** [comment]
![resbazazrectanglelogo](https://cloud.githubusercontent.com/assets/11139142/26503349/3a823f0c-41f5-11e7-8540-418038d3bfa1.png)

**Comment by hclent** [comment]
This is ready for Mozilla Pulse

**Comment by stephwright** [comment]
Hi @hclent ... This looks great!  Could you add your CONTRIBUTING doc to your README just so it's easy for newbies to find?  Let me know when you get that and I'll get this up on Pulse today!

**Comment by hclent** [comment]
@stephwright That's a great idea! Just updated the README to have the CONTRIBUTING doc. Thank you so much!

**Comment by stephwright** [comment]
Great!!!  Thanks! You've been Pulsed! https://www.mozillapulse.org/entry/316

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
