### ISSUE TITLE
lab.js: social, cognitive and behavioral research in the browser

### ISSUE THREAD

**Issue by FelixHenninger** [mozilla/global-sprint#83]
**[ Project Contact ]** @FelixHenninger
**[ GitHub Repo ]** https://github.com/felixhenninger/lab.js
**[ Track ]** Open Innovation
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** Bonn, Germany (UTC+02:00)

### Description

**Our project helps scientists studying behavior and cognition to build experiments and questionnaires in the browser.** Besides collecting data, researchers can document and share their work, so that others can reproduce, extend, and recombine previous research.

Using our graphical interface, beginners can assemble entire studies from basic components using drag and drop and a bit of HTML, while more experienced users are free to fully customize all aspects of their study if they so desire.
***

## Want to contribute to this project during #mozsprint?

<img align="right" src="https://felixhenninger.github.io/lab.js/media/logo/yellow/dot_200.png" height="100"> 

Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

We appreciate and welcome all contributions &mdash; whatever your expertise or experience, we'd be thrilled to hear from you, and would be more than happy to help you find a contribution that interests and suits you.

***

## Note to the Project Lead :tada:
Congrats, @FelixHenninger! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by stephwright** [comment]
Hi @FelixHenninger ... looks like you just need a CONTRIBUTING.md and an image (or tell me you don't want an image) and I can get this up on [Pulse](https://www.mozillapulse.org/latest) for you. Nice job on tagging a couple issues "Good First Bugs".

**Comment by FelixHenninger** [comment]
Hi @stephwright , thanks so much for your support and encouragement &mdash; this has been a fantastic experience already, and we haven't even really gotten started! I've appended a header below, and with it, hopefully, this is ready for Mozilla Pulse. :balloon: Please let me know if there is anything I can do to help, or any useful information I might provide.

![flask mozilla_pulse_l](https://cloud.githubusercontent.com/assets/8349942/26196193/7f2b0a0e-3bbe-11e7-8b38-0fe1b63c5000.png)

**Comment by stephwright** [comment]
You've been Pulsed! https://www.mozillapulse.org/entry/296

**Comment by FelixHenninger** [comment]
@stephwright Awesome, thanks a lot! What a privilege to see our little logo among all the other fantastic projects!

**Comment by himankpathak** [comment]
Hey, I'm Himank. I have skills in web design, graphic design, writing and i would like to help you out in this project.

**Comment by FelixHenninger** [comment]
Hi there, @himankpathak, thanks so much for stopping by! This is totally awesome &mdash; we could really use help in those areas. I've answered your comment on the [design issue](https://github.com/FelixHenninger/lab.js/issues/5#issuecomment-304482711), but I'd be glad to help you find a way to contribute that best suits your interests beyond that. You'll find me anytime via these threads, or on our [slack channel](https://slackin-nmbrcrnchrs.herokuapp.com/). See you around, I'm looking forward to hearing from you!

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/

**Comment by FelixHenninger** [comment]
Hi Abby,

thanks so much for taking care of us! Last year's sprint was a blast. I've already registered for the next one, and boy am I looking forward to it :-)

All the very best, and see you soon!

-Felix
