### ISSUE TITLE
MakersJam Mozilla Club OnTheRoad

### ISSUE THREAD

**Issue by shillontheroad** [mozilla/global-sprint#84]
**[ Project Contact ]** @shillontheroad
**[ GitHub Repo ]** https://github.com/shillontheroad/makers-jam
**[ Track ]** Web Literacy
**[ Community ]** Mozilla Clubs - wrangler: @jvallera
**[ Location ]** Lausanne, Switzerland, CEST 
### Description
MakersJam is a Mozilla Club committed to shaping the web through peer to peer learning, collaboration, experimentation and creation…finding new and imaginative ways to express ourselves, and having lots of fun. This project takes MakersJam on the road.
MakersJam OnTheRoad seeks to reach a wider audience by offering Maker Educator Residencies in schools and informal learning spaces, supporting them to kickstart their MakerSpaces, grow professional learning opportunities and develop an experimental/tactile approach to hands on learning of Web Literacy skills.
MakersJam aims to make web literacy an embedded part of primary/elementary school curriculum and teacher/educator training.. 

***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @shillontheroad! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @jvallera. We're here to help you through this process.

**Comment by zee-moz** [comment]
@shillontheroad looks like the link to your GitHub repo is broken, can you fix it? Excited to have your project in the Sprint, looking forward to seeing more from you 😄 thanks!

**Comment by shillontheroad** [comment]
Hi 
Thanks- fixed it!
Here’s the link:
https://github.com/shillontheroad/makers-jam <https://github.com/shillontheroad/makers-jam>
Could you please check it.
Look forward to you joining the sprint.

Mark

**Comment by shillontheroad** [comment]
![makers-jam](https://cloud.githubusercontent.com/assets/17291378/26174285/1edf7942-3b4f-11e7-8086-11fb940e2563.jpeg)

**Comment by zee-moz** [comment]
Hey there, the link does work!  In a few places, it looks like you still have some of the language from the Template in your contributing.md file--  stuff like "if your guide is long, add links." or "do you have a chat room or email list you use for this project"  or "This is a good place to link your Roadmap, GitHub Milestones, or Projects so newcomers can see what you're working on." If you are not taking code contributions, you may want to edit "how to submit changes" and "how to report bugs" sections. Please review this file and be sure that all the language there is your own, and relevant to contributors! Also, it's great to add more detail about the kinds of skills and people you're looking for on the project -- artists, librarians, engineers, students, makers, teachers, etc. Add a few more issues, too-- these will help people find work that they can do on the project... hope this helps 😸

**Comment by shillontheroad** [comment]
Thanks for the tips- it's taking shape- more updates coming soon

**Comment by shillontheroad** [comment]
This is ready for Mozilla Pulse

**Comment by jvallera** [comment]
Super! Thanks for making the updates. Here is the project on Pulse: https://www.mozillapulse.org/entry/307

**Comment by jvallera** [comment]
@shillontheroad this is a good example of simple, clear issues: https://github.com/dunebuggie/participation-collaboration-mozillaclubs/issues

I see you have one already but good to have at least 4/5 that allow different skill sets to engage. Let me know if you have any q's.

**Comment by shillontheroad** [comment]
@jvallera thanks for the clear issue tips! I've updated.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
