### ISSUE TITLE
Omaha Parks

### ISSUE THREAD

**Issue by hepplerj** [mozilla/global-sprint#86]
**[ Project Contact ]** @hepplerj
**[ GitHub Repo ]** https://github.com/open-omaha/omaha-parks
**[ Track ]** Digital Inclusion, Open Innovation
**[ Community ]** -- wrangler: @zee-moz
**[ Location ]** Omaha, Nebraska (Central)
### Description
We are looking to kick off a new civic engagement + open data project called Open Omaha, and the Sprint would take place around creating a web application / portal for finding the city's parks. Currently, Omaha has no good portal for discovering parks and open spaces, which means it's difficult to find parks that are appropriate for certain age ranges, are designed for accessibility, have playground or other amenities, or are in states of disrepair.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @hepplerj! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by PikioopSo** [comment]
Hey, I wasn't aware their were any projects from omaha, other than mine @hepplerj .

if I could help let me know. I also could use some help on Pi Reel, too.

**Comment by hepplerj** [comment]
@PiReel Nice to "meet" you! Yeah, hoping to start something new here around open data and civic engagement. Omaha Parks will hopefully be our pilot project for that!

**Comment by hepplerj** [comment]
Here is our logo: https://github.com/open-omaha/project-ideas/raw/master/open-omaha-logo.png 

![Open Omaha](https://github.com/open-omaha/project-ideas/raw/master/open-omaha-logo.png)

**Comment by hepplerj** [comment]
This is ready for Mozilla Pulse

**Comment by zee-moz** [comment]
hi @hepplerj, it's Zannah, Global Sprint Coordinator here. I'm really excited about this project! in addition to the issues you have now, you might add issues where people can discuss features of the app they'd like, and weigh in on the kinds of amenities they might be searching for. great project-- looking forward to seeing what you do at the sprint!

**Comment by hepplerj** [comment]
@zee-moz Thanks for the suggestion! I'll add those as issues.

**Comment by hepplerj** [comment]
@zee-moz Any chance I could learn whether we made it in in time for the coffee + swag give-away? Just want to be sure I have time to cover coffee if we didn't. Thanks!

**Comment by zee-moz** [comment]
@hepplerj yes, you did! we'll be sending out coffee funds next week. stay tuned for more info.

**Comment by hepplerj** [comment]
@zee-moz Woo! Awesome, thanks 😄

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
