### ISSUE TITLE
Study Group Event Visualization

### ISSUE THREAD

**Issue by WW-Web-Infra** [mozilla/global-sprint#89]
**[ Project Contact ]** @AnamikaD
**[ GitHub Repo ]** https://github.com/mozillascience/studyGroupEvents
**[ Track ]** Web Literacy
**[ Community ]** Mozilla Science - wrangler: @stephwright
**[ Location ]** Bangalore, India (time zone: IST)
### Description
The current page of Study Group Event needs enhancement as to provide information about Study Group Programs and Events. Through this page, people learns about events at individual Study Group globally. I would like to import the details of the event, add features to the website and provide statistics i.e, activities on the Study Group page and from all of the forks of the Study Group. The main purpose of the project is to provide visualization and automation.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @AnamikaD! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @stephwright. We're here to help you through this process.

**Comment by zee-moz** [comment]
@AnamikaD welcome to the Sprint! I've looped @auremoser in on the conversation here 😄

**Comment by WW-Web-Infra** [comment]
@zee-moz Thank you!!! :)

**Comment by auremoser** [comment]
Hi @AnamikaD ! I've learned more about the sprint process now, we'll need to:

* add a CONTRIBUTOR.md file with details about how people can contribute to the study group events repo, feel free to copy over relevant material from the GSOC [CONTRIBUTOR.md](https://github.com/mozillascience/studyGroup-GSOC/blob/master/CONTRIBUTOR.md) file
* add at least 5 issues that will be easy for people to participate in to the issues queue and label them `mozsprint`, these can be simple activities like "test out the form and give feedback on what's useful or missing", or "discuss what features you would like to see on a calendar of study group events like this one", or "audit the current site's css and decide on different colors or layout additions".

Do you think that's something you might be able to work on this week, or should we talk about it in our checkin on Monday?

**Comment by WW-Web-Infra** [comment]
Hi @auremoser !
- Task 1 completed. Please review it!
- Task 2 I am not able to add a new label, it seems that you can add that. After adding the label, I will add the issues. (https://github.com/mozillascience/studyGroupEvents)

I would like to play around Visualization. We can discuss the progress on Monday :D 
Thank you Aurelia!!

**Comment by auremoser** [comment]
Looks great (reviewed ✅ ) @AnamikaD 

I added the label in task 2, feel free to add or tag any issues you can think of that might be relevant for us and any contributors to the project.

We'll discuss on monday, thank you!

**Comment by WW-Web-Infra** [comment]
@auremoser Added the issues :D May be I do not have the privilege to add labels :(

**Comment by WW-Web-Infra** [comment]
@auremoser Issues are added with label "mozsprint"!! Please review them and Thank you!!

**Comment by WW-Web-Infra** [comment]
![image](https://cloud.githubusercontent.com/assets/15039155/26187372/0790324c-3bb6-11e7-9fb2-ced679bffc49.png)
Mozilla Pulse image

**Comment by WW-Web-Infra** [comment]
This is ready for Mozilla Pulse

**Comment by auremoser** [comment]
Posted on [Pulse](https://www.mozillapulse.org/entry/289) ! 🍰 
Thanks @AnamikaD

**Comment by WW-Web-Infra** [comment]
Cheers @auremoser !!

**Comment by akshatnitd** [comment]
@AnamikaD I would like to work on it for the MozSprint :smile:

**Comment by WW-Web-Infra** [comment]
@akshatnitd that's wonderful!!! What do you want to work on? feel free to ping [me](https://gitter.im/AnamikaD) or [Aurelia](https://gitter.im/auremoser) on gitter!! @auremoser is my mentor :) You can start to review issues [here](https://github.com/mozillascience/studyGroupEvents/issues) or create issues!

**Comment by HassenPy** [comment]
count me in as well.

**Comment by WW-Web-Infra** [comment]
@HassenPy Great!! What are you planning to work on ? :D

**Comment by HassenPy** [comment]
i'm looking into "Add Events on Mozilla Study Group Events" and "Audit CSS of the website".

**Comment by akshatnitd** [comment]
@AnamikaD Yes, sure. Will first look out to solve the issues and then rest will go on :smile:

**Comment by WW-Web-Infra** [comment]
@HassenPy @akshatnitd  Cheers! Feel free to ping us! Happy coding :D

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
