### ISSUE TITLE
WikiToLearn

### ISSUE THREAD

**Issue by ruphy** [mozilla/global-sprint#9]
**[ Project Contact ]** @ruphy
**[ GitHub Repo ]** https://github.com/WikiToLearn/Hives-Network
**[ Track ]** Open Innovation, Digital Inclusion, Web Literacy
**[ Community ]** Curriculum on the Web - wrangler @chadsansing 
**[ Location ]** Milano
### Description
Imagine a world where educational material is freely available to everyone, always up-to-date and written from thousands of experts and educators. This is what we are doing at WikiToLearn.

WikiToLearn is an open platform where students, researchers and key people in the academia can create and refine notes and textbooks, tailored precisely to their needs, giving them the power to customize the teaching beyond what traditional textbooks allow. Accessibility & learning efficiency are our pillars.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @ruphy! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by chadsansing** [comment]
Hi, @ruphy. Do you think this project might track with Decentralization since it puts the "authority" of the textbook into the hands of thousands of authors?

**Comment by stephwright** [comment]
Hi @ruphy ... I was browsing projects and was wondering if you had some specific ideas of how folks could help you on the day of the Sprint.  I didn't see anything in the Issue Tracker, though realize this may still be a work in progress.

**Comment by ruphy** [comment]
hi @stephwright , you are right, it is definitely a work in progress! :-) expect updates soon, I am in the process of adding more... I have added one simple design task for now, but I expect more, especially for organizing and other nontechincal skills

**Comment by ruphy** [comment]
![mozsprint](https://cloud.githubusercontent.com/assets/2030/26316152/9c21b6fa-3f13-11e7-9f38-4f8bf6882f53.png)

**Comment by ruphy** [comment]
This is ready for Mozilla Pulse

**Comment by chadsansing** [comment]
Pulsed!

https://www.mozillapulse.org/entry/298

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
