### ISSUE TITLE
Peer 2 Peer University - Awesome OER List

### ISSUE THREAD

**Issue by nicop2pu** [mozilla/global-sprint#90]
**[ Project Contact ]** @nicop2pu
**[ GitHub Repo ]** https://github.com/p2pu/Awesome-Online-Courses
**[ Track ]** Web Literacy, Open Innovation, Digital Inclusion
**[ Community ]** 
**[ Location ]** Ottawa, Boston (Eastern Time Zone UTC-05:00) and Cape Town, South Africa (South Africa Time Zone UTC+02:00) 
### Description
Peer 2 Peer University (P2PU) supports access to high-quality education in public local spaces. We're supporting libraries and community groups to facilitate peer-led learning circles to help learners who want to take online courses together and in-person.

WE NEED YOUR HELP to find more AWESOME online courses and share this list with educators and facilitators who are running learning circles across the globe.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @nicop2pu! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @acabunoc. We're here to help you through this process.

**Comment by zee-moz** [comment]
@nicop2pu great to see this here! assigning @chadsansing to help wrangle. 😸

**Comment by chadsansing** [comment]
Great to see P2PU & @nicop2pu here - let me know how to help!

**Comment by nicop2pu** [comment]
![p2pu_logo_medium_rgb-02](https://cloud.githubusercontent.com/assets/26551221/26422567/6a730ff6-4098-11e7-92d1-808277a7e348.png)

**Comment by nicop2pu** [comment]
This is ready for Mozilla Pulse

**Comment by chadsansing** [comment]
Pulsed!

https://www.mozillapulse.org/entry/304

**Comment by nicop2pu** [comment]
Hey @chadsansing  the image looks too big for your site. Here are two more - the smaller one will likely fit best. Can you make the switch? Thanks a ton.

**Comment by nicop2pu** [comment]
![p2pu-logo](https://cloud.githubusercontent.com/assets/26551221/26461349/ea086b0a-414a-11e7-8ae6-bb76d503ae1b.jpg)
![p2pu-logo_big](https://cloud.githubusercontent.com/assets/26551221/26461362/f2bb4e7a-414a-11e7-8e8f-7c8a1e4f2a4c.jpg)

**Comment by abbycabs** [comment]
@chadsansing & @nicop2pu I updated it for you!

https://www.mozillapulse.org/entry/304

**Comment by chadsansing** [comment]
Many thanks, @acabunoc.

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
