### ISSUE TITLE
diaspora* social network

### ISSUE THREAD

**Issue by Flaburgan** [mozilla/global-sprint#92]
**[ Project Contact ]** @flaburgan
**[ GitHub Repo ]** https://github.com/diaspora/diaspora
**[ Track ]** Privacy + Security, Digital Inclusion, Decentralization
**[ Community ]** 
**[ Location ]** Grenoble UTC+2 Paris/France
### Description
diaspora* is a decentralized and privacy-oriented social network available under the AGPL licence
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @flaburgan! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [ ] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @acabunoc. We're here to help you through this process.

**Comment by zee-moz** [comment]
hi @Flaburgan you'll need to [fill out this form](https://docs.google.com/a/mozillafoundation.org/forms/d/e/1FAIpQLSe1-lN-weRFeWo3ZvOuS0Ah_vyysii2OQPK1dTk1nfcTA1ZWQ/viewform?c=0&w=1) -- you'll be logged into our system and an issue will be auto-generated for you here in this repo.

**Comment by Flaburgan** [comment]
**[ Project Contact ]** @flaburgan
**[ GitHub Repo ]** https://github.com/diaspora/diaspora
**[ Track ]** Privacy + Security, Digital Inclusion, Decentralization
**[ Community ]** 
**[ Location ]** Grenoble UTC+2 Paris/France
### Description
diaspora* is a decentralized and privacy-oriented social network available under the AGPL licence
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @flaburgan! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [ ] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [ ] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [ ] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [ ] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [ ] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [ ] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [ ] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [ ] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @acabunoc. We're here to help you through this process.

**Comment by stephwright** [comment]
Hi @Flaburgan ... I checked off the CONTRIBUTING.md requirement for you.  Even though you don't have a specific CONTRIBUTING doc in the repo, you have links in your README w/ instructions for contributors on how to contribute during the Sprint.

**Comment by Flaburgan** [comment]
@stephwright thank you!
I didn't created a `mozsprint` label but we use the `newcomer` one to highlight the issues suitable for new comers, is that enough?

**Comment by stephwright** [comment]
@Flaburgan That will work.  Since you have so many different docs for contributions, instead of just one CONTRIBUTING doc, can  you highlight in your README that the issues w/ the #newcomer tag are good places to start?

**Comment by abbycabs** [comment]
Hey @Flaburgan I'd recommend also adding the a `mozsprint` label since we'll be displaying all issues with that label during the sprint. Thanks!

**Comment by stephwright** [comment]
Ahh... thx for that @acabunoc

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by skyschub** [comment]
@acabunoc the Call for Papers link 404's. :)

**Comment by abbycabs** [comment]
https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
