### ISSUE TITLE
Caja de herramientas para emprendedores/Toolkit for entrepreneurs

### ISSUE THREAD

**Issue by Carotejada** [mozilla/global-sprint#97]
**[ Contacto ]** @Carotejada
**[ GitHub Repo ]**[Caja de herramientas para emprendedores](https://github.com/Carotejada/Caja-de-herramientas-para-emprendedores) 
**[ Track ]** Open Innovation, Digital Inclusion
**[ Communidad ]** Mozilla Clubs - wrangler: @jvallera
**[ Locación ]** Medellín, Colombia - UTC−05:00 zone
### Descripción
Este proyecto pretende poner al alcance de las pequeñas y medianas industrias de manufactura, tecnología y herramientas de alto impacto y bajo costo, tales como karakuris y pokayokes. Estas herramientas pueden ser desarrolladas por las mismas personas en espacios colaborativos de creación, al interior de las empresas. 
***

## ¿Quieres contribuir a este proyecto durante el #mozsprint?
[Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Deja un comentario si quieres colaborar con este proyecto en el #mozsprint 2017!

***

## Nota para el líder del proyecto :tada:
Felicitaciones, @Carotejada! Este es tu repositorio para el [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). Para confirmar tu participación, completa las siguientes tareas:

- [x] Completa el [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Crea un repositorio en Github para trabajar sobre tu proyecto
  * Nuevo en GitHub?  Acá encontrarás una [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [ ] Crea un archivo README en tu repositorio. Este archivo ayuda a las personas a enteder tu proyecto, por qué es importante, y el tipo de ayuda que necesitas.
* [x] [Crear el archivo: LICENSE](http://choosealicense.com/) para asignar una licencia abierta que permita a las personas contribuir.
- [ ] Activa tu [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) y crea temas para describir cada tarea con la cual necesitas ayuda, y cómo alguien puede contribuir. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist para proyectos DESTACADOS :clipboard:
Para que tu proyecto sea publicado en  [Mozilla Pulse](http://mozillapulse.org/), completa la siguiente documentación. En los pasados Sprints, los proyectos bien documentados que fueron publicados, obtuvieron 5 veces más contribuciones. Los detalles sobre cada tema y más información sobre cómo crearlos están en [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [ ] En tu README, crea un vínculo a las [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) o crea tu propio código de conducta.
* [ ] Crear el archivo CONTRIBUTING.md para que otros puedan saber cómo contribuir. Si quieres puedes adaptar  [esta plantilla](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [ ] Agrega una imagen para publicar en Mozilla Pulse.

Una vez completes estas tareas...
- [ ] Escribe un comentario diciendo `This is ready for Mozilla Pulse`. Tu community wranglerrevisará tu proyecto y lo publicará :balloon:

Si te bloqueas en algún punto, ve a los  [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) y [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) o contacta a @jvallera. Estamos acá para ayudarte!

**Comment by jvallera** [comment]
Muy Bien! Very happy to see this. I submitted a change to the license because I did not see one. You can merge it if it looks ok. I think the most immediate needs for this are:

1. Complete the readme file
2. Complete the contribute file
3. Create at least 5 issues so people can start jumping in. 

Once these things are complete I can add the project to our Network Pulse site. 
@Carotejada let me know what you think.

Gracias!

**Comment by Carotejada** [comment]
Thank @jvallera! Working on those tasks. I will also try to have a Spanish - English version of this project.

**Comment by abbycabs** [comment]
Just wanted to say that I'm loving this! Nice work @Carotejada

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
