### ISSUE TITLE
Mozilla2School

### ISSUE THREAD

**Issue by cskumaresan** [mozilla/global-sprint#99]
**[ Project Contact ]** @cskumaresan
**[ GitHub Repo ]** https://github.com/cskumaresan/m2s
**[ Track ]** Web Literacy, Privacy + Security
**[ Community ]** 
**[ Location ]** Kochi,Kerala,India (Time zone IST)
### Description
Introduce young school-going students to the internet and help them to explore it and make them aware of the power of internet. The initiative also introduces these young minds to the latest technology and give practical trainings on using it.

We are planning a different methodology for this project in order to enhance its practical output. We introduce new technologies in both software and hardware programming to the students and give them the complete range of scope to choose from.
***

## Want to contribute to this project during #mozsprint?
Join us at the [Global Sprint, June 1-2](https://mozilla.github.io/global-sprint). Leave a comment below if you're interested in contributing to this project during #mozsprint 2017!

***

## Note to the Project Lead :tada:
Congrats, @cskumaresan! This is your official project listing for the [Mozilla Global Sprint 2017](https://mozilla.github.io/global-sprint). To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project in a comment
  * new to GitHub?  Here's a [step-by-step guide on using the #mozsprint template](https://mozilla.github.io/global-sprint/project-lead/templates/)
- [x] Create a README file in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
* [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead/templates/#4-create-issues) and create issues to describe each task that you need help with and how a contributor can get started on that task. [Create a label](https://mozilla.github.io/global-sprint/project-lead/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/). 

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or write your own code of conduct.
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] Comment with an image to use on Mozilla Pulse for this project listing

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready for Mozilla Pulse`. Your community wrangler will review this issue and post your project :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead/templates/) or reach out to your community wrangler, @zee-moz. We're here to help you through this process.

**Comment by cskumaresan** [comment]
This is ready for Mozilla Pulse

**Comment by cskumaresan** [comment]
This is ready for Mozilla Pulse

**Comment by himankpathak** [comment]
Hey I'm Himank. I have skills in design, writing, web and I would like to help out on this project.

**Comment by olditshweu** [comment]
Hi, I'm Olebile, I have an interest in bridging the gap of Web Literacy especially in schools and would love to partake on this project.

**Comment by xellpher** [comment]
Hi, my name is Mikko and I'd be interested in bringing my experience in bringing Web Literacy to the classroom. I am a teacher and have been doing it for some years now.

**Comment by cbaba20** [comment]
Hi Kumar,
I would Like to join this project in the sprint.

**Comment by cskumaresan** [comment]
@himankpathak  @olditshweu @xellpher @cbaba20 You can be a part of this by join to this [group](https://gitter.im/Mozilla2School/Lobby)

**Comment by abbycabs** [comment]
Thanks for participating in #mozsprint 2017! We're gearing up for 2018 and closing all the issues from last year. Want to bring your project to #mozsprint 2018, May 10-11? [Our Call for Projects](https://foundation.mozilla.org/opportunity/global-sprint/for-project-leads/) is open!

**Comment by abbycabs** [comment]
Updated link for the call for projects!: https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/
